/**
 * PCC, QoS, and Traffic Control Data API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "DefaultPolicyDecisionsApiImpl.h"
#include "api_response.h"

namespace oai::pcf::provisioning::api {

using namespace oai::pcf::api;

DefaultPolicyDecisionsApiImpl::DefaultPolicyDecisionsApiImpl(
    const std::shared_ptr<Pistache::Rest::Router>& rtr)
    : DefaultPolicyDecisionsApi(rtr) {
  m_api_handler = std::make_shared<default_policy_decisions_handler>(
      default_policy_decisions_handler());
}

void DefaultPolicyDecisionsApiImpl::default_decision_get(
    Pistache::Http::ResponseWriter& response) {
  api_response resp  = m_api_handler->default_decision_get();
  response.headers() = resp.headers;
  response.send(Pistache::Http::Code(resp.status_code), resp.body);
}
void DefaultPolicyDecisionsApiImpl::default_decision_put(
    const std::vector<std::string>& pccRules,
    Pistache::Http::ResponseWriter& response) {
  api_response resp  = m_api_handler->default_decision_put(pccRules);
  response.headers() = resp.headers;
  response.send(Pistache::Http::Code(resp.status_code), resp.body);
}

}  // namespace oai::pcf::provisioning::api
