/**
 * PCC, QoS, and Traffic Control Data API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * DefaultPolicyDecisionsApiImpl.h
 *
 *
 */

#ifndef DEFAULT_POLICY_DECISIONS_API_IMPL_H_
#define DEFAULT_POLICY_DECISIONS_API_IMPL_H_

#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>
#include <optional>

#include "DefaultPolicyDecisionsApi.h"
#include "default_policy_decisions_handler.h"

#include <string>
#include <vector>

namespace oai::pcf::provisioning::api {

class DefaultPolicyDecisionsApiImpl
    : public oai::pcf::provisioning::api::DefaultPolicyDecisionsApi {
 public:
  explicit DefaultPolicyDecisionsApiImpl(
      const std::shared_ptr<Pistache::Rest::Router>& rtr);
  ~DefaultPolicyDecisionsApiImpl() override = default;

  void default_decision_get(Pistache::Http::ResponseWriter& response);
  void default_decision_put(
      const std::vector<std::string>& pccRules,
      Pistache::Http::ResponseWriter& response);

 private:
  std::shared_ptr<default_policy_decisions_handler> m_api_handler;
};

}  // namespace oai::pcf::provisioning::api

#endif
