/**
 * PCC, QoS, and Traffic Control Data API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * DNNPolicyDecisionsApiImpl.h
 *
 *
 */

#ifndef DNN_POLICY_DECISIONS_API_IMPL_H_
#define DNN_POLICY_DECISIONS_API_IMPL_H_

#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>
#include <optional>

#include "DNNPolicyDecisionsApi.h"
#include "dnn_policy_decisions_handler.h"

#include "DnnPolicyDecision.h"
#include <string>

namespace oai::pcf::provisioning::api {

using namespace oai::pcf::provisioning::model;

class DNNPolicyDecisionsApiImpl
    : public oai::pcf::provisioning::api::DNNPolicyDecisionsApi {
 public:
  explicit DNNPolicyDecisionsApiImpl(
      const std::shared_ptr<Pistache::Rest::Router>& rtr);
  ~DNNPolicyDecisionsApiImpl() override = default;

  void dnn_policy_decision_dnn_delete(
      const std::string& dnn, Pistache::Http::ResponseWriter& response);
  void dnn_policy_decision_dnn_get(
      const std::string& dnn, Pistache::Http::ResponseWriter& response);
  void dnn_policy_decision_dnn_put(
      const std::string& dnn, const DnnPolicyDecision& dnnPolicyDecision,
      Pistache::Http::ResponseWriter& response);
  void dnn_policy_decision_post(
      const DnnPolicyDecision& dnnPolicyDecision,
      Pistache::Http::ResponseWriter& response);
  void dnn_policy_decisions_get(Pistache::Http::ResponseWriter& response);

 private:
  std::shared_ptr<dnn_policy_decisions_handler> m_api_handler;
};

}  // namespace oai::pcf::provisioning::api

#endif
