/**
 * PCC, QoS, and Traffic Control Data API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "PCCRulesApiImpl.h"

namespace oai::pcf::provisioning::api {

using namespace oai::model::pcf;
using namespace oai::pcf::api;

PCCRulesApiImpl::PCCRulesApiImpl(
    const std::shared_ptr<Pistache::Rest::Router>& rtr)
    : PCCRulesApi(rtr) {}

void PCCRulesApiImpl::pcc_rule_pcc_rule_id_delete(
    const std::string& pccRuleId, Pistache::Http::ResponseWriter& response) {
  api_response resp  = m_api_handler->pcc_rule_pcc_rule_id_delete(pccRuleId);
  response.headers() = resp.headers;
  response.send(Pistache::Http::Code(resp.status_code), resp.body);
}
void PCCRulesApiImpl::pcc_rule_pcc_rule_id_get(
    const std::string& pccRuleId, Pistache::Http::ResponseWriter& response) {
  api_response resp  = m_api_handler->pcc_rule_pcc_rule_id_get(pccRuleId);
  response.headers() = resp.headers;
  response.send(Pistache::Http::Code(resp.status_code), resp.body);
}
void PCCRulesApiImpl::pcc_rule_pcc_rule_id_put(
    const std::string& pccRuleId, const PccRule& pccRule,
    Pistache::Http::ResponseWriter& response) {
  api_response resp =
      m_api_handler->pcc_rule_pcc_rule_id_put(pccRuleId, pccRule);
  response.headers() = resp.headers;
  response.send(Pistache::Http::Code(resp.status_code), resp.body);
}
void PCCRulesApiImpl::pcc_rule_post(
    const PccRule& pccRule, Pistache::Http::ResponseWriter& response) {
  api_response resp  = m_api_handler->pcc_rule_post(pccRule);
  response.headers() = resp.headers;
  response.send(Pistache::Http::Code(resp.status_code), resp.body);
}
void PCCRulesApiImpl::pcc_rules_get(Pistache::Http::ResponseWriter& response) {
  api_response resp  = m_api_handler->pcc_rules_get();
  response.headers() = resp.headers;
  response.send(Pistache::Http::Code(resp.status_code), resp.body);
}

}  // namespace oai::pcf::provisioning::api
