/**
 * PCC, QoS, and Traffic Control Data API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * QOSRulesApiImpl.h
 *
 *
 */

#ifndef QOS_RULES_API_IMPL_H_
#define QOS_RULES_API_IMPL_H_

#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>
#include <optional>

#include "QOSDataApi.h"
#include "qos_data_handler.h"

#include "QosData.h"
#include <string>

namespace oai::pcf::provisioning::api {

using namespace oai::model::pcf;

class QOSDataApiImpl : public oai::pcf::provisioning::api::QOSDataApi {
 public:
  explicit QOSDataApiImpl(const std::shared_ptr<Pistache::Rest::Router>& rtr);
  ~QOSDataApiImpl() override = default;

  void qos_data_get(Pistache::Http::ResponseWriter& response);
  void qos_data_post(
      const QosData& qosData, Pistache::Http::ResponseWriter& response);
  void qos_data_qos_id_delete(
      const std::string& qosId, Pistache::Http::ResponseWriter& response);
  void qos_data_qos_id_get(
      const std::string& qosId, Pistache::Http::ResponseWriter& response);
  void qos_data_qos_id_put(
      const std::string& qosId, const QosData& qosData,
      Pistache::Http::ResponseWriter& response);

 private:
  std::shared_ptr<qos_data_handler> m_api_handler;
};

}  // namespace oai::pcf::provisioning::api

#endif
