/**
 * PCC, QoS, and Traffic Control Data API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "QOSDataApiImpl.h"

namespace oai::pcf::provisioning::api {

using namespace oai::model::pcf;
using namespace oai::pcf::api;

QOSDataApiImpl::QOSDataApiImpl(
    const std::shared_ptr<Pistache::Rest::Router>& rtr)
    : QOSDataApi(rtr) {}

void QOSDataApiImpl::qos_data_get(Pistache::Http::ResponseWriter& response) {
  api_response resp  = m_api_handler->qos_data_get();
  response.headers() = resp.headers;
  response.send(Pistache::Http::Code(resp.status_code), resp.body);
}
void QOSDataApiImpl::qos_data_post(
    const QosData& qosData, Pistache::Http::ResponseWriter& response) {
  api_response resp  = m_api_handler->qos_data_post(qosData);
  response.headers() = resp.headers;
  response.send(Pistache::Http::Code(resp.status_code), resp.body);
}
void QOSDataApiImpl::qos_data_qos_id_delete(
    const std::string& qosId, Pistache::Http::ResponseWriter& response) {
  api_response resp  = m_api_handler->qos_data_qos_id_delete(qosId);
  response.headers() = resp.headers;
  response.send(Pistache::Http::Code(resp.status_code), resp.body);
}
void QOSDataApiImpl::qos_data_qos_id_get(
    const std::string& qosId, Pistache::Http::ResponseWriter& response) {
  api_response resp  = m_api_handler->qos_data_qos_id_get(qosId);
  response.headers() = resp.headers;
  response.send(Pistache::Http::Code(resp.status_code), resp.body);
}
void QOSDataApiImpl::qos_data_qos_id_put(
    const std::string& qosId, const QosData& qosData,
    Pistache::Http::ResponseWriter& response) {
  api_response resp  = m_api_handler->qos_data_qos_id_put(qosId, qosData);
  response.headers() = resp.headers;
  response.send(Pistache::Http::Code(resp.status_code), resp.body);
}

}  // namespace oai::pcf::provisioning::api
