/**
 * PCC, QoS, and Traffic Control Data API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "SlicePolicyDecisionsApiImpl.h"

namespace oai::pcf::provisioning::api {

using namespace oai::pcf::provisioning::model;
using namespace oai::pcf::api;

SlicePolicyDecisionsApiImpl::SlicePolicyDecisionsApiImpl(
    const std::shared_ptr<Pistache::Rest::Router>& rtr)
    : SlicePolicyDecisionsApi(rtr) {}

void SlicePolicyDecisionsApiImpl::slice_policy_decision_delete(
    const std::optional<int32_t>& sst, const std::optional<std::string>& sd,
    Pistache::Http::ResponseWriter& response) {
  api_response resp  = m_api_handler->slice_policy_decision_delete(sst, sd);
  response.headers() = resp.headers;
  response.send(Pistache::Http::Code(resp.status_code), resp.body);
}
void SlicePolicyDecisionsApiImpl::slice_policy_decision_get(
    const std::optional<int32_t>& sst, const std::optional<std::string>& sd,
    Pistache::Http::ResponseWriter& response) {
  api_response resp  = m_api_handler->slice_policy_decision_get(sst, sd);
  response.headers() = resp.headers;
  response.send(Pistache::Http::Code(resp.status_code), resp.body);
}
void SlicePolicyDecisionsApiImpl::slice_policy_decision_post(
    const SlicePolicyDecision& slicePolicyDecision,
    Pistache::Http::ResponseWriter& response) {
  api_response resp =
      m_api_handler->slice_policy_decision_post(slicePolicyDecision);
  response.headers() = resp.headers;
  response.send(Pistache::Http::Code(resp.status_code), resp.body);
}
void SlicePolicyDecisionsApiImpl::slice_policy_decision_put(
    const std::optional<int32_t>& sst, const std::optional<std::string>& sd,
    const SlicePolicyDecision& slicePolicyDecision,
    Pistache::Http::ResponseWriter& response) {
  api_response resp =
      m_api_handler->slice_policy_decision_put(sst, sd, slicePolicyDecision);
  response.headers() = resp.headers;
  response.send(Pistache::Http::Code(resp.status_code), resp.body);
}
void SlicePolicyDecisionsApiImpl::slice_policy_decisions_get(
    Pistache::Http::ResponseWriter& response) {
  api_response resp  = m_api_handler->slice_policy_decisions_get();
  response.headers() = resp.headers;
  response.send(Pistache::Http::Code(resp.status_code), resp.body);
}

}  // namespace oai::pcf::provisioning::api
