/**
 * PCC, QoS, and Traffic Control Data API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * SlicePolicyDecisionsApiImpl.h
 *
 *
 */

#ifndef SLICE_POLICY_DECISIONS_API_IMPL_H_
#define SLICE_POLICY_DECISIONS_API_IMPL_H_

#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>
#include <optional>

#include "SlicePolicyDecisionsApi.h"
#include "slice_policy_decisions_handler.h"

#include "SlicePolicyDecision.h"
#include <string>

namespace oai::pcf::provisioning::api {

using namespace oai::pcf::provisioning::model;

class SlicePolicyDecisionsApiImpl
    : public oai::pcf::provisioning::api::SlicePolicyDecisionsApi {
 public:
  explicit SlicePolicyDecisionsApiImpl(
      const std::shared_ptr<Pistache::Rest::Router>& rtr);
  ~SlicePolicyDecisionsApiImpl() override = default;

  void slice_policy_decision_delete(
      const std::optional<int32_t>& sst, const std::optional<std::string>& sd,
      Pistache::Http::ResponseWriter& response);
  void slice_policy_decision_get(
      const std::optional<int32_t>& sst, const std::optional<std::string>& sd,
      Pistache::Http::ResponseWriter& response);
  void slice_policy_decision_post(
      const SlicePolicyDecision& slicePolicyDecision,
      Pistache::Http::ResponseWriter& response);
  void slice_policy_decision_put(
      const std::optional<int32_t>& sst, const std::optional<std::string>& sd,
      const SlicePolicyDecision& slicePolicyDecision,
      Pistache::Http::ResponseWriter& response);
  void slice_policy_decisions_get(Pistache::Http::ResponseWriter& response);

 private:
  std::shared_ptr<slice_policy_decisions_handler> m_api_handler;
};

}  // namespace oai::pcf::provisioning::api

#endif
