/**
 * PCC, QoS, and Traffic Control Data API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * SupiPolicyDecisionsApiImpl.h
 *
 *
 */

#ifndef SUPI_POLICY_DECISIONS_API_IMPL_H_
#define SUPI_POLICY_DECISIONS_API_IMPL_H_

#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>
#include <optional>

#include "SupiPolicyDecisionsApi.h"
#include "supi_policy_decisions_handler.h"

#include "SupiPolicyDecision.h"
#include <string>

namespace oai::pcf::provisioning::api {

using namespace oai::pcf::provisioning::model;

class SupiPolicyDecisionsApiImpl
    : public oai::pcf::provisioning::api::SupiPolicyDecisionsApi {
 public:
  explicit SupiPolicyDecisionsApiImpl(
      const std::shared_ptr<Pistache::Rest::Router>& rtr);
  ~SupiPolicyDecisionsApiImpl() override = default;

  void supi_policy_decision_post(
      const SupiPolicyDecision& supiPolicyDecision,
      Pistache::Http::ResponseWriter& response);
  void supi_policy_decision_supi_delete(
      const std::string& supi, Pistache::Http::ResponseWriter& response);
  void supi_policy_decision_supi_get(
      const std::string& supi, Pistache::Http::ResponseWriter& response);
  void supi_policy_decision_supi_put(
      const std::string& supi, const SupiPolicyDecision& supiPolicyDecision,
      Pistache::Http::ResponseWriter& response);
  void supi_policy_decisions_get(Pistache::Http::ResponseWriter& response);

 private:
  std::shared_ptr<supi_policy_decisions_handler> m_api_handler;
};

}  // namespace oai::pcf::provisioning::api

#endif
