/**
 * PCC, QoS, and Traffic Control Data API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "SupiPolicyDecisionsApiImpl.h"

namespace oai::pcf::provisioning::api {

using namespace oai::pcf::provisioning::model;
using namespace oai::pcf::api;

SupiPolicyDecisionsApiImpl::SupiPolicyDecisionsApiImpl(
    const std::shared_ptr<Pistache::Rest::Router>& rtr)
    : SupiPolicyDecisionsApi(rtr) {}

void SupiPolicyDecisionsApiImpl::supi_policy_decision_post(
    const SupiPolicyDecision& supiPolicyDecision,
    Pistache::Http::ResponseWriter& response) {
  api_response resp =
      m_api_handler->supi_policy_decision_post(supiPolicyDecision);
  response.headers() = resp.headers;
  response.send(Pistache::Http::Code(resp.status_code), resp.body);
}
void SupiPolicyDecisionsApiImpl::supi_policy_decision_supi_delete(
    const std::string& supi, Pistache::Http::ResponseWriter& response) {
  api_response resp  = m_api_handler->supi_policy_decision_supi_delete(supi);
  response.headers() = resp.headers;
  response.send(Pistache::Http::Code(resp.status_code), resp.body);
}
void SupiPolicyDecisionsApiImpl::supi_policy_decision_supi_get(
    const std::string& supi, Pistache::Http::ResponseWriter& response) {
  api_response resp  = m_api_handler->supi_policy_decision_supi_get(supi);
  response.headers() = resp.headers;
  response.send(Pistache::Http::Code(resp.status_code), resp.body);
}
void SupiPolicyDecisionsApiImpl::supi_policy_decision_supi_put(
    const std::string& supi, const SupiPolicyDecision& supiPolicyDecision,
    Pistache::Http::ResponseWriter& response) {
  api_response resp =
      m_api_handler->supi_policy_decision_supi_put(supi, supiPolicyDecision);
  response.headers() = resp.headers;
  response.send(Pistache::Http::Code(resp.status_code), resp.body);
}
void SupiPolicyDecisionsApiImpl::supi_policy_decisions_get(
    Pistache::Http::ResponseWriter& response) {
  api_response resp  = m_api_handler->supi_policy_decisions_get();
  response.headers() = resp.headers;
  response.send(Pistache::Http::Code(resp.status_code), resp.body);
}

}  // namespace oai::pcf::provisioning::api
