/**
 * PCC, QoS, and Traffic Control Data API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "TrafficControlDataApiImpl.h"

namespace oai::pcf::provisioning::api {

using namespace oai::model::pcf;
using namespace oai::pcf::api;

TrafficControlDataApiImpl::TrafficControlDataApiImpl(
    const std::shared_ptr<Pistache::Rest::Router>& rtr)
    : TrafficControlDataApi(rtr) {}

void TrafficControlDataApiImpl::traffic_control_data_get(
    Pistache::Http::ResponseWriter& response) {
  api_response resp  = m_api_handler->traffic_control_data_get();
  response.headers() = resp.headers;
  response.send(Pistache::Http::Code(resp.status_code), resp.body);
}
void TrafficControlDataApiImpl::traffic_control_data_post(
    const TrafficControlData& trafficControlData,
    Pistache::Http::ResponseWriter& response) {
  api_response resp =
      m_api_handler->traffic_control_data_post(trafficControlData);
  response.headers() = resp.headers;
  response.send(Pistache::Http::Code(resp.status_code), resp.body);
}
void TrafficControlDataApiImpl::traffic_control_data_tc_id_delete(
    const std::string& tcId, Pistache::Http::ResponseWriter& response) {
  api_response resp  = m_api_handler->traffic_control_data_tc_id_delete(tcId);
  response.headers() = resp.headers;
  response.send(Pistache::Http::Code(resp.status_code), resp.body);
}
void TrafficControlDataApiImpl::traffic_control_data_tc_id_get(
    const std::string& tcId, Pistache::Http::ResponseWriter& response) {
  api_response resp  = m_api_handler->traffic_control_data_tc_id_get(tcId);
  response.headers() = resp.headers;
  response.send(Pistache::Http::Code(resp.status_code), resp.body);
}
void TrafficControlDataApiImpl::traffic_control_data_tc_id_put(
    const std::string& tcId, const TrafficControlData& trafficControlData,
    Pistache::Http::ResponseWriter& response) {
  api_response resp =
      m_api_handler->traffic_control_data_tc_id_put(tcId, trafficControlData);
  response.headers() = resp.headers;
  response.send(Pistache::Http::Code(resp.status_code), resp.body);
}

}  // namespace oai::pcf::provisioning::api
