/**
 * PCC, QoS, and Traffic Control Data API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * TrafficControlDataApiImpl.h
 *
 *
 */

#ifndef TRAFFIC_CONTROL_DATA_API_IMPL_H_
#define TRAFFIC_CONTROL_DATA_API_IMPL_H_

#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>
#include <optional>

#include "TrafficControlDataApi.h"
#include "traffic_control_data_handler.h"

#include "TrafficControlData.h"
#include <string>

namespace oai::pcf::provisioning::api {

using namespace oai::model::pcf;

class TrafficControlDataApiImpl
    : public oai::pcf::provisioning::api::TrafficControlDataApi {
 public:
  explicit TrafficControlDataApiImpl(
      const std::shared_ptr<Pistache::Rest::Router>& rtr);
  ~TrafficControlDataApiImpl() override = default;

  void traffic_control_data_get(Pistache::Http::ResponseWriter& response);
  void traffic_control_data_post(
      const TrafficControlData& trafficControlData,
      Pistache::Http::ResponseWriter& response);
  void traffic_control_data_tc_id_delete(
      const std::string& tcId, Pistache::Http::ResponseWriter& response);
  void traffic_control_data_tc_id_get(
      const std::string& tcId, Pistache::Http::ResponseWriter& response);
  void traffic_control_data_tc_id_put(
      const std::string& tcId, const TrafficControlData& trafficControlData,
      Pistache::Http::ResponseWriter& response);

 private:
  std::shared_ptr<traffic_control_data_handler> m_api_handler;
};

}  // namespace oai::pcf::provisioning::api

#endif
