/**
 * Npcf_SMPolicyControl API
 * Session Management Policy Control Service   © 2024, 3GPP Organizational
 * Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.3.0-alpha.6
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * ApiBase.h
 *
 * Generalization of the Api classes
 */

#ifndef ApiBase_H_
#define ApiBase_H_

#include <pistache/router.h>
#include <memory>

namespace oai::pcf::api {

class ApiBase {
 public:
  explicit ApiBase(const std::shared_ptr<Pistache::Rest::Router>& rtr)
      : router(rtr){};
  virtual ~ApiBase()  = default;
  virtual void init() = 0;

 protected:
  const std::shared_ptr<Pistache::Rest::Router> router;
};

}  // namespace oai::pcf::api

#endif /* ApiBase_H_ */
