/**
 * Npcf_PolicyAuthorization Service API
 * PCF Policy Authorization Service.   © 2024, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.3.0-alpha.6
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * ApplicationSessionsCollectionApi.h
 *
 *
 */

#ifndef ApplicationSessionsCollectionApi_H_
#define ApplicationSessionsCollectionApi_H_

#include "ApiBase.h"

#include <pistache/http.h>
#include <pistache/router.h>
#include <pistache/http_headers.h>

#include <optional>
#include <utility>

#include "AppSessionContext.h"
#include "ExtendedProblemDetails.h"
#include "ProblemDetails.h"
#include <string>

namespace oai::pcf::api {

class ApplicationSessionsCollectionApi : public ApiBase {
 public:
  explicit ApplicationSessionsCollectionApi(
      const std::shared_ptr<Pistache::Rest::Router>& rtr);
  ~ApplicationSessionsCollectionApi() override = default;
  void init() override;

  static const std::string base;

 private:
  void setupRoutes();

  void post_app_sessions_handler(
      const Pistache::Rest::Request& request,
      Pistache::Http::ResponseWriter response);
  void application_sessions_collection_api_default_handler(
      const Pistache::Rest::Request& request,
      Pistache::Http::ResponseWriter response);

  /// <summary>
  /// Helper function to handle unexpected Exceptions during Parameter parsing
  /// and validation. May be overridden to return custom error formats. This is
  /// called inside a catch block. Important: When overriding, do not call
  /// `throw ex;`, but instead use `throw;`.
  /// </summary>
  virtual std::pair<Pistache::Http::Code, std::string> handleParsingException(
      const std::exception& ex) const noexcept;

  /// <summary>
  /// Helper function to handle unexpected Exceptions during processing of the
  /// request in handler functions. May be overridden to return custom error
  /// formats. This is called inside a catch block. Important: When overriding,
  /// do not call `throw ex;`, but instead use `throw;`.
  /// </summary>
  virtual std::pair<Pistache::Http::Code, std::string> handleOperationException(
      const std::exception& ex) const noexcept;

  /// <summary>
  /// Creates a new Individual Application Session Context resource
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  /// <param name="appSessionContext">Contains the information for the creation
  /// the resource.</param>
  virtual void post_app_sessions(
      const oai::model::pcf::AppSessionContext& appSessionContext,
      Pistache::Http::ResponseWriter& response) = 0;
};

}  // namespace oai::pcf::api

#endif /* ApplicationSessionsCollectionApi_H_ */
