/**
 * Npcf_PolicyAuthorization Service API
 * PCF Policy Authorization Service.   © 2024, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.3.0-alpha.6
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "ApplicationSessionsCollectionApi.h"
#include "Helpers.h"
#include "api_defs.h"

namespace oai::pcf::api {

using namespace oai::model::common::helpers;
using namespace oai::model::pcf;

ApplicationSessionsCollectionApi::ApplicationSessionsCollectionApi(
    const std::shared_ptr<Pistache::Rest::Router>& rtr)
    : ApiBase(rtr) {}

void ApplicationSessionsCollectionApi::init() {
  setupRoutes();
}

void ApplicationSessionsCollectionApi::setupRoutes() {
  using namespace Pistache::Rest;

  Routes::Post(
      *router, app_sessions::get_route(),
      Routes::bind(
          &ApplicationSessionsCollectionApi::post_app_sessions_handler, this));

  // Default handler, called when a route is not found
  router->addCustomHandler(Routes::bind(
      &ApplicationSessionsCollectionApi::
          application_sessions_collection_api_default_handler,
      this));
}

std::pair<Pistache::Http::Code, std::string>
ApplicationSessionsCollectionApi::handleParsingException(
    const std::exception& ex) const noexcept {
  try {
    throw;
  } catch (nlohmann::detail::exception& e) {
    return std::make_pair(Pistache::Http::Code::Bad_Request, e.what());
  } catch (oai::model::common::helpers::ValidationException& e) {
    return std::make_pair(Pistache::Http::Code::Bad_Request, e.what());
  } catch (std::exception& e) {
    return std::make_pair(
        Pistache::Http::Code::Internal_Server_Error, e.what());
  }
}

std::pair<Pistache::Http::Code, std::string>
ApplicationSessionsCollectionApi::handleOperationException(
    const std::exception& ex) const noexcept {
  return std::make_pair(Pistache::Http::Code::Internal_Server_Error, ex.what());
}

void ApplicationSessionsCollectionApi::post_app_sessions_handler(
    const Pistache::Rest::Request& request,
    Pistache::Http::ResponseWriter response) {
  try {
    // Getting the body param

    AppSessionContext appSessionContext;

    try {
      nlohmann::json::parse(request.body()).get_to(appSessionContext);
      appSessionContext.validate();
    } catch (std::exception& e) {
      const std::pair<Pistache::Http::Code, std::string> errorInfo =
          this->handleParsingException(e);
      response.send(errorInfo.first, errorInfo.second);
      return;
    }

    try {
      this->post_app_sessions(appSessionContext, response);
    } catch (Pistache::Http::HttpError& e) {
      response.send(static_cast<Pistache::Http::Code>(e.code()), e.what());
      return;
    } catch (std::exception& e) {
      const std::pair<Pistache::Http::Code, std::string> errorInfo =
          this->handleOperationException(e);
      response.send(errorInfo.first, errorInfo.second);
      return;
    }

  } catch (std::exception& e) {
    response.send(Pistache::Http::Code::Internal_Server_Error, e.what());
  }
}

void ApplicationSessionsCollectionApi::
    application_sessions_collection_api_default_handler(
        const Pistache::Rest::Request&,
        Pistache::Http::ResponseWriter response) {
  response.send(
      Pistache::Http::Code::Not_Found, "The requested method does not exist");
}

}  // namespace oai::pcf::api
