/**
 * Npcf_PolicyAuthorization Service API
 * PCF Policy Authorization Service.   © 2024, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.3.0-alpha.6
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "EventsSubscriptionDocumentApi.h"
#include "Helpers.h"
#include "api_defs.h"

namespace oai::pcf::api {

using namespace oai::model::common::helpers;
using namespace oai::model::pcf;

EventsSubscriptionDocumentApi::EventsSubscriptionDocumentApi(
    const std::shared_ptr<Pistache::Rest::Router>& rtr)
    : ApiBase(rtr) {}

void EventsSubscriptionDocumentApi::init() {
  setupRoutes();
}

void EventsSubscriptionDocumentApi::setupRoutes() {
  using namespace Pistache::Rest;

  Routes::Delete(
      *router, app_sessions::get_route() + "/:appSessionId/events-subscription",
      Routes::bind(
          &EventsSubscriptionDocumentApi::delete_events_subsc_handler, this));
  Routes::Put(
      *router, app_sessions::get_route() + "/:appSessionId/events-subscription",
      Routes::bind(
          &EventsSubscriptionDocumentApi::update_events_subsc_handler, this));

  // Default handler, called when a route is not found
  router->addCustomHandler(Routes::bind(
      &EventsSubscriptionDocumentApi::
          events_subscription_document_api_default_handler,
      this));
}

std::pair<Pistache::Http::Code, std::string>
EventsSubscriptionDocumentApi::handleParsingException(
    const std::exception& ex) const noexcept {
  try {
    throw;
  } catch (nlohmann::detail::exception& e) {
    return std::make_pair(Pistache::Http::Code::Bad_Request, e.what());
  } catch (oai::model::common::helpers::ValidationException& e) {
    return std::make_pair(Pistache::Http::Code::Bad_Request, e.what());
  } catch (std::exception& e) {
    return std::make_pair(
        Pistache::Http::Code::Internal_Server_Error, e.what());
  }
}

std::pair<Pistache::Http::Code, std::string>
EventsSubscriptionDocumentApi::handleOperationException(
    const std::exception& ex) const noexcept {
  return std::make_pair(Pistache::Http::Code::Internal_Server_Error, ex.what());
}

void EventsSubscriptionDocumentApi::delete_events_subsc_handler(
    const Pistache::Rest::Request& request,
    Pistache::Http::ResponseWriter response) {
  try {
    // Getting the path params
    auto appSessionId = request.param(":appSessionId").as<std::string>();

    try {
      this->delete_events_subsc(appSessionId, response);
    } catch (Pistache::Http::HttpError& e) {
      response.send(static_cast<Pistache::Http::Code>(e.code()), e.what());
      return;
    } catch (std::exception& e) {
      const std::pair<Pistache::Http::Code, std::string> errorInfo =
          this->handleOperationException(e);
      response.send(errorInfo.first, errorInfo.second);
      return;
    }

  } catch (std::exception& e) {
    response.send(Pistache::Http::Code::Internal_Server_Error, e.what());
  }
}
void EventsSubscriptionDocumentApi::update_events_subsc_handler(
    const Pistache::Rest::Request& request,
    Pistache::Http::ResponseWriter response) {
  try {
    // Getting the path params
    auto appSessionId = request.param(":appSessionId").as<std::string>();

    // Getting the body param

    EventsSubscReqData eventsSubscReqData;

    try {
      nlohmann::json::parse(request.body()).get_to(eventsSubscReqData);
      eventsSubscReqData.validate();
    } catch (std::exception& e) {
      const std::pair<Pistache::Http::Code, std::string> errorInfo =
          this->handleParsingException(e);
      response.send(errorInfo.first, errorInfo.second);
      return;
    }

    try {
      this->update_events_subsc(appSessionId, eventsSubscReqData, response);
    } catch (Pistache::Http::HttpError& e) {
      response.send(static_cast<Pistache::Http::Code>(e.code()), e.what());
      return;
    } catch (std::exception& e) {
      const std::pair<Pistache::Http::Code, std::string> errorInfo =
          this->handleOperationException(e);
      response.send(errorInfo.first, errorInfo.second);
      return;
    }

  } catch (std::exception& e) {
    response.send(Pistache::Http::Code::Internal_Server_Error, e.what());
  }
}

void EventsSubscriptionDocumentApi::
    events_subscription_document_api_default_handler(
        const Pistache::Rest::Request&,
        Pistache::Http::ResponseWriter response) {
  response.send(
      Pistache::Http::Code::Not_Found, "The requested method does not exist");
}

}  // namespace oai::pcf::api
