/**
 * Npcf_PolicyAuthorization Service API
 * PCF Policy Authorization Service.   © 2024, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.3.0-alpha.6
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * EventsSubscriptionDocumentApi.h
 *
 *
 */

#ifndef EventsSubscriptionDocumentApi_H_
#define EventsSubscriptionDocumentApi_H_

#include "ApiBase.h"

#include <pistache/http.h>
#include <pistache/router.h>
#include <pistache/http_headers.h>

#include <optional>
#include <utility>

#include "EventsSubscPutData.h"
#include "EventsSubscReqData.h"
#include "ProblemDetails.h"
#include "RedirectResponse.h"
#include <string>

namespace oai::pcf::api {

class EventsSubscriptionDocumentApi : public ApiBase {
 public:
  explicit EventsSubscriptionDocumentApi(
      const std::shared_ptr<Pistache::Rest::Router>& rtr);
  ~EventsSubscriptionDocumentApi() override = default;
  void init() override;

  static const std::string base;

 private:
  void setupRoutes();

  void delete_events_subsc_handler(
      const Pistache::Rest::Request& request,
      Pistache::Http::ResponseWriter response);
  void update_events_subsc_handler(
      const Pistache::Rest::Request& request,
      Pistache::Http::ResponseWriter response);
  void events_subscription_document_api_default_handler(
      const Pistache::Rest::Request& request,
      Pistache::Http::ResponseWriter response);

  /// <summary>
  /// Helper function to handle unexpected Exceptions during Parameter parsing
  /// and validation. May be overridden to return custom error formats. This is
  /// called inside a catch block. Important: When overriding, do not call
  /// `throw ex;`, but instead use `throw;`.
  /// </summary>
  virtual std::pair<Pistache::Http::Code, std::string> handleParsingException(
      const std::exception& ex) const noexcept;

  /// <summary>
  /// Helper function to handle unexpected Exceptions during processing of the
  /// request in handler functions. May be overridden to return custom error
  /// formats. This is called inside a catch block. Important: When overriding,
  /// do not call `throw ex;`, but instead use `throw;`.
  /// </summary>
  virtual std::pair<Pistache::Http::Code, std::string> handleOperationException(
      const std::exception& ex) const noexcept;

  /// <summary>
  /// deletes the Events Subscription subresource
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  /// <param name="appSessionId">String identifying the Individual Application
  /// Session Context resource.</param>
  virtual void delete_events_subsc(
      const std::string& appSessionId,
      Pistache::Http::ResponseWriter& response) = 0;
  /// <summary>
  /// creates or modifies an Events Subscription subresource
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  /// <param name="appSessionId">String identifying the Events Subscription
  /// resource.</param> <param name="eventsSubscReqData">Creation or
  /// modification of an Events Subscription resource.</param>
  virtual void update_events_subsc(
      const std::string& appSessionId,
      const oai::model::pcf::EventsSubscReqData& eventsSubscReqData,
      Pistache::Http::ResponseWriter& response) = 0;
};

}  // namespace oai::pcf::api

#endif /* EventsSubscriptionDocumentApi_H_ */
