/**
 * Npcf_PolicyAuthorization Service API
 * PCF Policy Authorization Service.   © 2024, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.3.0-alpha.6
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * IndividualApplicationSessionContextDocumentApi.h
 *
 *
 */

#ifndef IndividualApplicationSessionContextDocumentApi_H_
#define IndividualApplicationSessionContextDocumentApi_H_

#include "ApiBase.h"

#include <pistache/http.h>
#include <pistache/router.h>
#include <pistache/http_headers.h>

#include <optional>
#include <utility>

#include "AppSessionContext.h"
#include "AppSessionContextUpdateDataPatch.h"
#include "EventsSubscReqData.h"
#include "ExtendedProblemDetails.h"
#include "ProblemDetails.h"
#include "RedirectResponse.h"
#include <string>

namespace oai::pcf::api {

class IndividualApplicationSessionContextDocumentApi : public ApiBase {
 public:
  explicit IndividualApplicationSessionContextDocumentApi(
      const std::shared_ptr<Pistache::Rest::Router>& rtr);
  ~IndividualApplicationSessionContextDocumentApi() override = default;
  void init() override;

  static const std::string base;

 private:
  void setupRoutes();

  void delete_app_session_handler(
      const Pistache::Rest::Request& request,
      Pistache::Http::ResponseWriter response);
  void get_app_session_handler(
      const Pistache::Rest::Request& request,
      Pistache::Http::ResponseWriter response);
  void mod_app_session_handler(
      const Pistache::Rest::Request& request,
      Pistache::Http::ResponseWriter response);
  void individual_application_session_context_document_api_default_handler(
      const Pistache::Rest::Request& request,
      Pistache::Http::ResponseWriter response);

  /// <summary>
  /// Helper function to handle unexpected Exceptions during Parameter parsing
  /// and validation. May be overridden to return custom error formats. This is
  /// called inside a catch block. Important: When overriding, do not call
  /// `throw ex;`, but instead use `throw;`.
  /// </summary>
  virtual std::pair<Pistache::Http::Code, std::string> handleParsingException(
      const std::exception& ex) const noexcept;

  /// <summary>
  /// Helper function to handle unexpected Exceptions during processing of the
  /// request in handler functions. May be overridden to return custom error
  /// formats. This is called inside a catch block. Important: When overriding,
  /// do not call `throw ex;`, but instead use `throw;`.
  /// </summary>
  virtual std::pair<Pistache::Http::Code, std::string> handleOperationException(
      const std::exception& ex) const noexcept;

  /// <summary>
  /// Deletes an existing Individual Application Session Context
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  /// <param name="appSessionId">String identifying the Individual Application
  /// Session Context resource.</param> <param
  /// name="eventsSubscReqData">Deletion of the Individual Application Session
  /// Context resource, req notification.  (optional)</param>
  virtual void delete_app_session(
      const std::string& appSessionId,
      const oai::model::pcf::EventsSubscReqData& eventsSubscReqData,
      Pistache::Http::ResponseWriter& response) = 0;
  /// <summary>
  /// Reads an existing Individual Application Session Context
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  /// <param name="appSessionId">String identifying the resource.</param>
  virtual void get_app_session(
      const std::string& appSessionId,
      Pistache::Http::ResponseWriter& response) = 0;
  /// <summary>
  /// Modifies an existing Individual Application Session Context
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  /// <param name="appSessionId">String identifying the resource.</param>
  /// <param name="appSessionContextUpdateDataPatch">Modification of the
  /// resource.</param>
  virtual void mod_app_session(
      const std::string& appSessionId,
      const oai::model::pcf::AppSessionContextUpdateDataPatch&
          appSessionContextUpdateDataPatch,
      Pistache::Http::ResponseWriter& response) = 0;
};

}  // namespace oai::pcf::api

#endif /* IndividualApplicationSessionContextDocumentApi_H_ */
