/**
 * Npcf_PolicyAuthorization Service API
 * PCF Policy Authorization Service.   © 2024, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.3.0-alpha.6
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "IndividualApplicationSessionContextDocumentApi.h"
#include "Helpers.h"
#include "api_defs.h"

namespace oai::pcf::api {

using namespace oai::model::common::helpers;
using namespace oai::model::pcf;

IndividualApplicationSessionContextDocumentApi::
    IndividualApplicationSessionContextDocumentApi(
        const std::shared_ptr<Pistache::Rest::Router>& rtr)
    : ApiBase(rtr) {}

void IndividualApplicationSessionContextDocumentApi::init() {
  setupRoutes();
}

void IndividualApplicationSessionContextDocumentApi::setupRoutes() {
  using namespace Pistache::Rest;

  Routes::Post(
      *router, app_sessions::get_route() + "/:appSessionId/delete",
      Routes::bind(
          &IndividualApplicationSessionContextDocumentApi::
              delete_app_session_handler,
          this));
  Routes::Get(
      *router, app_sessions::get_route() + "/:appSessionId",
      Routes::bind(
          &IndividualApplicationSessionContextDocumentApi::
              get_app_session_handler,
          this));
  Routes::Patch(
      *router, app_sessions::get_route() + "/:appSessionId",
      Routes::bind(
          &IndividualApplicationSessionContextDocumentApi::
              mod_app_session_handler,
          this));

  // Default handler, called when a route is not found
  router->addCustomHandler(Routes::bind(
      &IndividualApplicationSessionContextDocumentApi::
          individual_application_session_context_document_api_default_handler,
      this));
}

std::pair<Pistache::Http::Code, std::string>
IndividualApplicationSessionContextDocumentApi::handleParsingException(
    const std::exception& ex) const noexcept {
  try {
    throw;
  } catch (nlohmann::detail::exception& e) {
    return std::make_pair(Pistache::Http::Code::Bad_Request, e.what());
  } catch (oai::model::common::helpers::ValidationException& e) {
    return std::make_pair(Pistache::Http::Code::Bad_Request, e.what());
  } catch (std::exception& e) {
    return std::make_pair(
        Pistache::Http::Code::Internal_Server_Error, e.what());
  }
}

std::pair<Pistache::Http::Code, std::string>
IndividualApplicationSessionContextDocumentApi::handleOperationException(
    const std::exception& ex) const noexcept {
  return std::make_pair(Pistache::Http::Code::Internal_Server_Error, ex.what());
}

void IndividualApplicationSessionContextDocumentApi::delete_app_session_handler(
    const Pistache::Rest::Request& request,
    Pistache::Http::ResponseWriter response) {
  try {
    // Getting the path params
    auto appSessionId = request.param(":appSessionId").as<std::string>();

    // Getting the body param

    EventsSubscReqData eventsSubscReqData;

    try {
      nlohmann::json::parse(request.body()).get_to(eventsSubscReqData);
      eventsSubscReqData.validate();
    } catch (std::exception& e) {
      const std::pair<Pistache::Http::Code, std::string> errorInfo =
          this->handleParsingException(e);
      response.send(errorInfo.first, errorInfo.second);
      return;
    }

    try {
      this->delete_app_session(appSessionId, eventsSubscReqData, response);
    } catch (Pistache::Http::HttpError& e) {
      response.send(static_cast<Pistache::Http::Code>(e.code()), e.what());
      return;
    } catch (std::exception& e) {
      const std::pair<Pistache::Http::Code, std::string> errorInfo =
          this->handleOperationException(e);
      response.send(errorInfo.first, errorInfo.second);
      return;
    }

  } catch (std::exception& e) {
    response.send(Pistache::Http::Code::Internal_Server_Error, e.what());
  }
}
void IndividualApplicationSessionContextDocumentApi::get_app_session_handler(
    const Pistache::Rest::Request& request,
    Pistache::Http::ResponseWriter response) {
  try {
    // Getting the path params
    auto appSessionId = request.param(":appSessionId").as<std::string>();

    try {
      this->get_app_session(appSessionId, response);
    } catch (Pistache::Http::HttpError& e) {
      response.send(static_cast<Pistache::Http::Code>(e.code()), e.what());
      return;
    } catch (std::exception& e) {
      const std::pair<Pistache::Http::Code, std::string> errorInfo =
          this->handleOperationException(e);
      response.send(errorInfo.first, errorInfo.second);
      return;
    }

  } catch (std::exception& e) {
    response.send(Pistache::Http::Code::Internal_Server_Error, e.what());
  }
}
void IndividualApplicationSessionContextDocumentApi::mod_app_session_handler(
    const Pistache::Rest::Request& request,
    Pistache::Http::ResponseWriter response) {
  try {
    // Getting the path params
    auto appSessionId = request.param(":appSessionId").as<std::string>();

    // Getting the body param

    AppSessionContextUpdateDataPatch appSessionContextUpdateDataPatch;

    try {
      nlohmann::json::parse(request.body())
          .get_to(appSessionContextUpdateDataPatch);
      appSessionContextUpdateDataPatch.validate();
    } catch (std::exception& e) {
      const std::pair<Pistache::Http::Code, std::string> errorInfo =
          this->handleParsingException(e);
      response.send(errorInfo.first, errorInfo.second);
      return;
    }

    try {
      this->mod_app_session(
          appSessionId, appSessionContextUpdateDataPatch, response);
    } catch (Pistache::Http::HttpError& e) {
      response.send(static_cast<Pistache::Http::Code>(e.code()), e.what());
      return;
    } catch (std::exception& e) {
      const std::pair<Pistache::Http::Code, std::string> errorInfo =
          this->handleOperationException(e);
      response.send(errorInfo.first, errorInfo.second);
      return;
    }

  } catch (std::exception& e) {
    response.send(Pistache::Http::Code::Internal_Server_Error, e.what());
  }
}

void IndividualApplicationSessionContextDocumentApi::
    individual_application_session_context_document_api_default_handler(
        const Pistache::Rest::Request&,
        Pistache::Http::ResponseWriter response) {
  response.send(
      Pistache::Http::Code::Not_Found, "The requested method does not exist");
}

}  // namespace oai::pcf::api
