/**
 * Npcf_PolicyAuthorization Service API
 * PCF Policy Authorization Service.   © 2024, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.3.0-alpha.6
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * PCSCFRestorationIndicationApi.h
 *
 *
 */

#ifndef PCSCFRestorationIndicationApi_H_
#define PCSCFRestorationIndicationApi_H_

#include "ApiBase.h"

#include <pistache/http.h>
#include <pistache/router.h>
#include <pistache/http_headers.h>

#include <optional>
#include <utility>

#include "PcscfRestorationRequestData.h"
#include "ProblemDetails.h"
#include "RedirectResponse.h"
#include <string>

namespace oai::pcf::api {

class PCSCFRestorationIndicationApi : public ApiBase {
 public:
  explicit PCSCFRestorationIndicationApi(
      const std::shared_ptr<Pistache::Rest::Router>& rtr);
  ~PCSCFRestorationIndicationApi() override = default;
  void init() override;

  static const std::string base;

 private:
  void setupRoutes();

  void pcscf_restoration_handler(
      const Pistache::Rest::Request& request,
      Pistache::Http::ResponseWriter response);
  void pcscf_restoration_indication_api_default_handler(
      const Pistache::Rest::Request& request,
      Pistache::Http::ResponseWriter response);

  /// <summary>
  /// Helper function to handle unexpected Exceptions during Parameter parsing
  /// and validation. May be overridden to return custom error formats. This is
  /// called inside a catch block. Important: When overriding, do not call
  /// `throw ex;`, but instead use `throw;`.
  /// </summary>
  virtual std::pair<Pistache::Http::Code, std::string> handleParsingException(
      const std::exception& ex) const noexcept;

  /// <summary>
  /// Helper function to handle unexpected Exceptions during processing of the
  /// request in handler functions. May be overridden to return custom error
  /// formats. This is called inside a catch block. Important: When overriding,
  /// do not call `throw ex;`, but instead use `throw;`.
  /// </summary>
  virtual std::pair<Pistache::Http::Code, std::string> handleOperationException(
      const std::exception& ex) const noexcept;

  /// <summary>
  /// Indicates P-CSCF restoration and does not create an Individual Application
  /// Session Context
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  /// <param name="pcscfRestorationRequestData">PCSCF Restoration
  /// Indication.</param>
  virtual void pcscf_restoration(
      const oai::model::pcf::PcscfRestorationRequestData&
          pcscfRestorationRequestData,
      Pistache::Http::ResponseWriter& response) = 0;
};

}  // namespace oai::pcf::api

#endif /* PCSCFRestorationIndicationApi_H_ */
