/**
 * Npcf_PolicyAuthorization Service API
 * PCF Policy Authorization Service.   © 2024, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.3.0-alpha.6
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "PCSCFRestorationIndicationApi.h"
#include "Helpers.h"
#include "api_defs.h"

namespace oai::pcf::api {

using namespace oai::model::common::helpers;
using namespace oai::model::pcf;

PCSCFRestorationIndicationApi::PCSCFRestorationIndicationApi(
    const std::shared_ptr<Pistache::Rest::Router>& rtr)
    : ApiBase(rtr) {}

void PCSCFRestorationIndicationApi::init() {
  setupRoutes();
}

void PCSCFRestorationIndicationApi::setupRoutes() {
  using namespace Pistache::Rest;

  Routes::Post(
      *router, app_sessions::get_route() + "/pcscf-restoration",
      Routes::bind(
          &PCSCFRestorationIndicationApi::pcscf_restoration_handler, this));

  // Default handler, called when a route is not found
  router->addCustomHandler(Routes::bind(
      &PCSCFRestorationIndicationApi::
          pcscf_restoration_indication_api_default_handler,
      this));
}

std::pair<Pistache::Http::Code, std::string>
PCSCFRestorationIndicationApi::handleParsingException(
    const std::exception& ex) const noexcept {
  try {
    throw;
  } catch (nlohmann::detail::exception& e) {
    return std::make_pair(Pistache::Http::Code::Bad_Request, e.what());
  } catch (oai::model::common::helpers::ValidationException& e) {
    return std::make_pair(Pistache::Http::Code::Bad_Request, e.what());
  } catch (std::exception& e) {
    return std::make_pair(
        Pistache::Http::Code::Internal_Server_Error, e.what());
  }
}

std::pair<Pistache::Http::Code, std::string>
PCSCFRestorationIndicationApi::handleOperationException(
    const std::exception& ex) const noexcept {
  return std::make_pair(Pistache::Http::Code::Internal_Server_Error, ex.what());
}

void PCSCFRestorationIndicationApi::pcscf_restoration_handler(
    const Pistache::Rest::Request& request,
    Pistache::Http::ResponseWriter response) {
  try {
    // Getting the body param

    PcscfRestorationRequestData pcscfRestorationRequestData;

    try {
      nlohmann::json::parse(request.body()).get_to(pcscfRestorationRequestData);
      pcscfRestorationRequestData.validate();
    } catch (std::exception& e) {
      const std::pair<Pistache::Http::Code, std::string> errorInfo =
          this->handleParsingException(e);
      response.send(errorInfo.first, errorInfo.second);
      return;
    }

    try {
      this->pcscf_restoration(pcscfRestorationRequestData, response);
    } catch (Pistache::Http::HttpError& e) {
      response.send(static_cast<Pistache::Http::Code>(e.code()), e.what());
      return;
    } catch (std::exception& e) {
      const std::pair<Pistache::Http::Code, std::string> errorInfo =
          this->handleOperationException(e);
      response.send(errorInfo.first, errorInfo.second);
      return;
    }

  } catch (std::exception& e) {
    response.send(Pistache::Http::Code::Internal_Server_Error, e.what());
  }
}

void PCSCFRestorationIndicationApi::
    pcscf_restoration_indication_api_default_handler(
        const Pistache::Rest::Request&,
        Pistache::Http::ResponseWriter response) {
  response.send(
      Pistache::Http::Code::Not_Found, "The requested method does not exist");
}

}  // namespace oai::pcf::api
