/**
* Npcf_SMPolicyControl API
* Session Management Policy Control Service © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
*
* The version of the OpenAPI document: 1.1.1.alpha-5
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * SubscribedDefaultQos.h
 *
 * 
 */

#ifndef SubscribedDefaultQos_H_
#define SubscribedDefaultQos_H_


#include "Arp.h"
#include <nlohmann/json.hpp>

namespace oai {
namespace pcf {
namespace model {

/// <summary>
/// 
/// </summary>
class  SubscribedDefaultQos
{
public:
    SubscribedDefaultQos();
    virtual ~SubscribedDefaultQos() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const SubscribedDefaultQos& rhs) const;
    bool operator!=(const SubscribedDefaultQos& rhs) const;

    /////////////////////////////////////////////
    /// SubscribedDefaultQos members

    /// <summary>
    /// 
    /// </summary>
    int32_t getR5qi() const;
    void setR5qi(int32_t const value);
    /// <summary>
    /// 
    /// </summary>
    Arp getArp() const;
    void setArp(Arp const& value);
    /// <summary>
    /// 
    /// </summary>
    int32_t getPriorityLevel() const;
    void setPriorityLevel(int32_t const value);
    bool priorityLevelIsSet() const;
    void unsetPriorityLevel();

    friend void to_json(nlohmann::json& j, const SubscribedDefaultQos& o);
    friend void from_json(const nlohmann::json& j, SubscribedDefaultQos& o);
protected:
    int32_t m_r_5qi;

    Arp m_Arp;

    int32_t m_PriorityLevel;
    bool m_PriorityLevelIsSet;
    
};

}  // namespace model
}  // namespace pcf
}  // namespace oai
#endif /* SubscribedDefaultQos_H_ */
