/**
 * PCC, QoS, and Traffic Control Data API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * DefaultPolicyDecisionsApi.h
 *
 *
 */

#ifndef DefaultPolicyDecisionsApi_H_
#define DefaultPolicyDecisionsApi_H_

#include <pistache/http.h>
#include <pistache/router.h>
#include <pistache/http_headers.h>
#include <nlohmann/json.hpp>
#include <optional>
#include <utility>

#include <string>
#include <vector>

namespace oai::pcf::provisioning::api {

class DefaultPolicyDecisionsApi {
 public:
  explicit DefaultPolicyDecisionsApi(
      const std::shared_ptr<Pistache::Rest::Router>& rtr);
  virtual ~DefaultPolicyDecisionsApi() = default;
  void init();

  static const std::string base;

 private:
  void setupRoutes();

  void default_decision_get_handler(
      const Pistache::Rest::Request& request,
      Pistache::Http::ResponseWriter response);
  void default_decision_put_handler(
      const Pistache::Rest::Request& request,
      Pistache::Http::ResponseWriter response);
  void default_policy_decisions_api_default_handler(
      const Pistache::Rest::Request& request,
      Pistache::Http::ResponseWriter response);

  const std::shared_ptr<Pistache::Rest::Router> router;

  /// <summary>
  /// Helper function to handle unexpected Exceptions during Parameter parsing
  /// and validation. May be overridden to return custom error formats. This is
  /// called inside a catch block. Important: When overriding, do not call
  /// `throw ex;`, but instead use `throw;`.
  /// </summary>
  virtual std::pair<Pistache::Http::Code, std::string> handleParsingException(
      const std::exception& ex) const noexcept;

  /// <summary>
  /// Helper function to handle unexpected Exceptions during processing of the
  /// request in handler functions. May be overridden to return custom error
  /// formats. This is called inside a catch block. Important: When overriding,
  /// do not call `throw ex;`, but instead use `throw;`.
  /// </summary>
  virtual std::pair<Pistache::Http::Code, std::string> handleOperationException(
      const std::exception& ex) const noexcept;

  /// <summary>
  /// Get the default policy decision
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  virtual void default_decision_get(
      Pistache::Http::ResponseWriter& response) = 0;
  /// <summary>
  /// Update the default policy decision
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  /// <param name="stdString">Default policy decision to update</param>
  virtual void default_decision_put(
      const std::vector<std::string>& stdString,
      Pistache::Http::ResponseWriter& response) = 0;
};

}  // namespace oai::pcf::provisioning::api

#endif /* DefaultPolicyDecisionsApi_H_ */
