/**
 * PCC, QoS, and Traffic Control Data API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "DefaultPolicyDecisionsApi.h"
#include "api_defs.h"
#include "Helpers.h"
#include "pcf_config.hpp"

namespace oai::pcf::provisioning::api {

DefaultPolicyDecisionsApi::DefaultPolicyDecisionsApi(
    const std::shared_ptr<Pistache::Rest::Router>& rtr)
    : router(rtr) {}

void DefaultPolicyDecisionsApi::init() {
  setupRoutes();
}

void DefaultPolicyDecisionsApi::setupRoutes() {
  using namespace Pistache::Rest;

  Routes::Get(
      *router,
      oai::pcf::api::policy_decision_provisioning::get_provisioning_base() +
          "/defaultDecision",
      Routes::bind(
          &DefaultPolicyDecisionsApi::default_decision_get_handler, this));
  Routes::Put(
      *router,
      oai::pcf::api::policy_decision_provisioning::get_provisioning_base() +
          "/defaultDecision",
      Routes::bind(
          &DefaultPolicyDecisionsApi::default_decision_put_handler, this));

  // Default handler, called when a route is not found
  router->addCustomHandler(Routes::bind(
      &DefaultPolicyDecisionsApi::default_policy_decisions_api_default_handler,
      this));
}

std::pair<Pistache::Http::Code, std::string>
DefaultPolicyDecisionsApi::handleParsingException(
    const std::exception& ex) const noexcept {
  try {
    throw;
  } catch (nlohmann::detail::exception& e) {
    return std::make_pair(Pistache::Http::Code::Bad_Request, e.what());
  } catch (oai::model::common::helpers::ValidationException& e) {
    return std::make_pair(Pistache::Http::Code::Bad_Request, e.what());
  } catch (std::exception& e) {
    return std::make_pair(
        Pistache::Http::Code::Internal_Server_Error, e.what());
  }
}

std::pair<Pistache::Http::Code, std::string>
DefaultPolicyDecisionsApi::handleOperationException(
    const std::exception& ex) const noexcept {
  return std::make_pair(Pistache::Http::Code::Internal_Server_Error, ex.what());
}

void DefaultPolicyDecisionsApi::default_decision_get_handler(
    const Pistache::Rest::Request&, Pistache::Http::ResponseWriter response) {
  try {
    try {
      this->default_decision_get(response);
    } catch (Pistache::Http::HttpError& e) {
      response.send(static_cast<Pistache::Http::Code>(e.code()), e.what());
      return;
    } catch (std::exception& e) {
      const std::pair<Pistache::Http::Code, std::string> errorInfo =
          this->handleOperationException(e);
      response.send(errorInfo.first, errorInfo.second);
      return;
    }

  } catch (std::exception& e) {
    response.send(Pistache::Http::Code::Internal_Server_Error, e.what());
  }
}
void DefaultPolicyDecisionsApi::default_decision_put_handler(
    const Pistache::Rest::Request& request,
    Pistache::Http::ResponseWriter response) {
  try {
    // Getting the body param
    std::vector<std::string> stdString;

    try {
      nlohmann::json::parse(request.body()).get_to(stdString);
    } catch (std::exception& e) {
      const std::pair<Pistache::Http::Code, std::string> errorInfo =
          this->handleParsingException(e);
      response.send(errorInfo.first, errorInfo.second);
      return;
    }

    try {
      this->default_decision_put(stdString, response);
    } catch (Pistache::Http::HttpError& e) {
      response.send(static_cast<Pistache::Http::Code>(e.code()), e.what());
      return;
    } catch (std::exception& e) {
      const std::pair<Pistache::Http::Code, std::string> errorInfo =
          this->handleOperationException(e);
      response.send(errorInfo.first, errorInfo.second);
      return;
    }

  } catch (std::exception& e) {
    response.send(Pistache::Http::Code::Internal_Server_Error, e.what());
  }
}

void DefaultPolicyDecisionsApi::default_policy_decisions_api_default_handler(
    const Pistache::Rest::Request&, Pistache::Http::ResponseWriter response) {
  response.send(
      Pistache::Http::Code::Not_Found, "The requested method does not exist");
}

}  // namespace oai::pcf::provisioning::api
