/**
 * PCC, QoS, and Traffic Control Data API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * DNNPolicyDecisionsApi.h
 *
 *
 */

#ifndef DNNPolicyDecisionsApi_H_
#define DNNPolicyDecisionsApi_H_

#include <pistache/http.h>
#include <pistache/router.h>
#include <pistache/http_headers.h>

#include <optional>
#include <utility>

#include "../model/DnnPolicyDecision.h"
#include <string>

namespace oai::pcf::provisioning::api {

class DNNPolicyDecisionsApi {
 public:
  explicit DNNPolicyDecisionsApi(
      const std::shared_ptr<Pistache::Rest::Router>& rtr);
  virtual ~DNNPolicyDecisionsApi() = default;
  void init();

  static const std::string base;

 private:
  void setupRoutes();

  void dnn_policy_decision_dnn_delete_handler(
      const Pistache::Rest::Request& request,
      Pistache::Http::ResponseWriter response);
  void dnn_policy_decision_dnn_get_handler(
      const Pistache::Rest::Request& request,
      Pistache::Http::ResponseWriter response);
  void dnn_policy_decision_dnn_put_handler(
      const Pistache::Rest::Request& request,
      Pistache::Http::ResponseWriter response);
  void dnn_policy_decision_post_handler(
      const Pistache::Rest::Request& request,
      Pistache::Http::ResponseWriter response);
  void dnn_policy_decisions_get_handler(
      const Pistache::Rest::Request& request,
      Pistache::Http::ResponseWriter response);
  void dnn_policy_decisions_api_default_handler(
      const Pistache::Rest::Request& request,
      Pistache::Http::ResponseWriter response);

  const std::shared_ptr<Pistache::Rest::Router> router;

  /// <summary>
  /// Helper function to handle unexpected Exceptions during Parameter parsing
  /// and validation. May be overridden to return custom error formats. This is
  /// called inside a catch block. Important: When overriding, do not call
  /// `throw ex;`, but instead use `throw;`.
  /// </summary>
  virtual std::pair<Pistache::Http::Code, std::string> handleParsingException(
      const std::exception& ex) const noexcept;

  /// <summary>
  /// Helper function to handle unexpected Exceptions during processing of the
  /// request in handler functions. May be overridden to return custom error
  /// formats. This is called inside a catch block. Important: When overriding,
  /// do not call `throw ex;`, but instead use `throw;`.
  /// </summary>
  virtual std::pair<Pistache::Http::Code, std::string> handleOperationException(
      const std::exception& ex) const noexcept;

  /// <summary>
  /// Delete a DNN policy decision by DNN
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  /// <param name="dnn"></param>
  virtual void dnn_policy_decision_dnn_delete(
      const std::string& dnn, Pistache::Http::ResponseWriter& response) = 0;
  /// <summary>
  /// Get a DNN policy decision by DNN
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  /// <param name="dnn"></param>
  virtual void dnn_policy_decision_dnn_get(
      const std::string& dnn, Pistache::Http::ResponseWriter& response) = 0;
  /// <summary>
  /// Update a DNN policy decision by DNN
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  /// <param name="dnn"></param>
  /// <param name="dnnPolicyDecision">DNN policy decision to update</param>
  virtual void dnn_policy_decision_dnn_put(
      const std::string& dnn,
      const oai::pcf::provisioning::model::DnnPolicyDecision& dnnPolicyDecision,
      Pistache::Http::ResponseWriter& response) = 0;
  /// <summary>
  /// Create a new DNN policy decision
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  /// <param name="dnnPolicyDecision">DNN policy decision to create</param>
  virtual void dnn_policy_decision_post(
      const oai::pcf::provisioning::model::DnnPolicyDecision& dnnPolicyDecision,
      Pistache::Http::ResponseWriter& response) = 0;
  /// <summary>
  /// List all DNN policy decisions
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  virtual void dnn_policy_decisions_get(
      Pistache::Http::ResponseWriter& response) = 0;
};

}  // namespace oai::pcf::provisioning::api

#endif /* DNNPolicyDecisionsApi_H_ */
