/**
 * PCC, QoS, and Traffic Control Data API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * PCCRulesApi.h
 *
 *
 */

#ifndef PCCRulesApi_H_
#define PCCRulesApi_H_

#include <pistache/http.h>
#include <pistache/router.h>
#include <pistache/http_headers.h>

#include <optional>
#include <utility>

#include "PccRule.h"
#include <string>

namespace oai::pcf::provisioning::api {

class PCCRulesApi {
 public:
  explicit PCCRulesApi(const std::shared_ptr<Pistache::Rest::Router>& rtr);
  virtual ~PCCRulesApi() = default;
  void init();

  static const std::string base;

 private:
  void setupRoutes();

  void pcc_rule_pcc_rule_id_delete_handler(
      const Pistache::Rest::Request& request,
      Pistache::Http::ResponseWriter response);
  void pcc_rule_pcc_rule_id_get_handler(
      const Pistache::Rest::Request& request,
      Pistache::Http::ResponseWriter response);
  void pcc_rule_pcc_rule_id_put_handler(
      const Pistache::Rest::Request& request,
      Pistache::Http::ResponseWriter response);
  void pcc_rule_post_handler(
      const Pistache::Rest::Request& request,
      Pistache::Http::ResponseWriter response);
  void pcc_rules_get_handler(
      const Pistache::Rest::Request& request,
      Pistache::Http::ResponseWriter response);
  void pcc_rules_api_default_handler(
      const Pistache::Rest::Request& request,
      Pistache::Http::ResponseWriter response);

  const std::shared_ptr<Pistache::Rest::Router> router;

  /// <summary>
  /// Helper function to handle unexpected Exceptions during Parameter parsing
  /// and validation. May be overridden to return custom error formats. This is
  /// called inside a catch block. Important: When overriding, do not call
  /// `throw ex;`, but instead use `throw;`.
  /// </summary>
  virtual std::pair<Pistache::Http::Code, std::string> handleParsingException(
      const std::exception& ex) const noexcept;

  /// <summary>
  /// Helper function to handle unexpected Exceptions during processing of the
  /// request in handler functions. May be overridden to return custom error
  /// formats. This is called inside a catch block. Important: When overriding,
  /// do not call `throw ex;`, but instead use `throw;`.
  /// </summary>
  virtual std::pair<Pistache::Http::Code, std::string> handleOperationException(
      const std::exception& ex) const noexcept;

  /// <summary>
  /// Delete a PCC rule by ID
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  /// <param name="pccRuleId"></param>
  virtual void pcc_rule_pcc_rule_id_delete(
      const std::string& pccRuleId,
      Pistache::Http::ResponseWriter& response) = 0;
  /// <summary>
  /// Get a PCC rule by ID
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  /// <param name="pccRuleId"></param>
  virtual void pcc_rule_pcc_rule_id_get(
      const std::string& pccRuleId,
      Pistache::Http::ResponseWriter& response) = 0;
  /// <summary>
  /// Update a PCC rule by ID
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  /// <param name="pccRuleId"></param>
  /// <param name="pccRule">PCC rule to update</param>
  virtual void pcc_rule_pcc_rule_id_put(
      const std::string& pccRuleId, const oai::model::pcf::PccRule& pccRule,
      Pistache::Http::ResponseWriter& response) = 0;
  /// <summary>
  /// Create a new PCC rule
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  /// <param name="pccRule">PCC rule to create</param>
  virtual void pcc_rule_post(
      const oai::model::pcf::PccRule& pccRule,
      Pistache::Http::ResponseWriter& response) = 0;
  /// <summary>
  /// List all PCC rules
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  virtual void pcc_rules_get(Pistache::Http::ResponseWriter& response) = 0;
};

}  // namespace oai::pcf::provisioning::api

#endif /* PCCRulesApi_H_ */
