/**
 * PCC, QoS, and Traffic Control Data API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * QOSRulesApi.h
 *
 *
 */

#ifndef QOSRulesApi_H_
#define QOSRulesApi_H_

#include <pistache/http.h>
#include <pistache/router.h>
#include <pistache/http_headers.h>

#include <optional>
#include <utility>

#include "QosData.h"
#include <string>

namespace oai::pcf::provisioning::api {

class QOSDataApi {
 public:
  explicit QOSDataApi(const std::shared_ptr<Pistache::Rest::Router>& rtr);
  virtual ~QOSDataApi() = default;
  void init();

  static const std::string base;

 private:
  void setupRoutes();

  void qos_data_get_handler(
      const Pistache::Rest::Request& request,
      Pistache::Http::ResponseWriter response);
  void qos_data_post_handler(
      const Pistache::Rest::Request& request,
      Pistache::Http::ResponseWriter response);
  void qos_data_qos_id_delete_handler(
      const Pistache::Rest::Request& request,
      Pistache::Http::ResponseWriter response);
  void qos_data_qos_id_get_handler(
      const Pistache::Rest::Request& request,
      Pistache::Http::ResponseWriter response);
  void qos_data_qos_id_put_handler(
      const Pistache::Rest::Request& request,
      Pistache::Http::ResponseWriter response);
  void qos_rules_api_default_handler(
      const Pistache::Rest::Request& request,
      Pistache::Http::ResponseWriter response);

  const std::shared_ptr<Pistache::Rest::Router> router;

  /// <summary>
  /// Helper function to handle unexpected Exceptions during Parameter parsing
  /// and validation. May be overridden to return custom error formats. This is
  /// called inside a catch block. Important: When overriding, do not call
  /// `throw ex;`, but instead use `throw;`.
  /// </summary>
  virtual std::pair<Pistache::Http::Code, std::string> handleParsingException(
      const std::exception& ex) const noexcept;

  /// <summary>
  /// Helper function to handle unexpected Exceptions during processing of the
  /// request in handler functions. May be overridden to return custom error
  /// formats. This is called inside a catch block. Important: When overriding,
  /// do not call `throw ex;`, but instead use `throw;`.
  /// </summary>
  virtual std::pair<Pistache::Http::Code, std::string> handleOperationException(
      const std::exception& ex) const noexcept;

  /// <summary>
  /// List all QoS data
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  virtual void qos_data_get(Pistache::Http::ResponseWriter& response) = 0;
  /// <summary>
  /// Create a new QoS data entry
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  /// <param name="qosData">QoS data to create</param>
  virtual void qos_data_post(
      const oai::model::pcf::QosData& qosData,
      Pistache::Http::ResponseWriter& response) = 0;
  /// <summary>
  /// Delete QoS data by ID
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  /// <param name="qosId"></param>
  virtual void qos_data_qos_id_delete(
      const std::string& qosId, Pistache::Http::ResponseWriter& response) = 0;
  /// <summary>
  /// Get QoS data by ID
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  /// <param name="qosId"></param>
  virtual void qos_data_qos_id_get(
      const std::string& qosId, Pistache::Http::ResponseWriter& response) = 0;
  /// <summary>
  /// Update QoS data by ID
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  /// <param name="qosId"></param>
  /// <param name="qosData">QoS data to update</param>
  virtual void qos_data_qos_id_put(
      const std::string& qosId, const oai::model::pcf::QosData& qosData,
      Pistache::Http::ResponseWriter& response) = 0;
};

}  // namespace oai::pcf::provisioning::api

#endif /* QOSRulesApi_H_ */
