/**
 * PCC, QoS, and Traffic Control Data API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include <Snssai.h>
#include "SlicePolicyDecisionsApi.h"
#include "Helpers.h"
#include "api_defs.h"
#include "pcf_config.hpp"

namespace oai::pcf::provisioning::api {

using namespace oai::model::common::helpers;
using namespace oai::pcf::provisioning::model;
using namespace oai::pcf::api;

SlicePolicyDecisionsApi::SlicePolicyDecisionsApi(
    const std::shared_ptr<Pistache::Rest::Router>& rtr)
    : router(rtr) {}

void SlicePolicyDecisionsApi::init() {
  setupRoutes();
}

void SlicePolicyDecisionsApi::setupRoutes() {
  using namespace Pistache::Rest;

  Routes::Delete(
      *router,
      policy_decision_provisioning::get_provisioning_base() +
          "/slicePolicyDecision",
      Routes::bind(
          &SlicePolicyDecisionsApi::slice_policy_decision_delete_handler,
          this));
  Routes::Get(
      *router,
      policy_decision_provisioning::get_provisioning_base() +
          "/slicePolicyDecision",
      Routes::bind(
          &SlicePolicyDecisionsApi::slice_policy_decision_get_handler, this));
  Routes::Post(
      *router,
      policy_decision_provisioning::get_provisioning_base() +
          "/slicePolicyDecision",
      Routes::bind(
          &SlicePolicyDecisionsApi::slice_policy_decision_post_handler, this));
  Routes::Put(
      *router,
      policy_decision_provisioning::get_provisioning_base() +
          "/slicePolicyDecision",
      Routes::bind(
          &SlicePolicyDecisionsApi::slice_policy_decision_put_handler, this));
  Routes::Get(
      *router,
      policy_decision_provisioning::get_provisioning_base() +
          "/slicePolicyDecisions",
      Routes::bind(
          &SlicePolicyDecisionsApi::slice_policy_decisions_get_handler, this));

  // Default handler, called when a route is not found
  router->addCustomHandler(Routes::bind(
      &SlicePolicyDecisionsApi::slice_policy_decisions_api_default_handler,
      this));
}

std::pair<Pistache::Http::Code, std::string>
SlicePolicyDecisionsApi::handleParsingException(
    const std::exception& ex) const noexcept {
  try {
    throw;
  } catch (nlohmann::detail::exception& e) {
    return std::make_pair(Pistache::Http::Code::Bad_Request, e.what());
  } catch (oai::model::common::helpers::ValidationException& e) {
    return std::make_pair(Pistache::Http::Code::Bad_Request, e.what());
  } catch (std::exception& e) {
    return std::make_pair(
        Pistache::Http::Code::Internal_Server_Error, e.what());
  }
}

std::pair<Pistache::Http::Code, std::string>
SlicePolicyDecisionsApi::handleOperationException(
    const std::exception& ex) const noexcept {
  return std::make_pair(Pistache::Http::Code::Internal_Server_Error, ex.what());
}

void SlicePolicyDecisionsApi::slice_policy_decision_delete_handler(
    const Pistache::Rest::Request& request,
    Pistache::Http::ResponseWriter response) {
  try {
    // Getting the query params
    auto sstQuery = request.query().get("sst");
    std::optional<int32_t> sst;
    if (!sstQuery.isEmpty()) {
      int32_t valueQuery_instance;
      if (fromStringValue(sstQuery.get(), valueQuery_instance)) {
        sst = valueQuery_instance;
      }
    } else {
      response.send(
          Pistache::Http::Code::Bad_Request, "Missing 'sst' parameter");
    }
    auto sdQuery = request.query().get("sd");
    std::optional<std::string> sd;
    if (!sdQuery.isEmpty()) {
      std::string valueQuery_instance;
      if (fromStringValue(sdQuery.get(), valueQuery_instance)) {
        sd = valueQuery_instance;
      }
    } else {
      sd = oai::model::common::SD_DEFAULT_VALUE;
    }

    try {
      this->slice_policy_decision_delete(sst, sd, response);
    } catch (Pistache::Http::HttpError& e) {
      response.send(static_cast<Pistache::Http::Code>(e.code()), e.what());
      return;
    } catch (std::exception& e) {
      const std::pair<Pistache::Http::Code, std::string> errorInfo =
          this->handleOperationException(e);
      response.send(errorInfo.first, errorInfo.second);
      return;
    }

  } catch (std::exception& e) {
    response.send(Pistache::Http::Code::Internal_Server_Error, e.what());
  }
}
void SlicePolicyDecisionsApi::slice_policy_decision_get_handler(
    const Pistache::Rest::Request& request,
    Pistache::Http::ResponseWriter response) {
  try {
    // Getting the query params
    auto sstQuery = request.query().get("sst");
    std::optional<int32_t> sst;
    if (!sstQuery.isEmpty()) {
      int32_t valueQuery_instance;
      if (fromStringValue(sstQuery.get(), valueQuery_instance)) {
        sst = valueQuery_instance;
      }
    } else {
      response.send(
          Pistache::Http::Code::Bad_Request, "Missing 'sst' parameter");
    }
    auto sdQuery = request.query().get("sd");
    std::optional<std::string> sd;
    if (!sdQuery.isEmpty()) {
      std::string valueQuery_instance;
      if (fromStringValue(sdQuery.get(), valueQuery_instance)) {
        sd = valueQuery_instance;
      }
    } else {
      sd = oai::model::common::SD_DEFAULT_VALUE;
    }

    try {
      this->slice_policy_decision_get(sst, sd, response);
    } catch (Pistache::Http::HttpError& e) {
      response.send(static_cast<Pistache::Http::Code>(e.code()), e.what());
      return;
    } catch (std::exception& e) {
      const std::pair<Pistache::Http::Code, std::string> errorInfo =
          this->handleOperationException(e);
      response.send(errorInfo.first, errorInfo.second);
      return;
    }

  } catch (std::exception& e) {
    response.send(Pistache::Http::Code::Internal_Server_Error, e.what());
  }
}
void SlicePolicyDecisionsApi::slice_policy_decision_post_handler(
    const Pistache::Rest::Request& request,
    Pistache::Http::ResponseWriter response) {
  try {
    // Getting the body param

    SlicePolicyDecision slicePolicyDecision;

    try {
      nlohmann::json::parse(request.body()).get_to(slicePolicyDecision);
      slicePolicyDecision.validate();
    } catch (std::exception& e) {
      const std::pair<Pistache::Http::Code, std::string> errorInfo =
          this->handleParsingException(e);
      response.send(errorInfo.first, errorInfo.second);
      return;
    }

    try {
      this->slice_policy_decision_post(slicePolicyDecision, response);
    } catch (Pistache::Http::HttpError& e) {
      response.send(static_cast<Pistache::Http::Code>(e.code()), e.what());
      return;
    } catch (std::exception& e) {
      const std::pair<Pistache::Http::Code, std::string> errorInfo =
          this->handleOperationException(e);
      response.send(errorInfo.first, errorInfo.second);
      return;
    }

  } catch (std::exception& e) {
    response.send(Pistache::Http::Code::Internal_Server_Error, e.what());
  }
}
void SlicePolicyDecisionsApi::slice_policy_decision_put_handler(
    const Pistache::Rest::Request& request,
    Pistache::Http::ResponseWriter response) {
  try {
    // Getting the body param

    SlicePolicyDecision slicePolicyDecision;

    // Getting the query params
    auto sstQuery = request.query().get("sst");
    std::optional<int32_t> sst;
    if (!sstQuery.isEmpty()) {
      int32_t valueQuery_instance;
      if (fromStringValue(sstQuery.get(), valueQuery_instance)) {
        sst = valueQuery_instance;
      }
    } else {
      response.send(
          Pistache::Http::Code::Bad_Request, "Missing 'sst' parameter");
    }
    auto sdQuery = request.query().get("sd");
    std::optional<std::string> sd;
    if (!sdQuery.isEmpty()) {
      std::string valueQuery_instance;
      if (fromStringValue(sdQuery.get(), valueQuery_instance)) {
        sd = valueQuery_instance;
      }
    } else {
      sd = oai::model::common::SD_DEFAULT_VALUE;
    }

    try {
      nlohmann::json::parse(request.body()).get_to(slicePolicyDecision);
      slicePolicyDecision.validate();
    } catch (std::exception& e) {
      const std::pair<Pistache::Http::Code, std::string> errorInfo =
          this->handleParsingException(e);
      response.send(errorInfo.first, errorInfo.second);
      return;
    }

    try {
      this->slice_policy_decision_put(sst, sd, slicePolicyDecision, response);
    } catch (Pistache::Http::HttpError& e) {
      response.send(static_cast<Pistache::Http::Code>(e.code()), e.what());
      return;
    } catch (std::exception& e) {
      const std::pair<Pistache::Http::Code, std::string> errorInfo =
          this->handleOperationException(e);
      response.send(errorInfo.first, errorInfo.second);
      return;
    }

  } catch (std::exception& e) {
    response.send(Pistache::Http::Code::Internal_Server_Error, e.what());
  }
}
void SlicePolicyDecisionsApi::slice_policy_decisions_get_handler(
    const Pistache::Rest::Request&, Pistache::Http::ResponseWriter response) {
  try {
    try {
      this->slice_policy_decisions_get(response);
    } catch (Pistache::Http::HttpError& e) {
      response.send(static_cast<Pistache::Http::Code>(e.code()), e.what());
      return;
    } catch (std::exception& e) {
      const std::pair<Pistache::Http::Code, std::string> errorInfo =
          this->handleOperationException(e);
      response.send(errorInfo.first, errorInfo.second);
      return;
    }

  } catch (std::exception& e) {
    response.send(Pistache::Http::Code::Internal_Server_Error, e.what());
  }
}

void SlicePolicyDecisionsApi::slice_policy_decisions_api_default_handler(
    const Pistache::Rest::Request&, Pistache::Http::ResponseWriter response) {
  response.send(
      Pistache::Http::Code::Not_Found, "The requested method does not exist");
}

}  // namespace oai::pcf::provisioning::api
