/**
 * PCC, QoS, and Traffic Control Data API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "SupiPolicyDecisionsApi.h"
#include "Helpers.h"
#include "api_defs.h"
#include "pcf_config.hpp"

namespace oai::pcf::provisioning::api {

using namespace oai::model::common::helpers;
using namespace oai::pcf::provisioning::model;
using namespace oai::pcf::api;

SupiPolicyDecisionsApi::SupiPolicyDecisionsApi(
    const std::shared_ptr<Pistache::Rest::Router>& rtr)
    : router(rtr) {}

void SupiPolicyDecisionsApi::init() {
  setupRoutes();
}

void SupiPolicyDecisionsApi::setupRoutes() {
  using namespace Pistache::Rest;

  Routes::Post(
      *router,
      policy_decision_provisioning::get_provisioning_base() +
          "/supiPolicyDecision",
      Routes::bind(
          &SupiPolicyDecisionsApi::supi_policy_decision_post_handler, this));
  Routes::Delete(
      *router,
      policy_decision_provisioning::get_provisioning_base() +
          "/supiPolicyDecision/:supi",
      Routes::bind(
          &SupiPolicyDecisionsApi::supi_policy_decision_supi_delete_handler,
          this));
  Routes::Get(
      *router,
      policy_decision_provisioning::get_provisioning_base() +
          "/supiPolicyDecision/:supi",
      Routes::bind(
          &SupiPolicyDecisionsApi::supi_policy_decision_supi_get_handler,
          this));
  Routes::Put(
      *router,
      policy_decision_provisioning::get_provisioning_base() +
          "/supiPolicyDecision/:supi",
      Routes::bind(
          &SupiPolicyDecisionsApi::supi_policy_decision_supi_put_handler,
          this));
  Routes::Get(
      *router,
      policy_decision_provisioning::get_provisioning_base() +
          "/supiPolicyDecisions",
      Routes::bind(
          &SupiPolicyDecisionsApi::supi_policy_decisions_get_handler, this));

  // Default handler, called when a route is not found
  router->addCustomHandler(Routes::bind(
      &SupiPolicyDecisionsApi::supi_policy_decisions_api_default_handler,
      this));
}

std::pair<Pistache::Http::Code, std::string>
SupiPolicyDecisionsApi::handleParsingException(
    const std::exception& ex) const noexcept {
  try {
    throw;
  } catch (nlohmann::detail::exception& e) {
    return std::make_pair(Pistache::Http::Code::Bad_Request, e.what());
  } catch (oai::model::common::helpers::ValidationException& e) {
    return std::make_pair(Pistache::Http::Code::Bad_Request, e.what());
  } catch (std::exception& e) {
    return std::make_pair(
        Pistache::Http::Code::Internal_Server_Error, e.what());
  }
}

std::pair<Pistache::Http::Code, std::string>
SupiPolicyDecisionsApi::handleOperationException(
    const std::exception& ex) const noexcept {
  return std::make_pair(Pistache::Http::Code::Internal_Server_Error, ex.what());
}

void SupiPolicyDecisionsApi::supi_policy_decision_post_handler(
    const Pistache::Rest::Request& request,
    Pistache::Http::ResponseWriter response) {
  try {
    // Getting the body param

    SupiPolicyDecision supiPolicyDecision;

    try {
      nlohmann::json::parse(request.body()).get_to(supiPolicyDecision);
      supiPolicyDecision.validate();
    } catch (std::exception& e) {
      const std::pair<Pistache::Http::Code, std::string> errorInfo =
          this->handleParsingException(e);
      response.send(errorInfo.first, errorInfo.second);
      return;
    }

    try {
      this->supi_policy_decision_post(supiPolicyDecision, response);
    } catch (Pistache::Http::HttpError& e) {
      response.send(static_cast<Pistache::Http::Code>(e.code()), e.what());
      return;
    } catch (std::exception& e) {
      const std::pair<Pistache::Http::Code, std::string> errorInfo =
          this->handleOperationException(e);
      response.send(errorInfo.first, errorInfo.second);
      return;
    }

  } catch (std::exception& e) {
    response.send(Pistache::Http::Code::Internal_Server_Error, e.what());
  }
}
void SupiPolicyDecisionsApi::supi_policy_decision_supi_delete_handler(
    const Pistache::Rest::Request& request,
    Pistache::Http::ResponseWriter response) {
  try {
    // Getting the path params
    auto supi = request.param(":supi").as<std::string>();

    try {
      this->supi_policy_decision_supi_delete(supi, response);
    } catch (Pistache::Http::HttpError& e) {
      response.send(static_cast<Pistache::Http::Code>(e.code()), e.what());
      return;
    } catch (std::exception& e) {
      const std::pair<Pistache::Http::Code, std::string> errorInfo =
          this->handleOperationException(e);
      response.send(errorInfo.first, errorInfo.second);
      return;
    }

  } catch (std::exception& e) {
    response.send(Pistache::Http::Code::Internal_Server_Error, e.what());
  }
}
void SupiPolicyDecisionsApi::supi_policy_decision_supi_get_handler(
    const Pistache::Rest::Request& request,
    Pistache::Http::ResponseWriter response) {
  try {
    // Getting the path params
    auto supi = request.param(":supi").as<std::string>();

    try {
      this->supi_policy_decision_supi_get(supi, response);
    } catch (Pistache::Http::HttpError& e) {
      response.send(static_cast<Pistache::Http::Code>(e.code()), e.what());
      return;
    } catch (std::exception& e) {
      const std::pair<Pistache::Http::Code, std::string> errorInfo =
          this->handleOperationException(e);
      response.send(errorInfo.first, errorInfo.second);
      return;
    }

  } catch (std::exception& e) {
    response.send(Pistache::Http::Code::Internal_Server_Error, e.what());
  }
}
void SupiPolicyDecisionsApi::supi_policy_decision_supi_put_handler(
    const Pistache::Rest::Request& request,
    Pistache::Http::ResponseWriter response) {
  try {
    // Getting the path params
    auto supi = request.param(":supi").as<std::string>();

    // Getting the body param

    SupiPolicyDecision supiPolicyDecision;

    try {
      nlohmann::json::parse(request.body()).get_to(supiPolicyDecision);
      supiPolicyDecision.validate();
    } catch (std::exception& e) {
      const std::pair<Pistache::Http::Code, std::string> errorInfo =
          this->handleParsingException(e);
      response.send(errorInfo.first, errorInfo.second);
      return;
    }

    try {
      this->supi_policy_decision_supi_put(supi, supiPolicyDecision, response);
    } catch (Pistache::Http::HttpError& e) {
      response.send(static_cast<Pistache::Http::Code>(e.code()), e.what());
      return;
    } catch (std::exception& e) {
      const std::pair<Pistache::Http::Code, std::string> errorInfo =
          this->handleOperationException(e);
      response.send(errorInfo.first, errorInfo.second);
      return;
    }

  } catch (std::exception& e) {
    response.send(Pistache::Http::Code::Internal_Server_Error, e.what());
  }
}
void SupiPolicyDecisionsApi::supi_policy_decisions_get_handler(
    const Pistache::Rest::Request&, Pistache::Http::ResponseWriter response) {
  try {
    try {
      this->supi_policy_decisions_get(response);
    } catch (Pistache::Http::HttpError& e) {
      response.send(static_cast<Pistache::Http::Code>(e.code()), e.what());
      return;
    } catch (std::exception& e) {
      const std::pair<Pistache::Http::Code, std::string> errorInfo =
          this->handleOperationException(e);
      response.send(errorInfo.first, errorInfo.second);
      return;
    }

  } catch (std::exception& e) {
    response.send(Pistache::Http::Code::Internal_Server_Error, e.what());
  }
}

void SupiPolicyDecisionsApi::supi_policy_decisions_api_default_handler(
    const Pistache::Rest::Request&, Pistache::Http::ResponseWriter response) {
  response.send(
      Pistache::Http::Code::Not_Found, "The requested method does not exist");
}

}  // namespace oai::pcf::provisioning::api
