/**
 * PCC, QoS, and Traffic Control Data API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * SupiPolicyDecisionsApi.h
 *
 *
 */

#ifndef SupiPolicyDecisionsApi_H_
#define SupiPolicyDecisionsApi_H_

#include <pistache/http.h>
#include <pistache/router.h>
#include <pistache/http_headers.h>

#include <optional>
#include <utility>

#include "../model/SupiPolicyDecision.h"
#include <string>

namespace oai::pcf::provisioning::api {

class SupiPolicyDecisionsApi {
 public:
  explicit SupiPolicyDecisionsApi(
      const std::shared_ptr<Pistache::Rest::Router>& rtr);
  virtual ~SupiPolicyDecisionsApi() = default;
  void init();

  static const std::string base;

 private:
  void setupRoutes();

  void supi_policy_decision_post_handler(
      const Pistache::Rest::Request& request,
      Pistache::Http::ResponseWriter response);
  void supi_policy_decision_supi_delete_handler(
      const Pistache::Rest::Request& request,
      Pistache::Http::ResponseWriter response);
  void supi_policy_decision_supi_get_handler(
      const Pistache::Rest::Request& request,
      Pistache::Http::ResponseWriter response);
  void supi_policy_decision_supi_put_handler(
      const Pistache::Rest::Request& request,
      Pistache::Http::ResponseWriter response);
  void supi_policy_decisions_get_handler(
      const Pistache::Rest::Request& request,
      Pistache::Http::ResponseWriter response);
  void supi_policy_decisions_api_default_handler(
      const Pistache::Rest::Request& request,
      Pistache::Http::ResponseWriter response);

  const std::shared_ptr<Pistache::Rest::Router> router;

  /// <summary>
  /// Helper function to handle unexpected Exceptions during Parameter parsing
  /// and validation. May be overridden to return custom error formats. This is
  /// called inside a catch block. Important: When overriding, do not call
  /// `throw ex;`, but instead use `throw;`.
  /// </summary>
  virtual std::pair<Pistache::Http::Code, std::string> handleParsingException(
      const std::exception& ex) const noexcept;

  /// <summary>
  /// Helper function to handle unexpected Exceptions during processing of the
  /// request in handler functions. May be overridden to return custom error
  /// formats. This is called inside a catch block. Important: When overriding,
  /// do not call `throw ex;`, but instead use `throw;`.
  /// </summary>
  virtual std::pair<Pistache::Http::Code, std::string> handleOperationException(
      const std::exception& ex) const noexcept;

  /// <summary>
  /// Create a new SUPI policy decision
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  /// <param name="supiPolicyDecision">SUPI policy decision to create</param>
  virtual void supi_policy_decision_post(
      const oai::pcf::provisioning::model::SupiPolicyDecision&
          supiPolicyDecision,
      Pistache::Http::ResponseWriter& response) = 0;
  /// <summary>
  /// Delete a SUPI policy decision by SUPI
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  /// <param name="supi"></param>
  virtual void supi_policy_decision_supi_delete(
      const std::string& supi, Pistache::Http::ResponseWriter& response) = 0;
  /// <summary>
  /// Get a SUPI policy decision by SUPI
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  /// <param name="supi"></param>
  virtual void supi_policy_decision_supi_get(
      const std::string& supi, Pistache::Http::ResponseWriter& response) = 0;
  /// <summary>
  /// Update a SUPI policy decision by SUPI
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  /// <param name="supi"></param>
  /// <param name="supiPolicyDecision">SUPI policy decision to update</param>
  virtual void supi_policy_decision_supi_put(
      const std::string& supi,
      const oai::pcf::provisioning::model::SupiPolicyDecision&
          supiPolicyDecision,
      Pistache::Http::ResponseWriter& response) = 0;
  /// <summary>
  /// List all SUPI policy decisions
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  virtual void supi_policy_decisions_get(
      Pistache::Http::ResponseWriter& response) = 0;
};

}  // namespace oai::pcf::provisioning::api

#endif /* SupiPolicyDecisionsApi_H_ */
