/**
 * PCC, QoS, and Traffic Control Data API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "TrafficControlDataApi.h"
#include "Helpers.h"
#include "api_defs.h"
#include "pcf_config.hpp"

namespace oai::pcf::provisioning::api {

using namespace oai::model::common::helpers;
using namespace oai::model::pcf;
using namespace oai::pcf::api;

TrafficControlDataApi::TrafficControlDataApi(
    const std::shared_ptr<Pistache::Rest::Router>& rtr)
    : router(rtr) {}

void TrafficControlDataApi::init() {
  setupRoutes();
}

void TrafficControlDataApi::setupRoutes() {
  using namespace Pistache::Rest;

  Routes::Get(
      *router,
      policy_decision_provisioning::get_provisioning_base() +
          "/trafficControlData",
      Routes::bind(
          &TrafficControlDataApi::traffic_control_data_get_handler, this));
  Routes::Post(
      *router,
      policy_decision_provisioning::get_provisioning_base() +
          "/trafficControlData",
      Routes::bind(
          &TrafficControlDataApi::traffic_control_data_post_handler, this));
  Routes::Delete(
      *router,
      policy_decision_provisioning::get_provisioning_base() +
          "/trafficControlData/:tcId",
      Routes::bind(
          &TrafficControlDataApi::traffic_control_data_tc_id_delete_handler,
          this));
  Routes::Get(
      *router,
      policy_decision_provisioning::get_provisioning_base() +
          "/trafficControlData/:tcId",
      Routes::bind(
          &TrafficControlDataApi::traffic_control_data_tc_id_get_handler,
          this));
  Routes::Put(
      *router,
      policy_decision_provisioning::get_provisioning_base() +
          "/trafficControlData/:tcId",
      Routes::bind(
          &TrafficControlDataApi::traffic_control_data_tc_id_put_handler,
          this));

  // Default handler, called when a route is not found
  router->addCustomHandler(Routes::bind(
      &TrafficControlDataApi::traffic_control_data_api_default_handler, this));
}

std::pair<Pistache::Http::Code, std::string>
TrafficControlDataApi::handleParsingException(
    const std::exception& ex) const noexcept {
  try {
    throw;
  } catch (nlohmann::detail::exception& e) {
    return std::make_pair(Pistache::Http::Code::Bad_Request, e.what());
  } catch (oai::model::common::helpers::ValidationException& e) {
    return std::make_pair(Pistache::Http::Code::Bad_Request, e.what());
  } catch (std::exception& e) {
    return std::make_pair(
        Pistache::Http::Code::Internal_Server_Error, e.what());
  }
}

std::pair<Pistache::Http::Code, std::string>
TrafficControlDataApi::handleOperationException(
    const std::exception& ex) const noexcept {
  return std::make_pair(Pistache::Http::Code::Internal_Server_Error, ex.what());
}

void TrafficControlDataApi::traffic_control_data_get_handler(
    const Pistache::Rest::Request&, Pistache::Http::ResponseWriter response) {
  try {
    try {
      this->traffic_control_data_get(response);
    } catch (Pistache::Http::HttpError& e) {
      response.send(static_cast<Pistache::Http::Code>(e.code()), e.what());
      return;
    } catch (std::exception& e) {
      const std::pair<Pistache::Http::Code, std::string> errorInfo =
          this->handleOperationException(e);
      response.send(errorInfo.first, errorInfo.second);
      return;
    }

  } catch (std::exception& e) {
    response.send(Pistache::Http::Code::Internal_Server_Error, e.what());
  }
}
void TrafficControlDataApi::traffic_control_data_post_handler(
    const Pistache::Rest::Request& request,
    Pistache::Http::ResponseWriter response) {
  try {
    // Getting the body param

    TrafficControlData trafficControlData;

    try {
      nlohmann::json::parse(request.body()).get_to(trafficControlData);
      trafficControlData.validate();
    } catch (std::exception& e) {
      const std::pair<Pistache::Http::Code, std::string> errorInfo =
          this->handleParsingException(e);
      response.send(errorInfo.first, errorInfo.second);
      return;
    }

    try {
      this->traffic_control_data_post(trafficControlData, response);
    } catch (Pistache::Http::HttpError& e) {
      response.send(static_cast<Pistache::Http::Code>(e.code()), e.what());
      return;
    } catch (std::exception& e) {
      const std::pair<Pistache::Http::Code, std::string> errorInfo =
          this->handleOperationException(e);
      response.send(errorInfo.first, errorInfo.second);
      return;
    }

  } catch (std::exception& e) {
    response.send(Pistache::Http::Code::Internal_Server_Error, e.what());
  }
}
void TrafficControlDataApi::traffic_control_data_tc_id_delete_handler(
    const Pistache::Rest::Request& request,
    Pistache::Http::ResponseWriter response) {
  try {
    // Getting the path params
    auto tcId = request.param(":tcId").as<std::string>();

    try {
      this->traffic_control_data_tc_id_delete(tcId, response);
    } catch (Pistache::Http::HttpError& e) {
      response.send(static_cast<Pistache::Http::Code>(e.code()), e.what());
      return;
    } catch (std::exception& e) {
      const std::pair<Pistache::Http::Code, std::string> errorInfo =
          this->handleOperationException(e);
      response.send(errorInfo.first, errorInfo.second);
      return;
    }

  } catch (std::exception& e) {
    response.send(Pistache::Http::Code::Internal_Server_Error, e.what());
  }
}
void TrafficControlDataApi::traffic_control_data_tc_id_get_handler(
    const Pistache::Rest::Request& request,
    Pistache::Http::ResponseWriter response) {
  try {
    // Getting the path params
    auto tcId = request.param(":tcId").as<std::string>();

    try {
      this->traffic_control_data_tc_id_get(tcId, response);
    } catch (Pistache::Http::HttpError& e) {
      response.send(static_cast<Pistache::Http::Code>(e.code()), e.what());
      return;
    } catch (std::exception& e) {
      const std::pair<Pistache::Http::Code, std::string> errorInfo =
          this->handleOperationException(e);
      response.send(errorInfo.first, errorInfo.second);
      return;
    }

  } catch (std::exception& e) {
    response.send(Pistache::Http::Code::Internal_Server_Error, e.what());
  }
}
void TrafficControlDataApi::traffic_control_data_tc_id_put_handler(
    const Pistache::Rest::Request& request,
    Pistache::Http::ResponseWriter response) {
  try {
    // Getting the path params
    auto tcId = request.param(":tcId").as<std::string>();

    // Getting the body param

    TrafficControlData trafficControlData;

    try {
      nlohmann::json::parse(request.body()).get_to(trafficControlData);
      trafficControlData.validate();
    } catch (std::exception& e) {
      const std::pair<Pistache::Http::Code, std::string> errorInfo =
          this->handleParsingException(e);
      response.send(errorInfo.first, errorInfo.second);
      return;
    }

    try {
      this->traffic_control_data_tc_id_put(tcId, trafficControlData, response);
    } catch (Pistache::Http::HttpError& e) {
      response.send(static_cast<Pistache::Http::Code>(e.code()), e.what());
      return;
    } catch (std::exception& e) {
      const std::pair<Pistache::Http::Code, std::string> errorInfo =
          this->handleOperationException(e);
      response.send(errorInfo.first, errorInfo.second);
      return;
    }

  } catch (std::exception& e) {
    response.send(Pistache::Http::Code::Internal_Server_Error, e.what());
  }
}

void TrafficControlDataApi::traffic_control_data_api_default_handler(
    const Pistache::Rest::Request&, Pistache::Http::ResponseWriter response) {
  response.send(
      Pistache::Http::Code::Not_Found, "The requested method does not exist");
}

}  // namespace oai::pcf::provisioning::api
