/**
 * RNI API
 * The ETSI MEC ISG MEC012 Radio Network Information API described using OpenAPI
 *
 * OpenAPI spec version: 1.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * Licensed to the OpenAirInterface (OAI) Software Alliance under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The OpenAirInterface Software Alliance licenses this file to You under
 * the OAI Public License, Version 1.1  (the "License"); you may not use this
 *file except in compliance with the License. You may obtain a copy of the
 *License at
 *
 *      http://www.openairinterface.org/?page_id=698
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *-------------------------------------------------------------------------------
 * For more information about the OpenAirInterface (OAI) Software Alliance:
 *      contact@openairinterface.org
 */

#pragma once

//#include "IndividualSMPolicyDocumentApi.h"

#include "pistache/endpoint.h"
#include "pistache/http.h"
#include "pistache/router.h"
#ifdef __linux__
#include <signal.h>
#include <unistd.h>
#include <vector>
#endif

#include "logger.hpp"
#include "pcf_app.hpp"
#include "SMPoliciesCollectionApiImpl.h"
#include "IndividualSMPolicyDocumentApiImpl.h"
#include "ApplicationSessionsCollectionApiImpl.h"
#include "EventsSubscriptionDocumentApiImpl.h"
#include "IndividualApplicationSessionContextDocumentApiImpl.h"
#include "PCSCFRestorationIndicationApiImpl.h"
#include "provisioning_api/impl/DefaultPolicyDecisionsApiImpl.h"
#include "provisioning_api/impl/SlicePolicyDecisionsApiImpl.h"
#include "provisioning_api/impl/SupiPolicyDecisionsApiImpl.h"
#include "provisioning_api/impl/DNNPolicyDecisionsApiImpl.h"
#include "provisioning_api/impl/QOSDataApiImpl.h"
#include "provisioning_api/impl/TrafficControlDataApiImpl.h"
#include "provisioning_api/impl/PCCRulesApiImpl.h"

namespace oai::pcf::api {

class PCFApiServer {
 public:
  PCFApiServer(
      const Pistache::Address& address,
      const std::unique_ptr<oai::pcf::app::pcf_app>& pcf_app_inst)
      : m_httpEndpoint(std::make_shared<Pistache::Http::Endpoint>(address)) {
    m_router = std::make_shared<Pistache::Rest::Router>();
    // TODO hardcode http string, how to handle https
    m_address = "http://" + address.host() + ":" + (address.port()).toString();

    m_smPoliciesCollectionApi =
        std::make_shared<oai::pcf::api::SMPoliciesCollectionApiImpl>(
            m_router, pcf_app_inst->get_pcf_smpc_service(), m_address);

    m_individualSmPolicyDocumentApi =
        std::make_shared<oai::pcf::api::IndividualSMPolicyDocumentApiImpl>(
            m_router, pcf_app_inst->get_pcf_smpc_service(), m_address);

    m_applicationSessionsCollectionApi =
        std::make_shared<oai::pcf::api::ApplicationSessionsCollectionApiImpl>(
            m_router, pcf_app_inst->get_pcf_policy_authorization_service(),
            m_address);

    m_eventsSubscriptionDocumentApi =
        std::make_shared<oai::pcf::api::EventsSubscriptionDocumentApiImpl>(
            m_router, pcf_app_inst->get_pcf_policy_authorization_service(),
            m_address);

    m_individualApplicationSessionContextDocumentApi = std::make_shared<
        oai::pcf::api::IndividualApplicationSessionContextDocumentApiImpl>(
        m_router, pcf_app_inst->get_pcf_policy_authorization_service(),
        m_address);

    m_pcscfRestorationIndicationApi =
        std::make_shared<oai::pcf::api::PCSCFRestorationIndicationApiImpl>(
            m_router, pcf_app_inst->get_pcf_policy_authorization_service(),
            m_address);

    m_defaultPolicyDecisionProvisioningApi = std::make_shared<
        oai::pcf::provisioning::api::DefaultPolicyDecisionsApiImpl>(m_router);

    m_slicePolicyDecisionProvisioningApi = std::make_shared<
        oai::pcf::provisioning::api::SlicePolicyDecisionsApiImpl>(m_router);

    m_supiPolicyDecisionProvisioningApi = std::make_shared<
        oai::pcf::provisioning::api::SupiPolicyDecisionsApiImpl>(m_router);

    m_dnnPolicyDecisionProvisioningApi = std::make_shared<
        oai::pcf::provisioning::api::DNNPolicyDecisionsApiImpl>(m_router);

    m_pccRulesProvisioningApi =
        std::make_shared<oai::pcf::provisioning::api::PCCRulesApiImpl>(
            m_router);

    m_qosDataProvisioningApi =
        std::make_shared<oai::pcf::provisioning::api::QOSDataApiImpl>(m_router);

    m_trafficControlDataProvisioningApi = std::make_shared<
        oai::pcf::provisioning::api::TrafficControlDataApiImpl>(m_router);
  }
  void init(size_t thr = 1);
  void start();
  void shutdown();

 private:
  std::shared_ptr<Pistache::Http::Endpoint> m_httpEndpoint;
  std::shared_ptr<Pistache::Rest::Router> m_router;

  std::string m_address;

  std::shared_ptr<oai::pcf::api::SMPoliciesCollectionApiImpl>
      m_smPoliciesCollectionApi;

  std::shared_ptr<oai::pcf::api::IndividualSMPolicyDocumentApiImpl>
      m_individualSmPolicyDocumentApi;

  std::shared_ptr<oai::pcf::api::ApplicationSessionsCollectionApiImpl>
      m_applicationSessionsCollectionApi;

  std::shared_ptr<oai::pcf::api::EventsSubscriptionDocumentApiImpl>
      m_eventsSubscriptionDocumentApi;

  std::shared_ptr<
      oai::pcf::api::IndividualApplicationSessionContextDocumentApiImpl>
      m_individualApplicationSessionContextDocumentApi;

  std::shared_ptr<oai::pcf::api::PCSCFRestorationIndicationApiImpl>
      m_pcscfRestorationIndicationApi;
  std::shared_ptr<oai::pcf::provisioning::api::DefaultPolicyDecisionsApiImpl>
      m_defaultPolicyDecisionProvisioningApi;

  std::shared_ptr<oai::pcf::provisioning::api::DNNPolicyDecisionsApiImpl>
      m_dnnPolicyDecisionProvisioningApi;

  std::shared_ptr<oai::pcf::provisioning::api::SupiPolicyDecisionsApiImpl>
      m_supiPolicyDecisionProvisioningApi;

  std::shared_ptr<oai::pcf::provisioning::api::SlicePolicyDecisionsApiImpl>
      m_slicePolicyDecisionProvisioningApi;

  std::shared_ptr<oai::pcf::provisioning::api::PCCRulesApiImpl>
      m_pccRulesProvisioningApi;

  std::shared_ptr<oai::pcf::provisioning::api::QOSDataApiImpl>
      m_qosDataProvisioningApi;

  std::shared_ptr<oai::pcf::provisioning::api::TrafficControlDataApiImpl>
      m_trafficControlDataProvisioningApi;
};
}  // namespace oai::pcf::api