#/*
# * SPDX-License-Identifier: LicenseRef-CSSL-1.0
# */

#---------------------------------------------------------------------
#
# Dockerfile for the Open-Air-Interface PCF service
#   Valid for Ubuntu-20.04 (focal),
#             Ubuntu-22.04 (jammy),
#             Ubuntu-24.04 (noble)
#
# The port exposed by container are 8080/tcp , 8080/tcp change it according to your setup
#
#---------------------------------------------------------------------

#---------------------------------------------------------------------
# BASE IMAGE
#---------------------------------------------------------------------
ARG BASE_IMAGE=ubuntu:noble
FROM $BASE_IMAGE AS oai-pcf-base

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Paris
ENV IS_DOCKERFILE=1
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get upgrade --yes && \
    DEBIAN_FRONTEND=noninteractive apt-get install --yes \
      psmisc \
      git \
  && rm -rf /var/lib/apt/lists/*

# Some GIT configuration command quite useful
RUN git config --global https.postBuffer 199757920 && \
    git config --global http.sslverify false
ARG ENABLE_LTTNG=false
# Copying source code
WORKDIR /openair-pcf
COPY ./build/scripts /openair-pcf/build/scripts/
COPY ./build/common-build /openair-pcf/build/common-build/
COPY ./build/pcf/CMakeLists.txt /openair-pcf/build/pcf/CMakeLists.txt
COPY ./build/cmake_modules /openair-pcf/build/cmake_modules/

# Installing all the needed libraries/packages to build and run PCF
WORKDIR /openair-pcf/build/scripts
RUN ./build_pcf --install-deps --force && \
    ldconfig

#---------------------------------------------------------------------
# BUILDER IMAGE
#---------------------------------------------------------------------
FROM oai-pcf-base AS oai-pcf-builder
# Copying source code
COPY . /openair-pcf
# Building PCF
WORKDIR /openair-pcf/build/scripts

RUN  if [ "$ENABLE_LTTNG" = "true" ]; then DEBIAN_FRONTEND=noninteractive apt-get install --yes \
        lttng-modules-dkms \
        liblttng-ust-dev \
        lttng-tools && \
        ldconfig && \
        ./build_pcf --clean --Verbose --build-type Release --jobs --lttng; \
    else \
        ldconfig && \
        ./build_pcf --clean --Verbose --build-type Release --jobs; \
    fi && \
    ldd /openair-pcf/build/pcf/build/pcf && \
    mv /openair-pcf/build/pcf/build/pcf /openair-pcf/build/pcf/build/oai_pcf


#---------------------------------------------------------------------
# TARGET IMAGE
#---------------------------------------------------------------------
FROM $BASE_IMAGE AS oai-pcf
ARG TARGETPLATFORM
ARG VERSION=v4.47.1
ENV TARGETPLATFORM=${TARGETPLATFORM}

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Paris
ARG ENABLE_LTTNG=false
# We install some debug tools for the moment in addition of mandatory libraries
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get upgrade --yes && \
    DEBIAN_FRONTEND=noninteractive apt-get install --yes \
# Debug Tools that are not mandatory
      tzdata \
      psmisc \
      net-tools \
      tcpdump \
      iputils-ping \
      bc \
      wget \
# Mandatory packages for the NF to run
      openssl \
# Ubuntu 20 --> libasan5
# Ubuntu 22 --> libasan6
#      libasan? \
# Ubuntu 20 --> boost 1.71
# Ubuntu 22 --> boost 1.74
# Ubuntu 24 --> boost 1.83
      libboost-filesystem1.??.0 \
      libcurl?-gnutls \
      librtmp1 \
      libpsl5 \
# Ubuntu 20 --> gcc-9-plugin-dev
# Ubuntu 22 --> gcc-11-plugin-dev
# Ubuntu 24 --> gcc-13-plugin-dev or gcc-14-plugin-dev
      gcc-*-plugin-dev \
      libmysqlclient2? \
# lttng
  && if [ "$ENABLE_LTTNG" = "true" ]; then DEBIAN_FRONTEND=noninteractive apt-get install --yes liblttng-ust-dev; fi \
  && rm -rf /var/lib/apt/lists/*

# Copying executable and generated libraries
WORKDIR /openair-pcf/bin
COPY --from=oai-pcf-builder \
    /openair-pcf/build/pcf/build/oai_pcf \
    /openair-pcf/scripts/healthcheck.sh \
    ./

RUN echo "Target platform is: ${TARGETPLATFORM}" && \
    case "${TARGETPLATFORM}" in \
      "linux/amd64") BINARY="yq_linux_amd64"; ;; \
      "linux/arm64") BINARY="yq_linux_arm64"; ;; \
      *) echo "Unsupported platform"; exit 1; ;; \
    esac && \
    wget https://github.com/mikefarah/yq/releases/download/${VERSION}/${BINARY} -O /usr/bin/yq && \
    chmod +x /usr/bin/yq

WORKDIR /usr/local/lib/
COPY --from=oai-pcf-builder \
# Copying only the packages built from source
    /usr/local/lib/libpistache.so* \
    /usr/local/lib/libnghttp2.so.14 \
    /usr/local/lib/libnghttp2_asio.so.1 \
    /usr/local/lib/libyaml-cpp.so.0.? \
    /usr/local/lib/libcpr.so.1* \
    /usr/local/lib/libspdlog.so \
    /usr/local/lib/libfmt.so \
    /usr/local/lib/libmysqlclient-21.so \
    /usr/local/lib/libssl-1.1.so \
    /usr/local/lib/libcrypto-1.1.so \
    /usr/local/lib/libodb-2.5.so \
    /usr/local/lib/libodb-mysql-2.5.so \
    ./

RUN ldconfig && \
    ldd /openair-pcf/bin/oai_pcf

# Copying template configuration files
# The configuration folder will be flat
WORKDIR /openair-pcf/etc
COPY --from=oai-pcf-builder \
    /openair-pcf/etc/config.yaml \
    ./

WORKDIR /openair-pcf

ARG GIT_COMMIT

LABEL org.opencontainers.image.authors="OpenAirInterface <oaicicdteam@openairinterface.org>" \
      org.opencontainers.image.vendor="OpenAirInterface Software Alliance" \
      org.opencontainers.image.licenses="Collaborative Standards Software License v1.0" \
      org.opencontainers.image.title="OAI PCF" \
      org.opencontainers.image.description="OpenAirInterface Policy Control Function" \
      org.opencontainers.image.revision="commit:${GIT_COMMIT}"

EXPOSE 80/tcp 8080/tcp 5342 5343 5344
# healthcheck
HEALTHCHECK --interval=10s \
            --timeout=15s \
            --retries=6 \
    CMD /openair-pcf/bin/healthcheck.sh

CMD ["/openair-pcf/bin/oai_pcf", "-c", "/openair-pcf/etc/config.yaml", "-o"]
