#/*
# * Licensed to the OpenAirInterface (OAI) Software Alliance under one or more
# * contributor license agreements.  See the NOTICE file distributed with
# * this work for additional information regarding copyright ownership.
# * The OpenAirInterface Software Alliance licenses this file to You under
# * the OAI Public License, Version 1.1  (the "License"); you may not use this file
# * except in compliance with the License.
# * You may obtain a copy of the License at
# *
# *      http://www.openairinterface.org/?page_id=698
# *
# * Unless required by applicable law or agreed to in writing, software
# * distributed under the License is distributed on an "AS IS" BASIS,
# * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# * See the License for the specific language governing permissions and
# * limitations under the License.
# *-------------------------------------------------------------------------------
# * For more information about the OpenAirInterface (OAI) Software Alliance:
# *      contact@openairinterface.org
# */
#---------------------------------------------------------------------
#
# Dockerfile for the Open-Air-Interface PCF service
#   Valid for Ubuntu-18.04 (bionic),
#             Ubuntu-20.04 (focal),
#             Ubuntu-22.04 (jammy)
# The port exposed by container are 8080/tcp , 8080/tcp change it according to your setup
#
#---------------------------------------------------------------------

#---------------------------------------------------------------------
# BASE IMAGE
#---------------------------------------------------------------------
ARG BASE_IMAGE=ubuntu:focal
FROM $BASE_IMAGE as oai-pcf-base

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Paris
ENV IS_DOCKERFILE=1
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get upgrade --yes && \
    DEBIAN_FRONTEND=noninteractive apt-get install --yes \
      psmisc \
      git \
  && rm -rf /var/lib/apt/lists/*

# Some GIT configuration command quite useful
RUN git config --global https.postBuffer 123289600 && \
    git config --global http.sslverify false

# Copying source code
WORKDIR /openair-pcf
COPY ./build/scripts /openair-pcf/build/scripts/
COPY ./build/common-build /openair-pcf/build/common-build/
COPY ./build/pcf/CMakeLists.txt /openair-pcf/build/pcf/CMakeLists.txt
COPY ./build/cmake_modules /openair-pcf/build/cmake_modules/

# Installing all the needed libraries/packages to build and run PCF
WORKDIR /openair-pcf/build/scripts
RUN ./build_pcf --install-deps --force && \
    ldconfig

#---------------------------------------------------------------------
# BUILDER IMAGE
#---------------------------------------------------------------------
FROM oai-pcf-base as oai-pcf-builder
# Copying source code
COPY . /openair-pcf
# Building PCF
WORKDIR /openair-pcf/build/scripts
RUN ./build_pcf --clean --Verbose --build-type Release --jobs && \
    ldd /openair-pcf/build/pcf/build/pcf && \
    mv /openair-pcf/build/pcf/build/pcf /openair-pcf/build/pcf/build/oai_pcf && \
    # Adapting the entrypoint to PCF NF
    sed -i -e "s@openair-nf-root-folder@openair-pcf@g" \
           -e "s@nf-config-file@pcf.yaml@g" \
           ../common-build/docker-scripts/entrypoint.py

#---------------------------------------------------------------------
# TARGET IMAGE
#---------------------------------------------------------------------
FROM $BASE_IMAGE as oai-pcf
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Paris
# We install some debug tools for the moment in addition of mandatory libraries
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get upgrade --yes && \
    DEBIAN_FRONTEND=noninteractive apt-get install --yes \
      python3 \
      python3-jinja2 \
      psmisc \
      net-tools \
      tzdata \
      bc \
      openssl \
# Ubuntu 18 --> libasan4
# Ubuntu 20 --> libasan5
# Ubuntu 22 --> libasan6
#      libasan? \
# Ubuntu 18 --> boost62/65 -> will remove both
# Ubuntu 20 --> boost67/71 -> will remove 67
# Ubuntu 22 --> boost74
      libboost-filesystem1.??.0 \
      libcurl?-gnutls \
      librtmp1 \
      libpsl5 \
  && rm -rf /var/lib/apt/lists/* \
       /lib/x86_64-linux-gnu/libboost_system.so.1.6*.0 \
       /lib/x86_64-linux-gnu/ibboost_filesystem.so.1.6*.0

# Copying executable and generated libraries
WORKDIR /openair-pcf/bin
COPY --from=oai-pcf-builder \
    /openair-pcf/build/pcf/build/oai_pcf \
    /openair-pcf/build/common-build/docker-scripts/entrypoint.py \
    /openair-pcf/scripts/healthcheck.sh \
    ./

WORKDIR /usr/local/lib/
COPY --from=oai-pcf-builder \
# Copying only the packages built from source
    /usr/local/lib/libpistache.so \
    /usr/local/lib/libnghttp2.so.14 \
    /usr/local/lib/libnghttp2_asio.so.1 \
    /usr/local/lib/libyaml-cpp.so.0.? \
    /usr/local/lib/libspdlog.so \
    /usr/local/lib/libfmt.so \
# Ubuntu 18 --> boost 67 will be copied
    /usr/lib/libboost_system.so.1.* \
    /usr/lib/libboost_filesystem.so.1.* \
    ./

RUN ldconfig && \
    ldd /openair-pcf/bin/oai_pcf

# Copying template configuration files
# The configuration folder will be flat
WORKDIR /openair-pcf/etc
COPY --from=oai-pcf-builder \
    /openair-pcf/etc/pcf.yaml \
    ./

WORKDIR /openair-pcf

EXPOSE 80/tcp 8080/tcp
# healthcheck
HEALTHCHECK --interval=10s \
            --timeout=15s \
            --retries=6 \
    CMD /openair-pcf/bin/healthcheck.sh

ENTRYPOINT ["python3","/openair-pcf/bin/entrypoint.py"]
CMD ["/openair-pcf/bin/oai_pcf", "-c", "/openair-pcf/etc/pcf.yaml", "-o"]
