// -*- C++ -*-
//
// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#include "Arp-odb.hxx"

#include <cassert>
#include <cstring>  // std::memcpy

#include <odb/mysql/traits.hxx>
#include <odb/mysql/database.hxx>
#include <odb/mysql/transaction.hxx>
#include <odb/mysql/connection.hxx>
#include <odb/mysql/statement.hxx>
#include <odb/mysql/statement-cache.hxx>
#include <odb/mysql/container-statements.hxx>
#include <odb/mysql/exceptions.hxx>
#include <odb/mysql/enum.hxx>

namespace odb {
// Arp
//

bool access::composite_value_traits< ::oai::model::common::Arp, id_mysql>::grow(
    image_type& i, my_bool* t) {
  ODB_POTENTIALLY_UNUSED(i);
  ODB_POTENTIALLY_UNUSED(t);

  bool grew(false);

  // m_PriorityLevel
  //
  t[0UL] = 0;

  // m_PreemptCap
  //
  if (composite_value_traits<
          ::oai::model::common::PreemptionCapability,
          id_mysql>::grow(i.m_PreemptCap_value, t + 1UL))
    grew = true;

  // m_PreemptVuln
  //
  if (composite_value_traits<
          ::oai::model::common::PreemptionVulnerability,
          id_mysql>::grow(i.m_PreemptVuln_value, t + 2UL))
    grew = true;

  return grew;
}

void access::composite_value_traits< ::oai::model::common::Arp, id_mysql>::bind(
    MYSQL_BIND* b, image_type& i, mysql::statement_kind sk) {
  ODB_POTENTIALLY_UNUSED(b);
  ODB_POTENTIALLY_UNUSED(i);
  ODB_POTENTIALLY_UNUSED(sk);

  using namespace mysql;

  std::size_t n(0);
  ODB_POTENTIALLY_UNUSED(n);

  // m_PriorityLevel
  //
  b[n].buffer_type = MYSQL_TYPE_LONG;
  b[n].is_unsigned = 0;
  b[n].buffer      = &i.m_PriorityLevel_value;
  b[n].is_null     = &i.m_PriorityLevel_null;
  n++;

  // m_PreemptCap
  //
  composite_value_traits<
      ::oai::model::common::PreemptionCapability,
      id_mysql>::bind(b + n, i.m_PreemptCap_value, sk);
  n += 1UL;

  // m_PreemptVuln
  //
  composite_value_traits<
      ::oai::model::common::PreemptionVulnerability,
      id_mysql>::bind(b + n, i.m_PreemptVuln_value, sk);
  n += 1UL;
}

bool access::composite_value_traits< ::oai::model::common::Arp, id_mysql>::init(
    image_type& i, const value_type& o, mysql::statement_kind sk) {
  ODB_POTENTIALLY_UNUSED(i);
  ODB_POTENTIALLY_UNUSED(o);
  ODB_POTENTIALLY_UNUSED(sk);

  using namespace mysql;

  bool grew(false);

  // m_PriorityLevel
  //
  {
    ::int32_t const& v = o.m_PriorityLevel;

    bool is_null(false);
    mysql::value_traits< ::int32_t, mysql::id_long>::set_image(
        i.m_PriorityLevel_value, is_null, v);
    i.m_PriorityLevel_null = is_null;
  }

  // m_PreemptCap
  //
  {
    ::oai::model::common::PreemptionCapability const& v = o.m_PreemptCap;

    if (composite_value_traits<
            ::oai::model::common::PreemptionCapability,
            id_mysql>::init(i.m_PreemptCap_value, v, sk))
      grew = true;
  }

  // m_PreemptVuln
  //
  {
    ::oai::model::common::PreemptionVulnerability const& v = o.m_PreemptVuln;

    if (composite_value_traits<
            ::oai::model::common::PreemptionVulnerability,
            id_mysql>::init(i.m_PreemptVuln_value, v, sk))
      grew = true;
  }

  return grew;
}

void access::composite_value_traits< ::oai::model::common::Arp, id_mysql>::init(
    value_type& o, const image_type& i, database* db) {
  ODB_POTENTIALLY_UNUSED(o);
  ODB_POTENTIALLY_UNUSED(i);
  ODB_POTENTIALLY_UNUSED(db);

  // m_PriorityLevel
  //
  {
    ::int32_t& v = o.m_PriorityLevel;

    mysql::value_traits< ::int32_t, mysql::id_long>::set_value(
        v, i.m_PriorityLevel_value, i.m_PriorityLevel_null);
  }

  // m_PreemptCap
  //
  {
    ::oai::model::common::PreemptionCapability& v = o.m_PreemptCap;

    composite_value_traits<
        ::oai::model::common::PreemptionCapability,
        id_mysql>::init(v, i.m_PreemptCap_value, db);
  }

  // m_PreemptVuln
  //
  {
    ::oai::model::common::PreemptionVulnerability& v = o.m_PreemptVuln;

    composite_value_traits<
        ::oai::model::common::PreemptionVulnerability,
        id_mysql>::init(v, i.m_PreemptVuln_value, db);
  }
}
}  // namespace odb

#include <odb/post.hxx>
