// -*- C++ -*-
//
// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

namespace odb {}

namespace odb {
// Arp
//

inline bool access::composite_value_traits<
    ::oai::model::common::Arp, id_mysql>::get_null(const image_type& i) {
  bool r(true);
  r = r && i.m_PriorityLevel_null;
  r = r && composite_value_traits<
               ::oai::model::common::PreemptionCapability,
               id_mysql>::get_null(i.m_PreemptCap_value);
  r = r && composite_value_traits<
               ::oai::model::common::PreemptionVulnerability,
               id_mysql>::get_null(i.m_PreemptVuln_value);
  return r;
}

inline void
access::composite_value_traits< ::oai::model::common::Arp, id_mysql>::set_null(
    image_type& i, mysql::statement_kind sk) {
  ODB_POTENTIALLY_UNUSED(sk);

  using namespace mysql;

  i.m_PriorityLevel_null = 1;
  composite_value_traits<
      ::oai::model::common::PreemptionCapability,
      id_mysql>::set_null(i.m_PreemptCap_value, sk);
  composite_value_traits<
      ::oai::model::common::PreemptionVulnerability,
      id_mysql>::set_null(i.m_PreemptVuln_value, sk);
}
}  // namespace odb
