// -*- C++ -*-
//
// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef DNN_POLICY_DECISION_ODB_HXX
#define DNN_POLICY_DECISION_ODB_HXX

#include <odb/version.hxx>

#include <odb/pre.hxx>

#include "DnnPolicyDecision.h"

#include <memory>
#include <cstddef>
#include <utility>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/no-op-cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb {
// DnnPolicyDecision
//
template<>
struct class_traits< ::oai::pcf::provisioning::model::DnnPolicyDecision> {
  static const class_kind kind = class_object;
};

template<>
class access::object_traits<
    ::oai::pcf::provisioning::model::DnnPolicyDecision> {
 public:
  typedef ::oai::pcf::provisioning::model::DnnPolicyDecision object_type;
  typedef ::oai::pcf::provisioning::model::DnnPolicyDecision* pointer_type;
  typedef odb::pointer_traits<pointer_type> pointer_traits;

  static const bool polymorphic = false;

  typedef ::std::string id_type;

  static const bool auto_id = false;

  static const bool abstract = false;

  static id_type id(const object_type&);

  typedef no_op_pointer_cache_traits<pointer_type> pointer_cache_traits;

  typedef no_op_reference_cache_traits<object_type> reference_cache_traits;

  static void callback(database&, object_type&, callback_event);

  static void callback(database&, const object_type&, callback_event);
};
}  // namespace odb

#include <odb/details/buffer.hxx>

#include <odb/mysql/version.hxx>
#include <odb/mysql/forward.hxx>
#include <odb/mysql/binding.hxx>
#include <odb/mysql/mysql-types.hxx>
#include <odb/mysql/query.hxx>

namespace odb {
// DnnPolicyDecision
//
template<typename A>
struct query_columns<
    ::oai::pcf::provisioning::model::DnnPolicyDecision, id_mysql, A> {
  // Dnn
  //
  typedef mysql::query_column<
      mysql::value_traits< ::std::string, mysql::id_string>::query_type,
      mysql::id_string>
      Dnn_type_;

  static const Dnn_type_ Dnn;

  // DnnIsSet
  //
  typedef mysql::query_column<
      mysql::value_traits<bool, mysql::id_tiny>::query_type, mysql::id_tiny>
      DnnIsSet_type_;

  static const DnnIsSet_type_ DnnIsSet;

  // PccRuleIdsIsSet
  //
  typedef mysql::query_column<
      mysql::value_traits<bool, mysql::id_tiny>::query_type, mysql::id_tiny>
      PccRuleIdsIsSet_type_;

  static const PccRuleIdsIsSet_type_ PccRuleIdsIsSet;
};

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::DnnPolicyDecision, id_mysql, A>::Dnn_type_
    query_columns<
        ::oai::pcf::provisioning::model::DnnPolicyDecision, id_mysql,
        A>::Dnn(A::table_name, "`Dnn`", 0);

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::DnnPolicyDecision, id_mysql,
    A>::DnnIsSet_type_
    query_columns<
        ::oai::pcf::provisioning::model::DnnPolicyDecision, id_mysql,
        A>::DnnIsSet(A::table_name, "`DnnIsSet`", 0);

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::DnnPolicyDecision, id_mysql,
    A>::PccRuleIdsIsSet_type_
    query_columns<
        ::oai::pcf::provisioning::model::DnnPolicyDecision, id_mysql,
        A>::PccRuleIdsIsSet(A::table_name, "`PccRuleIdsIsSet`", 0);

template<typename A>
struct pointer_query_columns<
    ::oai::pcf::provisioning::model::DnnPolicyDecision, id_mysql, A>
    : query_columns<
          ::oai::pcf::provisioning::model::DnnPolicyDecision, id_mysql, A> {};

template<>
class access::object_traits_impl<
    ::oai::pcf::provisioning::model::DnnPolicyDecision, id_mysql>
    : public access::object_traits<
          ::oai::pcf::provisioning::model::DnnPolicyDecision> {
 public:
  struct id_image_type {
    details::buffer id_value;
    unsigned long id_size;
    my_bool id_null;

    std::size_t version;
  };

  struct image_type {
    // m_Dnn
    //
    details::buffer m_Dnn_value;
    unsigned long m_Dnn_size;
    my_bool m_Dnn_null;

    // m_DnnIsSet
    //
    signed char m_DnnIsSet_value;
    my_bool m_DnnIsSet_null;

    // m_PccRuleIdsIsSet
    //
    signed char m_PccRuleIdsIsSet_value;
    my_bool m_PccRuleIdsIsSet_null;

    std::size_t version;
  };

  struct extra_statement_cache_type;

  // m_PccRuleIds
  //
  struct PccRuleIds_traits {
    static const std::size_t id_column_count   = 1UL;
    static const std::size_t data_column_count = 3UL;

    static const bool versioned = false;

    static const char insert_statement[];
    static const char select_statement[];
    static const char delete_statement[];

    typedef ::std::vector< ::std::basic_string<char> > container_type;
    typedef odb::access::container_traits<container_type> container_traits_type;
    typedef container_traits_type::index_type index_type;
    typedef container_traits_type::value_type value_type;

    typedef ordered_functions<index_type, value_type> functions_type;
    typedef mysql::container_statements<PccRuleIds_traits> statements_type;

    struct data_image_type {
      // index
      //
      unsigned long long index_value;
      my_bool index_null;

      // value
      //
      details::buffer value_value;
      unsigned long value_size;
      my_bool value_null;

      std::size_t version;
    };

    static void bind(
        MYSQL_BIND*, const MYSQL_BIND* id, std::size_t id_size,
        data_image_type&);

    static void grow(data_image_type&, my_bool*);

    static void init(data_image_type&, index_type*, const value_type&);

    static void init(
        index_type&, value_type&, const data_image_type&, database*);

    static void insert(index_type, const value_type&, void*);

    static bool select(index_type&, value_type&, void*);

    static void delete_(void*);

    static void persist(const container_type&, statements_type&);

    static void load(container_type&, statements_type&);

    static void update(const container_type&, statements_type&);

    static void erase(statements_type&);
  };

  using object_traits<object_type>::id;

  static id_type id(const image_type&);

  static bool grow(image_type&, my_bool*);

  static void bind(MYSQL_BIND*, image_type&, mysql::statement_kind);

  static void bind(MYSQL_BIND*, id_image_type&);

  static bool init(image_type&, const object_type&, mysql::statement_kind);

  static void init(object_type&, const image_type&, database*);

  static void init(id_image_type&, const id_type&);

  typedef mysql::object_statements<object_type> statements_type;

  typedef mysql::query_base query_base_type;

  static const std::size_t column_count                    = 3UL;
  static const std::size_t id_column_count                 = 1UL;
  static const std::size_t inverse_column_count            = 0UL;
  static const std::size_t readonly_column_count           = 0UL;
  static const std::size_t managed_optimistic_column_count = 0UL;

  static const std::size_t separate_load_column_count   = 0UL;
  static const std::size_t separate_update_column_count = 0UL;

  static const bool versioned = false;

  static const char persist_statement[];
  static const char find_statement[];
  static const char update_statement[];
  static const char erase_statement[];
  static const char query_statement[];
  static const char erase_query_statement[];

  static const char table_name[];

  static void persist(database&, const object_type&);

  static pointer_type find(database&, const id_type&);

  static bool find(database&, const id_type&, object_type&);

  static bool reload(database&, object_type&);

  static void update(database&, const object_type&);

  static void erase(database&, const id_type&);

  static void erase(database&, const object_type&);

  static result<object_type> query(database&, const query_base_type&);

  static unsigned long long erase_query(database&, const query_base_type&);

 public:
  static bool find_(statements_type&, const id_type*);

  static void load_(statements_type&, object_type&, bool reload);
};

template<>
class access::object_traits_impl<
    ::oai::pcf::provisioning::model::DnnPolicyDecision, id_common>
    : public access::object_traits_impl<
          ::oai::pcf::provisioning::model::DnnPolicyDecision, id_mysql> {};

// DnnPolicyDecision
//
}  // namespace odb

#include "DnnPolicyDecision-odb.ixx"

#include <odb/post.hxx>

#endif  // DNN_POLICY_DECISION_ODB_HXX
