// -*- C++ -*-
//
// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

namespace odb {
// DnnPolicyDecision
//

inline access::object_traits<
    ::oai::pcf::provisioning::model::DnnPolicyDecision>::id_type
access::object_traits< ::oai::pcf::provisioning::model::DnnPolicyDecision>::id(
    const object_type& o) {
  return o.m_Dnn;
}

inline void
access::object_traits< ::oai::pcf::provisioning::model::DnnPolicyDecision>::
    callback(database& db, object_type& x, callback_event e) {
  ODB_POTENTIALLY_UNUSED(db);
  ODB_POTENTIALLY_UNUSED(x);
  ODB_POTENTIALLY_UNUSED(e);
}

inline void
access::object_traits< ::oai::pcf::provisioning::model::DnnPolicyDecision>::
    callback(database& db, const object_type& x, callback_event e) {
  ODB_POTENTIALLY_UNUSED(db);
  ODB_POTENTIALLY_UNUSED(x);
  ODB_POTENTIALLY_UNUSED(e);
}
}  // namespace odb

namespace odb {
// DnnPolicyDecision
//

inline void access::object_traits_impl<
    ::oai::pcf::provisioning::model::DnnPolicyDecision,
    id_mysql>::erase(database& db, const object_type& obj) {
  callback(db, obj, callback_event::pre_erase);
  erase(db, id(obj));
  callback(db, obj, callback_event::post_erase);
}
}  // namespace odb
