/**
 * Policy Decisions API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "DnnPolicyDecision.h"
#include "Helpers.h"

#include <sstream>

namespace oai::pcf::provisioning::model {

DnnPolicyDecision::DnnPolicyDecision() {
  m_Dnn             = "";
  m_DnnIsSet        = false;
  m_PccRuleIdsIsSet = false;
}

void DnnPolicyDecision::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::model::common::helpers::ValidationException(msg.str());
  }
}

bool DnnPolicyDecision::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool DnnPolicyDecision::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "DnnPolicyDecision" : pathPrefix;

  if (pccRuleIdsIsSet()) {
    const std::vector<std::string>& value = m_PccRuleIds;
    const std::string currentValuePath    = _pathPrefix + ".pccRuleIds";

    {  // Recursive validation of array elements
      const std::string oldValuePath = currentValuePath;
      int i                          = 0;
      for (const std::string& value : value) {
        const std::string currentValuePath =
            oldValuePath + "[" + std::to_string(i) + "]";

        i++;
      }
    }
  }

  return success;
}

bool DnnPolicyDecision::operator==(const DnnPolicyDecision& rhs) const {
  return

      ((!dnnIsSet() && !rhs.dnnIsSet()) ||
       (dnnIsSet() && rhs.dnnIsSet() && getDnn() == rhs.getDnn())) &&

      ((!pccRuleIdsIsSet() && !rhs.pccRuleIdsIsSet()) ||
       (pccRuleIdsIsSet() && rhs.pccRuleIdsIsSet() &&
        getPccRuleIds() == rhs.getPccRuleIds()))

          ;
}

bool DnnPolicyDecision::operator!=(const DnnPolicyDecision& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const DnnPolicyDecision& o) {
  j = nlohmann::json();
  if (o.dnnIsSet()) j["dnn"] = o.m_Dnn;
  if (o.pccRuleIdsIsSet() || !o.m_PccRuleIds.empty())
    j["pccRuleIds"] = o.m_PccRuleIds;
}

void from_json(const nlohmann::json& j, DnnPolicyDecision& o) {
  if (j.find("dnn") != j.end()) {
    j.at("dnn").get_to(o.m_Dnn);
    o.m_DnnIsSet = true;
  }
  if (j.find("pccRuleIds") != j.end()) {
    j.at("pccRuleIds").get_to(o.m_PccRuleIds);
    o.m_PccRuleIdsIsSet = true;
  }
}

std::string DnnPolicyDecision::getDnn() const {
  return m_Dnn;
}
void DnnPolicyDecision::setDnn(std::string const& value) {
  m_Dnn      = value;
  m_DnnIsSet = true;
}
bool DnnPolicyDecision::dnnIsSet() const {
  return m_DnnIsSet;
}
void DnnPolicyDecision::unsetDnn() {
  m_DnnIsSet = false;
}
std::vector<std::string> DnnPolicyDecision::getPccRuleIds() const {
  return m_PccRuleIds;
}
void DnnPolicyDecision::setPccRuleIds(std::vector<std::string> const& value) {
  m_PccRuleIds      = value;
  m_PccRuleIdsIsSet = true;
}
bool DnnPolicyDecision::pccRuleIdsIsSet() const {
  return m_PccRuleIdsIsSet;
}
void DnnPolicyDecision::unsetPccRuleIds() {
  m_PccRuleIdsIsSet = false;
}

}  // namespace oai::pcf::provisioning::model
