// -*- C++ -*-
//
// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef PCC_RULE_ODB_ODB_HXX
#define PCC_RULE_ODB_ODB_HXX

#include <odb/version.hxx>

#include <odb/pre.hxx>

#include "PccRuleODB.h"

#include <memory>
#include <cstddef>
#include <utility>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/no-op-cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb {
// PccRuleODB
//
template<>
struct class_traits< ::oai::pcf::provisioning::model::PccRuleODB> {
  static const class_kind kind = class_object;
};

template<>
class access::object_traits< ::oai::pcf::provisioning::model::PccRuleODB> {
 public:
  typedef ::oai::pcf::provisioning::model::PccRuleODB object_type;
  typedef ::oai::pcf::provisioning::model::PccRuleODB* pointer_type;
  typedef odb::pointer_traits<pointer_type> pointer_traits;

  static const bool polymorphic = false;

  typedef ::std::string id_type;

  static const bool auto_id = false;

  static const bool abstract = false;

  static id_type id(const object_type&);

  typedef no_op_pointer_cache_traits<pointer_type> pointer_cache_traits;

  typedef no_op_reference_cache_traits<object_type> reference_cache_traits;

  static void callback(database&, object_type&, callback_event);

  static void callback(database&, const object_type&, callback_event);
};
}  // namespace odb

#include <odb/details/buffer.hxx>

#include <odb/mysql/version.hxx>
#include <odb/mysql/forward.hxx>
#include <odb/mysql/binding.hxx>
#include <odb/mysql/mysql-types.hxx>
#include <odb/mysql/query.hxx>

namespace odb {
// PccRuleODB
//
template<typename A>
struct query_columns<
    ::oai::pcf::provisioning::model::PccRuleODB, id_mysql, A> {
  // FlowInfos
  //
  typedef mysql::query_column<
      mysql::value_traits< ::std::string, mysql::id_string>::query_type,
      mysql::id_string>
      FlowInfos_type_;

  static const FlowInfos_type_ FlowInfos;

  // FlowInfosIsSet
  //
  typedef mysql::query_column<
      mysql::value_traits<bool, mysql::id_tiny>::query_type, mysql::id_tiny>
      FlowInfosIsSet_type_;

  static const FlowInfosIsSet_type_ FlowInfosIsSet;

  // AppId
  //
  typedef mysql::query_column<
      mysql::value_traits< ::std::string, mysql::id_string>::query_type,
      mysql::id_string>
      AppId_type_;

  static const AppId_type_ AppId;

  // AppIdIsSet
  //
  typedef mysql::query_column<
      mysql::value_traits<bool, mysql::id_tiny>::query_type, mysql::id_tiny>
      AppIdIsSet_type_;

  static const AppIdIsSet_type_ AppIdIsSet;

  // AppDescriptor
  //
  typedef mysql::query_column<
      mysql::value_traits< ::std::string, mysql::id_string>::query_type,
      mysql::id_string>
      AppDescriptor_type_;

  static const AppDescriptor_type_ AppDescriptor;

  // AppDescriptorIsSet
  //
  typedef mysql::query_column<
      mysql::value_traits<bool, mysql::id_tiny>::query_type, mysql::id_tiny>
      AppDescriptorIsSet_type_;

  static const AppDescriptorIsSet_type_ AppDescriptorIsSet;

  // ContVer
  //
  typedef mysql::query_column<
      mysql::value_traits< ::int32_t, mysql::id_long>::query_type,
      mysql::id_long>
      ContVer_type_;

  static const ContVer_type_ ContVer;

  // ContVerIsSet
  //
  typedef mysql::query_column<
      mysql::value_traits<bool, mysql::id_tiny>::query_type, mysql::id_tiny>
      ContVerIsSet_type_;

  static const ContVerIsSet_type_ ContVerIsSet;

  // PccRuleId
  //
  typedef mysql::query_column<
      mysql::value_traits< ::std::string, mysql::id_string>::query_type,
      mysql::id_string>
      PccRuleId_type_;

  static const PccRuleId_type_ PccRuleId;

  // Precedence
  //
  typedef mysql::query_column<
      mysql::value_traits< ::int32_t, mysql::id_long>::query_type,
      mysql::id_long>
      Precedence_type_;

  static const Precedence_type_ Precedence;

  // PrecedenceIsSet
  //
  typedef mysql::query_column<
      mysql::value_traits<bool, mysql::id_tiny>::query_type, mysql::id_tiny>
      PrecedenceIsSet_type_;

  static const PrecedenceIsSet_type_ PrecedenceIsSet;

  // AfSigProtocol
  //
  typedef mysql::query_column<
      mysql::value_traits< ::std::string, mysql::id_string>::query_type,
      mysql::id_string>
      AfSigProtocol_type_;

  static const AfSigProtocol_type_ AfSigProtocol;

  // AfSigProtocolIsSet
  //
  typedef mysql::query_column<
      mysql::value_traits<bool, mysql::id_tiny>::query_type, mysql::id_tiny>
      AfSigProtocolIsSet_type_;

  static const AfSigProtocolIsSet_type_ AfSigProtocolIsSet;

  // AppReloc
  //
  typedef mysql::query_column<
      mysql::value_traits<bool, mysql::id_tiny>::query_type, mysql::id_tiny>
      AppReloc_type_;

  static const AppReloc_type_ AppReloc;

  // AppRelocIsSet
  //
  typedef mysql::query_column<
      mysql::value_traits<bool, mysql::id_tiny>::query_type, mysql::id_tiny>
      AppRelocIsSet_type_;

  static const AppRelocIsSet_type_ AppRelocIsSet;

  // RefQosDataIsSet
  //
  typedef mysql::query_column<
      mysql::value_traits<bool, mysql::id_tiny>::query_type, mysql::id_tiny>
      RefQosDataIsSet_type_;

  static const RefQosDataIsSet_type_ RefQosDataIsSet;

  // RefAltQosParamsIsSet
  //
  typedef mysql::query_column<
      mysql::value_traits<bool, mysql::id_tiny>::query_type, mysql::id_tiny>
      RefAltQosParamsIsSet_type_;

  static const RefAltQosParamsIsSet_type_ RefAltQosParamsIsSet;

  // RefTcDataIsSet
  //
  typedef mysql::query_column<
      mysql::value_traits<bool, mysql::id_tiny>::query_type, mysql::id_tiny>
      RefTcDataIsSet_type_;

  static const RefTcDataIsSet_type_ RefTcDataIsSet;

  // RefChgDataIsSet
  //
  typedef mysql::query_column<
      mysql::value_traits<bool, mysql::id_tiny>::query_type, mysql::id_tiny>
      RefChgDataIsSet_type_;

  static const RefChgDataIsSet_type_ RefChgDataIsSet;

  // RefChgN3gDataIsSet
  //
  typedef mysql::query_column<
      mysql::value_traits<bool, mysql::id_tiny>::query_type, mysql::id_tiny>
      RefChgN3gDataIsSet_type_;

  static const RefChgN3gDataIsSet_type_ RefChgN3gDataIsSet;

  // RefUmDataIsSet
  //
  typedef mysql::query_column<
      mysql::value_traits<bool, mysql::id_tiny>::query_type, mysql::id_tiny>
      RefUmDataIsSet_type_;

  static const RefUmDataIsSet_type_ RefUmDataIsSet;

  // RefUmN3gDataIsSet
  //
  typedef mysql::query_column<
      mysql::value_traits<bool, mysql::id_tiny>::query_type, mysql::id_tiny>
      RefUmN3gDataIsSet_type_;

  static const RefUmN3gDataIsSet_type_ RefUmN3gDataIsSet;

  // RefCondData
  //
  typedef mysql::query_column<
      mysql::value_traits< ::std::string, mysql::id_string>::query_type,
      mysql::id_string>
      RefCondData_type_;

  static const RefCondData_type_ RefCondData;

  // RefCondDataIsSet
  //
  typedef mysql::query_column<
      mysql::value_traits<bool, mysql::id_tiny>::query_type, mysql::id_tiny>
      RefCondDataIsSet_type_;

  static const RefCondDataIsSet_type_ RefCondDataIsSet;

  // RefQosMonIsSet
  //
  typedef mysql::query_column<
      mysql::value_traits<bool, mysql::id_tiny>::query_type, mysql::id_tiny>
      RefQosMonIsSet_type_;

  static const RefQosMonIsSet_type_ RefQosMonIsSet;

  // AddrPreserInd
  //
  typedef mysql::query_column<
      mysql::value_traits<bool, mysql::id_tiny>::query_type, mysql::id_tiny>
      AddrPreserInd_type_;

  static const AddrPreserInd_type_ AddrPreserInd;

  // AddrPreserIndIsSet
  //
  typedef mysql::query_column<
      mysql::value_traits<bool, mysql::id_tiny>::query_type, mysql::id_tiny>
      AddrPreserIndIsSet_type_;

  static const AddrPreserIndIsSet_type_ AddrPreserIndIsSet;

  // TscaiInputDl
  //
  typedef mysql::query_column<
      mysql::value_traits< ::std::string, mysql::id_string>::query_type,
      mysql::id_string>
      TscaiInputDl_type_;

  static const TscaiInputDl_type_ TscaiInputDl;

  // TscaiInputDlIsSet
  //
  typedef mysql::query_column<
      mysql::value_traits<bool, mysql::id_tiny>::query_type, mysql::id_tiny>
      TscaiInputDlIsSet_type_;

  static const TscaiInputDlIsSet_type_ TscaiInputDlIsSet;

  // TscaiInputUl
  //
  typedef mysql::query_column<
      mysql::value_traits< ::std::string, mysql::id_string>::query_type,
      mysql::id_string>
      TscaiInputUl_type_;

  static const TscaiInputUl_type_ TscaiInputUl;

  // TscaiInputUlIsSet
  //
  typedef mysql::query_column<
      mysql::value_traits<bool, mysql::id_tiny>::query_type, mysql::id_tiny>
      TscaiInputUlIsSet_type_;

  static const TscaiInputUlIsSet_type_ TscaiInputUlIsSet;

  // DdNotifCtrl
  //
  typedef mysql::query_column<
      mysql::value_traits< ::std::string, mysql::id_string>::query_type,
      mysql::id_string>
      DdNotifCtrl_type_;

  static const DdNotifCtrl_type_ DdNotifCtrl;

  // DdNotifCtrlIsSet
  //
  typedef mysql::query_column<
      mysql::value_traits<bool, mysql::id_tiny>::query_type, mysql::id_tiny>
      DdNotifCtrlIsSet_type_;

  static const DdNotifCtrlIsSet_type_ DdNotifCtrlIsSet;

  // DdNotifCtrl2
  //
  typedef mysql::query_column<
      mysql::value_traits< ::std::string, mysql::id_string>::query_type,
      mysql::id_string>
      DdNotifCtrl2_type_;

  static const DdNotifCtrl2_type_ DdNotifCtrl2;

  // DdNotifCtrl2IsSet
  //
  typedef mysql::query_column<
      mysql::value_traits<bool, mysql::id_tiny>::query_type, mysql::id_tiny>
      DdNotifCtrl2IsSet_type_;

  static const DdNotifCtrl2IsSet_type_ DdNotifCtrl2IsSet;

  // DisUeNotif
  //
  typedef mysql::query_column<
      mysql::value_traits<bool, mysql::id_tiny>::query_type, mysql::id_tiny>
      DisUeNotif_type_;

  static const DisUeNotif_type_ DisUeNotif;

  // DisUeNotifIsSet
  //
  typedef mysql::query_column<
      mysql::value_traits<bool, mysql::id_tiny>::query_type, mysql::id_tiny>
      DisUeNotifIsSet_type_;

  static const DisUeNotifIsSet_type_ DisUeNotifIsSet;
};

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::PccRuleODB, id_mysql, A>::FlowInfos_type_
    query_columns< ::oai::pcf::provisioning::model::PccRuleODB, id_mysql, A>::
        FlowInfos(A::table_name, "`FlowInfos`", 0);

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::PccRuleODB, id_mysql,
    A>::FlowInfosIsSet_type_
    query_columns< ::oai::pcf::provisioning::model::PccRuleODB, id_mysql, A>::
        FlowInfosIsSet(A::table_name, "`FlowInfosIsSet`", 0);

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::PccRuleODB, id_mysql, A>::AppId_type_
    query_columns< ::oai::pcf::provisioning::model::PccRuleODB, id_mysql, A>::
        AppId(A::table_name, "`AppId`", 0);

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::PccRuleODB, id_mysql, A>::AppIdIsSet_type_
    query_columns< ::oai::pcf::provisioning::model::PccRuleODB, id_mysql, A>::
        AppIdIsSet(A::table_name, "`AppIdIsSet`", 0);

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::PccRuleODB, id_mysql,
    A>::AppDescriptor_type_
    query_columns< ::oai::pcf::provisioning::model::PccRuleODB, id_mysql, A>::
        AppDescriptor(A::table_name, "`AppDescriptor`", 0);

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::PccRuleODB, id_mysql,
    A>::AppDescriptorIsSet_type_
    query_columns< ::oai::pcf::provisioning::model::PccRuleODB, id_mysql, A>::
        AppDescriptorIsSet(A::table_name, "`AppDescriptorIsSet`", 0);

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::PccRuleODB, id_mysql, A>::ContVer_type_
    query_columns< ::oai::pcf::provisioning::model::PccRuleODB, id_mysql, A>::
        ContVer(A::table_name, "`ContVer`", 0);

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::PccRuleODB, id_mysql,
    A>::ContVerIsSet_type_
    query_columns< ::oai::pcf::provisioning::model::PccRuleODB, id_mysql, A>::
        ContVerIsSet(A::table_name, "`ContVerIsSet`", 0);

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::PccRuleODB, id_mysql, A>::PccRuleId_type_
    query_columns< ::oai::pcf::provisioning::model::PccRuleODB, id_mysql, A>::
        PccRuleId(A::table_name, "`PccRuleId`", 0);

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::PccRuleODB, id_mysql, A>::Precedence_type_
    query_columns< ::oai::pcf::provisioning::model::PccRuleODB, id_mysql, A>::
        Precedence(A::table_name, "`Precedence`", 0);

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::PccRuleODB, id_mysql,
    A>::PrecedenceIsSet_type_
    query_columns< ::oai::pcf::provisioning::model::PccRuleODB, id_mysql, A>::
        PrecedenceIsSet(A::table_name, "`PrecedenceIsSet`", 0);

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::PccRuleODB, id_mysql,
    A>::AfSigProtocol_type_
    query_columns< ::oai::pcf::provisioning::model::PccRuleODB, id_mysql, A>::
        AfSigProtocol(A::table_name, "`AfSigProtocol`", 0);

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::PccRuleODB, id_mysql,
    A>::AfSigProtocolIsSet_type_
    query_columns< ::oai::pcf::provisioning::model::PccRuleODB, id_mysql, A>::
        AfSigProtocolIsSet(A::table_name, "`AfSigProtocolIsSet`", 0);

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::PccRuleODB, id_mysql, A>::AppReloc_type_
    query_columns< ::oai::pcf::provisioning::model::PccRuleODB, id_mysql, A>::
        AppReloc(A::table_name, "`AppReloc`", 0);

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::PccRuleODB, id_mysql,
    A>::AppRelocIsSet_type_
    query_columns< ::oai::pcf::provisioning::model::PccRuleODB, id_mysql, A>::
        AppRelocIsSet(A::table_name, "`AppRelocIsSet`", 0);

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::PccRuleODB, id_mysql,
    A>::RefQosDataIsSet_type_
    query_columns< ::oai::pcf::provisioning::model::PccRuleODB, id_mysql, A>::
        RefQosDataIsSet(A::table_name, "`RefQosDataIsSet`", 0);

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::PccRuleODB, id_mysql,
    A>::RefAltQosParamsIsSet_type_
    query_columns< ::oai::pcf::provisioning::model::PccRuleODB, id_mysql, A>::
        RefAltQosParamsIsSet(A::table_name, "`RefAltQosParamsIsSet`", 0);

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::PccRuleODB, id_mysql,
    A>::RefTcDataIsSet_type_
    query_columns< ::oai::pcf::provisioning::model::PccRuleODB, id_mysql, A>::
        RefTcDataIsSet(A::table_name, "`RefTcDataIsSet`", 0);

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::PccRuleODB, id_mysql,
    A>::RefChgDataIsSet_type_
    query_columns< ::oai::pcf::provisioning::model::PccRuleODB, id_mysql, A>::
        RefChgDataIsSet(A::table_name, "`RefChgDataIsSet`", 0);

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::PccRuleODB, id_mysql,
    A>::RefChgN3gDataIsSet_type_
    query_columns< ::oai::pcf::provisioning::model::PccRuleODB, id_mysql, A>::
        RefChgN3gDataIsSet(A::table_name, "`RefChgN3gDataIsSet`", 0);

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::PccRuleODB, id_mysql,
    A>::RefUmDataIsSet_type_
    query_columns< ::oai::pcf::provisioning::model::PccRuleODB, id_mysql, A>::
        RefUmDataIsSet(A::table_name, "`RefUmDataIsSet`", 0);

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::PccRuleODB, id_mysql,
    A>::RefUmN3gDataIsSet_type_
    query_columns< ::oai::pcf::provisioning::model::PccRuleODB, id_mysql, A>::
        RefUmN3gDataIsSet(A::table_name, "`RefUmN3gDataIsSet`", 0);

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::PccRuleODB, id_mysql, A>::RefCondData_type_
    query_columns< ::oai::pcf::provisioning::model::PccRuleODB, id_mysql, A>::
        RefCondData(A::table_name, "`RefCondData`", 0);

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::PccRuleODB, id_mysql,
    A>::RefCondDataIsSet_type_
    query_columns< ::oai::pcf::provisioning::model::PccRuleODB, id_mysql, A>::
        RefCondDataIsSet(A::table_name, "`RefCondDataIsSet`", 0);

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::PccRuleODB, id_mysql,
    A>::RefQosMonIsSet_type_
    query_columns< ::oai::pcf::provisioning::model::PccRuleODB, id_mysql, A>::
        RefQosMonIsSet(A::table_name, "`RefQosMonIsSet`", 0);

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::PccRuleODB, id_mysql,
    A>::AddrPreserInd_type_
    query_columns< ::oai::pcf::provisioning::model::PccRuleODB, id_mysql, A>::
        AddrPreserInd(A::table_name, "`AddrPreserInd`", 0);

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::PccRuleODB, id_mysql,
    A>::AddrPreserIndIsSet_type_
    query_columns< ::oai::pcf::provisioning::model::PccRuleODB, id_mysql, A>::
        AddrPreserIndIsSet(A::table_name, "`AddrPreserIndIsSet`", 0);

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::PccRuleODB, id_mysql,
    A>::TscaiInputDl_type_
    query_columns< ::oai::pcf::provisioning::model::PccRuleODB, id_mysql, A>::
        TscaiInputDl(A::table_name, "`TscaiInputDl`", 0);

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::PccRuleODB, id_mysql,
    A>::TscaiInputDlIsSet_type_
    query_columns< ::oai::pcf::provisioning::model::PccRuleODB, id_mysql, A>::
        TscaiInputDlIsSet(A::table_name, "`TscaiInputDlIsSet`", 0);

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::PccRuleODB, id_mysql,
    A>::TscaiInputUl_type_
    query_columns< ::oai::pcf::provisioning::model::PccRuleODB, id_mysql, A>::
        TscaiInputUl(A::table_name, "`TscaiInputUl`", 0);

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::PccRuleODB, id_mysql,
    A>::TscaiInputUlIsSet_type_
    query_columns< ::oai::pcf::provisioning::model::PccRuleODB, id_mysql, A>::
        TscaiInputUlIsSet(A::table_name, "`TscaiInputUlIsSet`", 0);

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::PccRuleODB, id_mysql, A>::DdNotifCtrl_type_
    query_columns< ::oai::pcf::provisioning::model::PccRuleODB, id_mysql, A>::
        DdNotifCtrl(A::table_name, "`DdNotifCtrl`", 0);

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::PccRuleODB, id_mysql,
    A>::DdNotifCtrlIsSet_type_
    query_columns< ::oai::pcf::provisioning::model::PccRuleODB, id_mysql, A>::
        DdNotifCtrlIsSet(A::table_name, "`DdNotifCtrlIsSet`", 0);

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::PccRuleODB, id_mysql,
    A>::DdNotifCtrl2_type_
    query_columns< ::oai::pcf::provisioning::model::PccRuleODB, id_mysql, A>::
        DdNotifCtrl2(A::table_name, "`DdNotifCtrl2`", 0);

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::PccRuleODB, id_mysql,
    A>::DdNotifCtrl2IsSet_type_
    query_columns< ::oai::pcf::provisioning::model::PccRuleODB, id_mysql, A>::
        DdNotifCtrl2IsSet(A::table_name, "`DdNotifCtrl2IsSet`", 0);

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::PccRuleODB, id_mysql, A>::DisUeNotif_type_
    query_columns< ::oai::pcf::provisioning::model::PccRuleODB, id_mysql, A>::
        DisUeNotif(A::table_name, "`DisUeNotif`", 0);

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::PccRuleODB, id_mysql,
    A>::DisUeNotifIsSet_type_
    query_columns< ::oai::pcf::provisioning::model::PccRuleODB, id_mysql, A>::
        DisUeNotifIsSet(A::table_name, "`DisUeNotifIsSet`", 0);

template<typename A>
struct pointer_query_columns<
    ::oai::pcf::provisioning::model::PccRuleODB, id_mysql, A>
    : query_columns< ::oai::pcf::provisioning::model::PccRuleODB, id_mysql, A> {
};

template<>
class access::object_traits_impl<
    ::oai::pcf::provisioning::model::PccRuleODB, id_mysql>
    : public access::object_traits<
          ::oai::pcf::provisioning::model::PccRuleODB> {
 public:
  struct id_image_type {
    details::buffer id_value;
    unsigned long id_size;
    my_bool id_null;

    std::size_t version;
  };

  struct image_type {
    // m_FlowInfos
    //
    details::buffer m_FlowInfos_value;
    unsigned long m_FlowInfos_size;
    my_bool m_FlowInfos_null;

    // m_FlowInfosIsSet
    //
    signed char m_FlowInfosIsSet_value;
    my_bool m_FlowInfosIsSet_null;

    // m_AppId
    //
    details::buffer m_AppId_value;
    unsigned long m_AppId_size;
    my_bool m_AppId_null;

    // m_AppIdIsSet
    //
    signed char m_AppIdIsSet_value;
    my_bool m_AppIdIsSet_null;

    // m_AppDescriptor
    //
    details::buffer m_AppDescriptor_value;
    unsigned long m_AppDescriptor_size;
    my_bool m_AppDescriptor_null;

    // m_AppDescriptorIsSet
    //
    signed char m_AppDescriptorIsSet_value;
    my_bool m_AppDescriptorIsSet_null;

    // m_ContVer
    //
    int m_ContVer_value;
    my_bool m_ContVer_null;

    // m_ContVerIsSet
    //
    signed char m_ContVerIsSet_value;
    my_bool m_ContVerIsSet_null;

    // m_PccRuleId
    //
    details::buffer m_PccRuleId_value;
    unsigned long m_PccRuleId_size;
    my_bool m_PccRuleId_null;

    // m_Precedence
    //
    int m_Precedence_value;
    my_bool m_Precedence_null;

    // m_PrecedenceIsSet
    //
    signed char m_PrecedenceIsSet_value;
    my_bool m_PrecedenceIsSet_null;

    // m_AfSigProtocol
    //
    details::buffer m_AfSigProtocol_value;
    unsigned long m_AfSigProtocol_size;
    my_bool m_AfSigProtocol_null;

    // m_AfSigProtocolIsSet
    //
    signed char m_AfSigProtocolIsSet_value;
    my_bool m_AfSigProtocolIsSet_null;

    // m_AppReloc
    //
    signed char m_AppReloc_value;
    my_bool m_AppReloc_null;

    // m_AppRelocIsSet
    //
    signed char m_AppRelocIsSet_value;
    my_bool m_AppRelocIsSet_null;

    // m_RefQosDataIsSet
    //
    signed char m_RefQosDataIsSet_value;
    my_bool m_RefQosDataIsSet_null;

    // m_RefAltQosParamsIsSet
    //
    signed char m_RefAltQosParamsIsSet_value;
    my_bool m_RefAltQosParamsIsSet_null;

    // m_RefTcDataIsSet
    //
    signed char m_RefTcDataIsSet_value;
    my_bool m_RefTcDataIsSet_null;

    // m_RefChgDataIsSet
    //
    signed char m_RefChgDataIsSet_value;
    my_bool m_RefChgDataIsSet_null;

    // m_RefChgN3gDataIsSet
    //
    signed char m_RefChgN3gDataIsSet_value;
    my_bool m_RefChgN3gDataIsSet_null;

    // m_RefUmDataIsSet
    //
    signed char m_RefUmDataIsSet_value;
    my_bool m_RefUmDataIsSet_null;

    // m_RefUmN3gDataIsSet
    //
    signed char m_RefUmN3gDataIsSet_value;
    my_bool m_RefUmN3gDataIsSet_null;

    // m_RefCondData
    //
    details::buffer m_RefCondData_value;
    unsigned long m_RefCondData_size;
    my_bool m_RefCondData_null;

    // m_RefCondDataIsSet
    //
    signed char m_RefCondDataIsSet_value;
    my_bool m_RefCondDataIsSet_null;

    // m_RefQosMonIsSet
    //
    signed char m_RefQosMonIsSet_value;
    my_bool m_RefQosMonIsSet_null;

    // m_AddrPreserInd
    //
    signed char m_AddrPreserInd_value;
    my_bool m_AddrPreserInd_null;

    // m_AddrPreserIndIsSet
    //
    signed char m_AddrPreserIndIsSet_value;
    my_bool m_AddrPreserIndIsSet_null;

    // m_TscaiInputDl
    //
    details::buffer m_TscaiInputDl_value;
    unsigned long m_TscaiInputDl_size;
    my_bool m_TscaiInputDl_null;

    // m_TscaiInputDlIsSet
    //
    signed char m_TscaiInputDlIsSet_value;
    my_bool m_TscaiInputDlIsSet_null;

    // m_TscaiInputUl
    //
    details::buffer m_TscaiInputUl_value;
    unsigned long m_TscaiInputUl_size;
    my_bool m_TscaiInputUl_null;

    // m_TscaiInputUlIsSet
    //
    signed char m_TscaiInputUlIsSet_value;
    my_bool m_TscaiInputUlIsSet_null;

    // m_DdNotifCtrl
    //
    details::buffer m_DdNotifCtrl_value;
    unsigned long m_DdNotifCtrl_size;
    my_bool m_DdNotifCtrl_null;

    // m_DdNotifCtrlIsSet
    //
    signed char m_DdNotifCtrlIsSet_value;
    my_bool m_DdNotifCtrlIsSet_null;

    // m_DdNotifCtrl2
    //
    details::buffer m_DdNotifCtrl2_value;
    unsigned long m_DdNotifCtrl2_size;
    my_bool m_DdNotifCtrl2_null;

    // m_DdNotifCtrl2IsSet
    //
    signed char m_DdNotifCtrl2IsSet_value;
    my_bool m_DdNotifCtrl2IsSet_null;

    // m_DisUeNotif
    //
    signed char m_DisUeNotif_value;
    my_bool m_DisUeNotif_null;

    // m_DisUeNotifIsSet
    //
    signed char m_DisUeNotifIsSet_value;
    my_bool m_DisUeNotifIsSet_null;

    std::size_t version;
  };

  struct extra_statement_cache_type;

  // m_RefQosData
  //
  struct RefQosData_traits {
    static const std::size_t id_column_count   = 1UL;
    static const std::size_t data_column_count = 3UL;

    static const bool versioned = false;

    static const char insert_statement[];
    static const char select_statement[];
    static const char delete_statement[];

    typedef ::std::vector< ::std::basic_string<char> > container_type;
    typedef odb::access::container_traits<container_type> container_traits_type;
    typedef container_traits_type::index_type index_type;
    typedef container_traits_type::value_type value_type;

    typedef ordered_functions<index_type, value_type> functions_type;
    typedef mysql::container_statements<RefQosData_traits> statements_type;

    struct data_image_type {
      // index
      //
      unsigned long long index_value;
      my_bool index_null;

      // value
      //
      details::buffer value_value;
      unsigned long value_size;
      my_bool value_null;

      std::size_t version;
    };

    static void bind(
        MYSQL_BIND*, const MYSQL_BIND* id, std::size_t id_size,
        data_image_type&);

    static void grow(data_image_type&, my_bool*);

    static void init(data_image_type&, index_type*, const value_type&);

    static void init(
        index_type&, value_type&, const data_image_type&, database*);

    static void insert(index_type, const value_type&, void*);

    static bool select(index_type&, value_type&, void*);

    static void delete_(void*);

    static void persist(const container_type&, statements_type&);

    static void load(container_type&, statements_type&);

    static void update(const container_type&, statements_type&);

    static void erase(statements_type&);
  };

  // m_RefAltQosParams
  //
  struct RefAltQosParams_traits {
    static const std::size_t id_column_count   = 1UL;
    static const std::size_t data_column_count = 3UL;

    static const bool versioned = false;

    static const char insert_statement[];
    static const char select_statement[];
    static const char delete_statement[];

    typedef ::std::vector< ::std::basic_string<char> > container_type;
    typedef odb::access::container_traits<container_type> container_traits_type;
    typedef container_traits_type::index_type index_type;
    typedef container_traits_type::value_type value_type;

    typedef ordered_functions<index_type, value_type> functions_type;
    typedef mysql::container_statements<RefAltQosParams_traits> statements_type;

    struct data_image_type {
      // index
      //
      unsigned long long index_value;
      my_bool index_null;

      // value
      //
      details::buffer value_value;
      unsigned long value_size;
      my_bool value_null;

      std::size_t version;
    };

    static void bind(
        MYSQL_BIND*, const MYSQL_BIND* id, std::size_t id_size,
        data_image_type&);

    static void grow(data_image_type&, my_bool*);

    static void init(data_image_type&, index_type*, const value_type&);

    static void init(
        index_type&, value_type&, const data_image_type&, database*);

    static void insert(index_type, const value_type&, void*);

    static bool select(index_type&, value_type&, void*);

    static void delete_(void*);

    static void persist(const container_type&, statements_type&);

    static void load(container_type&, statements_type&);

    static void update(const container_type&, statements_type&);

    static void erase(statements_type&);
  };

  // m_RefTcData
  //
  struct RefTcData_traits {
    static const std::size_t id_column_count   = 1UL;
    static const std::size_t data_column_count = 3UL;

    static const bool versioned = false;

    static const char insert_statement[];
    static const char select_statement[];
    static const char delete_statement[];

    typedef ::std::vector< ::std::basic_string<char> > container_type;
    typedef odb::access::container_traits<container_type> container_traits_type;
    typedef container_traits_type::index_type index_type;
    typedef container_traits_type::value_type value_type;

    typedef ordered_functions<index_type, value_type> functions_type;
    typedef mysql::container_statements<RefTcData_traits> statements_type;

    struct data_image_type {
      // index
      //
      unsigned long long index_value;
      my_bool index_null;

      // value
      //
      details::buffer value_value;
      unsigned long value_size;
      my_bool value_null;

      std::size_t version;
    };

    static void bind(
        MYSQL_BIND*, const MYSQL_BIND* id, std::size_t id_size,
        data_image_type&);

    static void grow(data_image_type&, my_bool*);

    static void init(data_image_type&, index_type*, const value_type&);

    static void init(
        index_type&, value_type&, const data_image_type&, database*);

    static void insert(index_type, const value_type&, void*);

    static bool select(index_type&, value_type&, void*);

    static void delete_(void*);

    static void persist(const container_type&, statements_type&);

    static void load(container_type&, statements_type&);

    static void update(const container_type&, statements_type&);

    static void erase(statements_type&);
  };

  // m_RefChgData
  //
  struct RefChgData_traits {
    static const std::size_t id_column_count   = 1UL;
    static const std::size_t data_column_count = 3UL;

    static const bool versioned = false;

    static const char insert_statement[];
    static const char select_statement[];
    static const char delete_statement[];

    typedef ::std::vector< ::std::basic_string<char> > container_type;
    typedef odb::access::container_traits<container_type> container_traits_type;
    typedef container_traits_type::index_type index_type;
    typedef container_traits_type::value_type value_type;

    typedef ordered_functions<index_type, value_type> functions_type;
    typedef mysql::container_statements<RefChgData_traits> statements_type;

    struct data_image_type {
      // index
      //
      unsigned long long index_value;
      my_bool index_null;

      // value
      //
      details::buffer value_value;
      unsigned long value_size;
      my_bool value_null;

      std::size_t version;
    };

    static void bind(
        MYSQL_BIND*, const MYSQL_BIND* id, std::size_t id_size,
        data_image_type&);

    static void grow(data_image_type&, my_bool*);

    static void init(data_image_type&, index_type*, const value_type&);

    static void init(
        index_type&, value_type&, const data_image_type&, database*);

    static void insert(index_type, const value_type&, void*);

    static bool select(index_type&, value_type&, void*);

    static void delete_(void*);

    static void persist(const container_type&, statements_type&);

    static void load(container_type&, statements_type&);

    static void update(const container_type&, statements_type&);

    static void erase(statements_type&);
  };

  // m_RefChgN3gData
  //
  struct RefChgN3gData_traits {
    static const std::size_t id_column_count   = 1UL;
    static const std::size_t data_column_count = 3UL;

    static const bool versioned = false;

    static const char insert_statement[];
    static const char select_statement[];
    static const char delete_statement[];

    typedef ::std::vector< ::std::basic_string<char> > container_type;
    typedef odb::access::container_traits<container_type> container_traits_type;
    typedef container_traits_type::index_type index_type;
    typedef container_traits_type::value_type value_type;

    typedef ordered_functions<index_type, value_type> functions_type;
    typedef mysql::container_statements<RefChgN3gData_traits> statements_type;

    struct data_image_type {
      // index
      //
      unsigned long long index_value;
      my_bool index_null;

      // value
      //
      details::buffer value_value;
      unsigned long value_size;
      my_bool value_null;

      std::size_t version;
    };

    static void bind(
        MYSQL_BIND*, const MYSQL_BIND* id, std::size_t id_size,
        data_image_type&);

    static void grow(data_image_type&, my_bool*);

    static void init(data_image_type&, index_type*, const value_type&);

    static void init(
        index_type&, value_type&, const data_image_type&, database*);

    static void insert(index_type, const value_type&, void*);

    static bool select(index_type&, value_type&, void*);

    static void delete_(void*);

    static void persist(const container_type&, statements_type&);

    static void load(container_type&, statements_type&);

    static void update(const container_type&, statements_type&);

    static void erase(statements_type&);
  };

  // m_RefUmData
  //
  struct RefUmData_traits {
    static const std::size_t id_column_count   = 1UL;
    static const std::size_t data_column_count = 3UL;

    static const bool versioned = false;

    static const char insert_statement[];
    static const char select_statement[];
    static const char delete_statement[];

    typedef ::std::vector< ::std::basic_string<char> > container_type;
    typedef odb::access::container_traits<container_type> container_traits_type;
    typedef container_traits_type::index_type index_type;
    typedef container_traits_type::value_type value_type;

    typedef ordered_functions<index_type, value_type> functions_type;
    typedef mysql::container_statements<RefUmData_traits> statements_type;

    struct data_image_type {
      // index
      //
      unsigned long long index_value;
      my_bool index_null;

      // value
      //
      details::buffer value_value;
      unsigned long value_size;
      my_bool value_null;

      std::size_t version;
    };

    static void bind(
        MYSQL_BIND*, const MYSQL_BIND* id, std::size_t id_size,
        data_image_type&);

    static void grow(data_image_type&, my_bool*);

    static void init(data_image_type&, index_type*, const value_type&);

    static void init(
        index_type&, value_type&, const data_image_type&, database*);

    static void insert(index_type, const value_type&, void*);

    static bool select(index_type&, value_type&, void*);

    static void delete_(void*);

    static void persist(const container_type&, statements_type&);

    static void load(container_type&, statements_type&);

    static void update(const container_type&, statements_type&);

    static void erase(statements_type&);
  };

  // m_RefUmN3gData
  //
  struct RefUmN3gData_traits {
    static const std::size_t id_column_count   = 1UL;
    static const std::size_t data_column_count = 3UL;

    static const bool versioned = false;

    static const char insert_statement[];
    static const char select_statement[];
    static const char delete_statement[];

    typedef ::std::vector< ::std::basic_string<char> > container_type;
    typedef odb::access::container_traits<container_type> container_traits_type;
    typedef container_traits_type::index_type index_type;
    typedef container_traits_type::value_type value_type;

    typedef ordered_functions<index_type, value_type> functions_type;
    typedef mysql::container_statements<RefUmN3gData_traits> statements_type;

    struct data_image_type {
      // index
      //
      unsigned long long index_value;
      my_bool index_null;

      // value
      //
      details::buffer value_value;
      unsigned long value_size;
      my_bool value_null;

      std::size_t version;
    };

    static void bind(
        MYSQL_BIND*, const MYSQL_BIND* id, std::size_t id_size,
        data_image_type&);

    static void grow(data_image_type&, my_bool*);

    static void init(data_image_type&, index_type*, const value_type&);

    static void init(
        index_type&, value_type&, const data_image_type&, database*);

    static void insert(index_type, const value_type&, void*);

    static bool select(index_type&, value_type&, void*);

    static void delete_(void*);

    static void persist(const container_type&, statements_type&);

    static void load(container_type&, statements_type&);

    static void update(const container_type&, statements_type&);

    static void erase(statements_type&);
  };

  // m_RefQosMon
  //
  struct RefQosMon_traits {
    static const std::size_t id_column_count   = 1UL;
    static const std::size_t data_column_count = 3UL;

    static const bool versioned = false;

    static const char insert_statement[];
    static const char select_statement[];
    static const char delete_statement[];

    typedef ::std::vector< ::std::basic_string<char> > container_type;
    typedef odb::access::container_traits<container_type> container_traits_type;
    typedef container_traits_type::index_type index_type;
    typedef container_traits_type::value_type value_type;

    typedef ordered_functions<index_type, value_type> functions_type;
    typedef mysql::container_statements<RefQosMon_traits> statements_type;

    struct data_image_type {
      // index
      //
      unsigned long long index_value;
      my_bool index_null;

      // value
      //
      details::buffer value_value;
      unsigned long value_size;
      my_bool value_null;

      std::size_t version;
    };

    static void bind(
        MYSQL_BIND*, const MYSQL_BIND* id, std::size_t id_size,
        data_image_type&);

    static void grow(data_image_type&, my_bool*);

    static void init(data_image_type&, index_type*, const value_type&);

    static void init(
        index_type&, value_type&, const data_image_type&, database*);

    static void insert(index_type, const value_type&, void*);

    static bool select(index_type&, value_type&, void*);

    static void delete_(void*);

    static void persist(const container_type&, statements_type&);

    static void load(container_type&, statements_type&);

    static void update(const container_type&, statements_type&);

    static void erase(statements_type&);
  };

  using object_traits<object_type>::id;

  static id_type id(const image_type&);

  static bool grow(image_type&, my_bool*);

  static void bind(MYSQL_BIND*, image_type&, mysql::statement_kind);

  static void bind(MYSQL_BIND*, id_image_type&);

  static bool init(image_type&, const object_type&, mysql::statement_kind);

  static void init(object_type&, const image_type&, database*);

  static void init(id_image_type&, const id_type&);

  typedef mysql::object_statements<object_type> statements_type;

  typedef mysql::query_base query_base_type;

  static const std::size_t column_count                    = 37UL;
  static const std::size_t id_column_count                 = 1UL;
  static const std::size_t inverse_column_count            = 0UL;
  static const std::size_t readonly_column_count           = 0UL;
  static const std::size_t managed_optimistic_column_count = 0UL;

  static const std::size_t separate_load_column_count   = 0UL;
  static const std::size_t separate_update_column_count = 0UL;

  static const bool versioned = false;

  static const char persist_statement[];
  static const char find_statement[];
  static const char update_statement[];
  static const char erase_statement[];
  static const char query_statement[];
  static const char erase_query_statement[];

  static const char table_name[];

  static void persist(database&, const object_type&);

  static pointer_type find(database&, const id_type&);

  static bool find(database&, const id_type&, object_type&);

  static bool reload(database&, object_type&);

  static void update(database&, const object_type&);

  static void erase(database&, const id_type&);

  static void erase(database&, const object_type&);

  static result<object_type> query(database&, const query_base_type&);

  static unsigned long long erase_query(database&, const query_base_type&);

 public:
  static bool find_(statements_type&, const id_type*);

  static void load_(statements_type&, object_type&, bool reload);
};

template<>
class access::object_traits_impl<
    ::oai::pcf::provisioning::model::PccRuleODB, id_common>
    : public access::object_traits_impl<
          ::oai::pcf::provisioning::model::PccRuleODB, id_mysql> {};

// PccRuleODB
//
}  // namespace odb

#include "PccRuleODB-odb.ixx"

#include <odb/post.hxx>

#endif  // PCC_RULE_ODB_ODB_HXX
