/**
 * Npcf_SMPolicyControl API
 * Session Management Policy Control Service © 2023, 3GPP Organizational
 * Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.9
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#ifndef PccRuleODB_H_
#define PccRuleODB_H_

#include <string>
#include <vector>
#include <nlohmann/json.hpp>

namespace oai::pcf::provisioning::model {

/// <summary>
///
/// </summary>
#pragma db object
class PccRuleODB {
 public:
  PccRuleODB();
  virtual ~PccRuleODB() = default;

  bool operator==(const PccRuleODB& rhs) const;
  bool operator!=(const PccRuleODB& rhs) const;

  friend void to_json(nlohmann::json& j, const PccRuleODB& o);
  friend void from_json(const nlohmann::json& j, PccRuleODB& o);

  std::string m_FlowInfos;
  bool m_FlowInfosIsSet;
  std::string m_AppId;
  bool m_AppIdIsSet;
  std::string m_AppDescriptor;
  bool m_AppDescriptorIsSet;
  int32_t m_ContVer;
  bool m_ContVerIsSet;
#pragma db id
  std::string m_PccRuleId;

  int32_t m_Precedence;
  bool m_PrecedenceIsSet;
  std::string m_AfSigProtocol;
  bool m_AfSigProtocolIsSet;
  bool m_AppReloc;
  bool m_AppRelocIsSet;
  std::vector<std::string> m_RefQosData;
  bool m_RefQosDataIsSet;
  std::vector<std::string> m_RefAltQosParams;
  bool m_RefAltQosParamsIsSet;
  std::vector<std::string> m_RefTcData;
  bool m_RefTcDataIsSet;
  std::vector<std::string> m_RefChgData;
  bool m_RefChgDataIsSet;
  std::vector<std::string> m_RefChgN3gData;
  bool m_RefChgN3gDataIsSet;
  std::vector<std::string> m_RefUmData;
  bool m_RefUmDataIsSet;
  std::vector<std::string> m_RefUmN3gData;
  bool m_RefUmN3gDataIsSet;
  std::string m_RefCondData;
  bool m_RefCondDataIsSet;
  std::vector<std::string> m_RefQosMon;
  bool m_RefQosMonIsSet;
  bool m_AddrPreserInd;
  bool m_AddrPreserIndIsSet;
  std::string m_TscaiInputDl;
  bool m_TscaiInputDlIsSet;
  std::string m_TscaiInputUl;
  bool m_TscaiInputUlIsSet;
  std::string m_DdNotifCtrl;
  bool m_DdNotifCtrlIsSet;
  std::string m_DdNotifCtrl2;
  bool m_DdNotifCtrl2IsSet;
  bool m_DisUeNotif;
  bool m_DisUeNotifIsSet;
};

}  // namespace oai::pcf::provisioning::model

#endif /* PccRuleODB_H_ */
