/**
 * Npcf_SMPolicyControl API
 * Session Management Policy Control Service © 2023, 3GPP Organizational
 * Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.9
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "PccRuleODB.h"

#include <sstream>

namespace oai::pcf::provisioning::model {

PccRuleODB::PccRuleODB() {
  m_FlowInfosIsSet       = false;
  m_AppId                = "";
  m_AppIdIsSet           = false;
  m_AppDescriptorIsSet   = false;
  m_ContVer              = 0;
  m_ContVerIsSet         = false;
  m_PccRuleId            = "";
  m_Precedence           = 0;
  m_PrecedenceIsSet      = false;
  m_AfSigProtocolIsSet   = false;
  m_AppReloc             = false;
  m_AppRelocIsSet        = false;
  m_RefQosDataIsSet      = false;
  m_RefAltQosParamsIsSet = false;
  m_RefTcDataIsSet       = false;
  m_RefChgDataIsSet      = false;
  m_RefChgN3gDataIsSet   = false;
  m_RefUmDataIsSet       = false;
  m_RefUmN3gDataIsSet    = false;
  m_RefCondData          = "";
  m_RefCondDataIsSet     = false;
  m_RefQosMonIsSet       = false;
  m_AddrPreserInd        = false;
  m_AddrPreserIndIsSet   = false;
  m_TscaiInputDlIsSet    = false;
  m_TscaiInputUlIsSet    = false;
  m_DdNotifCtrlIsSet     = false;
  m_DdNotifCtrl2IsSet    = false;
  m_DisUeNotif           = false;
  m_DisUeNotifIsSet      = false;
}

bool PccRuleODB::operator==(const PccRuleODB& rhs) const {
  (m_PccRuleId == rhs.m_PccRuleId) &&

      ((!m_FlowInfosIsSet && !rhs.m_FlowInfosIsSet) ||
       (m_FlowInfosIsSet && rhs.m_FlowInfosIsSet &&
        m_FlowInfos == rhs.m_FlowInfos)) &&

      ((!m_AppIdIsSet && !rhs.m_AppIdIsSet) ||
       (m_AppIdIsSet && rhs.m_AppIdIsSet && m_AppId == rhs.m_AppId)) &&

      ((!m_AppDescriptorIsSet && !rhs.m_AppDescriptorIsSet) ||
       (m_AppDescriptorIsSet && rhs.m_AppDescriptorIsSet &&
        m_AppDescriptor == rhs.m_AppDescriptor)) &&

      ((!m_ContVerIsSet && !rhs.m_ContVerIsSet) ||
       (m_ContVerIsSet && rhs.m_ContVerIsSet && m_ContVer == rhs.m_ContVer)) &&

      ((!m_PrecedenceIsSet && !rhs.m_PrecedenceIsSet) ||
       (m_PrecedenceIsSet && rhs.m_PrecedenceIsSet &&
        m_Precedence == rhs.m_Precedence)) &&

      ((!m_AfSigProtocolIsSet && !rhs.m_AfSigProtocolIsSet) ||
       (m_AfSigProtocolIsSet && rhs.m_AfSigProtocolIsSet &&
        m_AfSigProtocol == rhs.m_AfSigProtocol)) &&

      ((!m_AppRelocIsSet && !rhs.m_AppRelocIsSet) ||
       (m_AppRelocIsSet && rhs.m_AppRelocIsSet &&
        m_AppReloc == rhs.m_AppReloc)) &&

      ((!m_RefQosDataIsSet && !rhs.m_RefQosDataIsSet) ||
       (m_RefQosDataIsSet && rhs.m_RefQosDataIsSet &&
        m_RefQosData == rhs.m_RefQosData)) &&

      ((!m_RefAltQosParamsIsSet && !rhs.m_RefAltQosParamsIsSet) ||
       (m_RefAltQosParamsIsSet && rhs.m_RefAltQosParamsIsSet &&
        m_RefAltQosParams == rhs.m_RefAltQosParams)) &&

      ((!m_RefTcDataIsSet && !rhs.m_RefTcDataIsSet) ||
       (m_RefTcDataIsSet && rhs.m_RefTcDataIsSet &&
        m_RefTcData == rhs.m_RefTcData)) &&

      ((!m_RefChgDataIsSet && !rhs.m_RefChgDataIsSet) ||
       (m_RefChgDataIsSet && rhs.m_RefChgDataIsSet &&
        m_RefChgData == rhs.m_RefChgData)) &&

      ((!m_RefChgN3gDataIsSet && !rhs.m_RefChgN3gDataIsSet) ||
       (m_RefChgN3gDataIsSet && rhs.m_RefChgN3gDataIsSet &&
        m_RefChgN3gData == rhs.m_RefChgN3gData)) &&

      ((!m_RefUmDataIsSet && !rhs.m_RefUmDataIsSet) ||
       (m_RefUmDataIsSet && rhs.m_RefUmDataIsSet &&
        m_RefUmData == rhs.m_RefUmData)) &&

      ((!m_RefUmN3gDataIsSet && !rhs.m_RefUmN3gDataIsSet) ||
       (m_RefUmN3gDataIsSet && rhs.m_RefUmN3gDataIsSet &&
        m_RefUmN3gData == rhs.m_RefUmN3gData)) &&

      ((!m_RefCondDataIsSet && !rhs.m_RefCondDataIsSet) ||
       (m_RefCondDataIsSet && rhs.m_RefCondDataIsSet &&
        m_RefCondData == rhs.m_RefCondData)) &&

      ((!m_RefQosMonIsSet && !rhs.m_RefQosMonIsSet) ||
       (m_RefQosMonIsSet && rhs.m_RefQosMonIsSet &&
        m_RefQosMon == rhs.m_RefQosMon)) &&

      ((!m_AddrPreserIndIsSet && !rhs.m_AddrPreserIndIsSet) ||
       (m_AddrPreserIndIsSet && rhs.m_AddrPreserIndIsSet &&
        m_AddrPreserInd == rhs.m_AddrPreserInd)) &&

      ((!m_TscaiInputDlIsSet && !rhs.m_TscaiInputDlIsSet) ||
       (m_TscaiInputDlIsSet && rhs.m_TscaiInputDlIsSet &&
        m_TscaiInputDl == rhs.m_TscaiInputDl)) &&

      ((!m_TscaiInputUlIsSet && !rhs.m_TscaiInputUlIsSet) ||
       (m_TscaiInputUlIsSet && rhs.m_TscaiInputUlIsSet &&
        m_TscaiInputUl == rhs.m_TscaiInputUl)) &&

      ((!m_DdNotifCtrlIsSet && !rhs.m_DdNotifCtrlIsSet) ||
       (m_DdNotifCtrlIsSet && rhs.m_DdNotifCtrlIsSet &&
        m_DdNotifCtrl == rhs.m_DdNotifCtrl)) &&

      ((!m_DdNotifCtrl2IsSet && !rhs.m_DdNotifCtrl2IsSet) ||
       (m_DdNotifCtrl2IsSet && rhs.m_DdNotifCtrl2IsSet &&
        m_DdNotifCtrl2 == rhs.m_DdNotifCtrl2)) &&

      ((!m_DisUeNotifIsSet && !rhs.m_DisUeNotifIsSet) ||
       (m_DisUeNotifIsSet && rhs.m_DisUeNotifIsSet &&
        m_DisUeNotif == rhs.m_DisUeNotif))

      ;
}

bool PccRuleODB::operator!=(const PccRuleODB& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const PccRuleODB& o) {
  j = nlohmann::json();
  if (o.m_FlowInfosIsSet) j["flowInfos"] = nlohmann::json::parse(o.m_FlowInfos);
  if (o.m_AppIdIsSet) j["appId"] = o.m_AppId;
  if (o.m_AppDescriptorIsSet) j["appDescriptor"] = o.m_AppDescriptor;
  if (o.m_ContVerIsSet) j["contVer"] = o.m_ContVer;
  j["pccRuleId"] = o.m_PccRuleId;
  if (o.m_PrecedenceIsSet) j["precedence"] = o.m_Precedence;
  if (o.m_AfSigProtocolIsSet)
    j["afSigProtocol"] = nlohmann::json::parse(o.m_AfSigProtocol);
  if (o.m_AppRelocIsSet) j["appReloc"] = o.m_AppReloc;
  if (o.m_RefQosDataIsSet || !o.m_RefQosData.empty())
    j["refQosData"] = o.m_RefQosData;
  if (o.m_RefAltQosParamsIsSet || !o.m_RefAltQosParams.empty())
    j["refAltQosParams"] = o.m_RefAltQosParams;
  if (o.m_RefTcDataIsSet || !o.m_RefTcData.empty())
    j["refTcData"] = o.m_RefTcData;
  if (o.m_RefChgDataIsSet || !o.m_RefChgData.empty())
    j["refChgData"] = o.m_RefChgData;
  if (o.m_RefChgN3gDataIsSet || !o.m_RefChgN3gData.empty())
    j["refChgN3gData"] = o.m_RefChgN3gData;
  if (o.m_RefUmDataIsSet || !o.m_RefUmData.empty())
    j["refUmData"] = o.m_RefUmData;
  if (o.m_RefUmN3gDataIsSet || !o.m_RefUmN3gData.empty())
    j["refUmN3gData"] = o.m_RefUmN3gData;
  if (o.m_RefCondDataIsSet) j["refCondData"] = o.m_RefCondData;
  if (o.m_RefQosMonIsSet || !o.m_RefQosMon.empty())
    j["refQosMon"] = o.m_RefQosMon;
  if (o.m_AddrPreserIndIsSet) j["addrPreserInd"] = o.m_AddrPreserInd;
  if (o.m_TscaiInputDlIsSet)
    j["tscaiInputDl"] = nlohmann::json::parse(o.m_TscaiInputDl);
  if (o.m_TscaiInputUlIsSet)
    j["tscaiInputUl"] = nlohmann::json::parse(o.m_TscaiInputUl);
  if (o.m_DdNotifCtrlIsSet)
    j["ddNotifCtrl"] = nlohmann::json::parse(o.m_DdNotifCtrl);
  if (o.m_DdNotifCtrl2IsSet)
    j["ddNotifCtrl2"] = nlohmann::json::parse(o.m_DdNotifCtrl2);
  if (o.m_DisUeNotifIsSet) j["disUeNotif"] = o.m_DisUeNotif;
}

void from_json(const nlohmann::json& j, PccRuleODB& o) {
  if (j.find("flowInfos") != j.end()) {
    o.m_FlowInfos      = j.at("flowInfos").dump();
    o.m_FlowInfosIsSet = true;
  }
  if (j.find("appId") != j.end()) {
    j.at("appId").get_to(o.m_AppId);
    o.m_AppIdIsSet = true;
  }
  if (j.find("appDescriptor") != j.end()) {
    j.at("appDescriptor").get_to(o.m_AppDescriptor);
    o.m_AppDescriptorIsSet = true;
  }
  if (j.find("contVer") != j.end()) {
    j.at("contVer").get_to(o.m_ContVer);
    o.m_ContVerIsSet = true;
  }
  if (j.find("pccRuleId") != j.end()) {
    j.at("pccRuleId").get_to(o.m_PccRuleId);
  }
  if (j.find("precedence") != j.end()) {
    j.at("precedence").get_to(o.m_Precedence);
    o.m_PrecedenceIsSet = true;
  }
  if (j.find("afSigProtocol") != j.end()) {
    o.m_AfSigProtocol      = j.at("afSigProtocol").dump();
    o.m_AfSigProtocolIsSet = true;
  }
  if (j.find("appReloc") != j.end()) {
    j.at("appReloc").get_to(o.m_AppReloc);
    o.m_AppRelocIsSet = true;
  }
  if (j.find("refQosData") != j.end()) {
    j.at("refQosData").get_to(o.m_RefQosData);
    o.m_RefQosDataIsSet = true;
  }
  if (j.find("refAltQosParams") != j.end()) {
    j.at("refAltQosParams").get_to(o.m_RefAltQosParams);
    o.m_RefAltQosParamsIsSet = true;
  }
  if (j.find("refTcData") != j.end()) {
    j.at("refTcData").get_to(o.m_RefTcData);
    o.m_RefTcDataIsSet = true;
  }
  if (j.find("refChgData") != j.end()) {
    j.at("refChgData").get_to(o.m_RefChgData);
    o.m_RefChgDataIsSet = true;
  }
  if (j.find("refChgN3gData") != j.end()) {
    j.at("refChgN3gData").get_to(o.m_RefChgN3gData);
    o.m_RefChgN3gDataIsSet = true;
  }
  if (j.find("refUmData") != j.end()) {
    j.at("refUmData").get_to(o.m_RefUmData);
    o.m_RefUmDataIsSet = true;
  }
  if (j.find("refUmN3gData") != j.end()) {
    j.at("refUmN3gData").get_to(o.m_RefUmN3gData);
    o.m_RefUmN3gDataIsSet = true;
  }
  if (j.find("refCondData") != j.end()) {
    j.at("refCondData").get_to(o.m_RefCondData);
    o.m_RefCondDataIsSet = true;
  }
  if (j.find("refQosMon") != j.end()) {
    j.at("refQosMon").get_to(o.m_RefQosMon);
    o.m_RefQosMonIsSet = true;
  }
  if (j.find("addrPreserInd") != j.end()) {
    j.at("addrPreserInd").get_to(o.m_AddrPreserInd);
    o.m_AddrPreserIndIsSet = true;
  }
  if (j.find("tscaiInputDl") != j.end()) {
    o.m_TscaiInputDl      = j.at("tscaiInputDl").dump();
    o.m_TscaiInputDlIsSet = true;
  }
  if (j.find("tscaiInputUl") != j.end()) {
    o.m_TscaiInputUl      = j.at("tscaiInputUl").dump();
    o.m_TscaiInputUlIsSet = true;
  }
  if (j.find("ddNotifCtrl") != j.end()) {
    o.m_DdNotifCtrl      = j.at("ddNotifCtrl").dump();
    o.m_DdNotifCtrlIsSet = true;
  }
  if (j.find("ddNotifCtrl2") != j.end()) {
    o.m_DdNotifCtrl2      = j.at("ddNotifCtrl2").dump();
    o.m_DdNotifCtrl2IsSet = true;
  }
  if (j.find("disUeNotif") != j.end()) {
    j.at("disUeNotif").get_to(o.m_DisUeNotif);
    o.m_DisUeNotifIsSet = true;
  }
}

}  // namespace oai::pcf::provisioning::model
