// -*- C++ -*-
//
// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#include "PreemptionCapability-odb.hxx"

#include <cassert>
#include <cstring>  // std::memcpy

#include <odb/mysql/traits.hxx>
#include <odb/mysql/database.hxx>
#include <odb/mysql/transaction.hxx>
#include <odb/mysql/connection.hxx>
#include <odb/mysql/statement.hxx>
#include <odb/mysql/statement-cache.hxx>
#include <odb/mysql/container-statements.hxx>
#include <odb/mysql/exceptions.hxx>
#include <odb/mysql/enum.hxx>

namespace odb {
// PreemptionCapability
//

bool access::composite_value_traits<
    ::oai::model::common::PreemptionCapability,
    id_mysql>::grow(image_type& i, my_bool* t) {
  ODB_POTENTIALLY_UNUSED(i);
  ODB_POTENTIALLY_UNUSED(t);

  bool grew(false);

  // m_value
  //
  if (composite_value_traits<
          ::oai::model::common::PreemptionCapability_anyOf,
          id_mysql>::grow(i.m_value_value, t + 0UL))
    grew = true;

  return grew;
}

void access::composite_value_traits<
    ::oai::model::common::PreemptionCapability,
    id_mysql>::bind(MYSQL_BIND* b, image_type& i, mysql::statement_kind sk) {
  ODB_POTENTIALLY_UNUSED(b);
  ODB_POTENTIALLY_UNUSED(i);
  ODB_POTENTIALLY_UNUSED(sk);

  using namespace mysql;

  std::size_t n(0);
  ODB_POTENTIALLY_UNUSED(n);

  // m_value
  //
  composite_value_traits<
      ::oai::model::common::PreemptionCapability_anyOf,
      id_mysql>::bind(b + n, i.m_value_value, sk);
  n += 1UL;
}

bool access::composite_value_traits<
    ::oai::model::common::PreemptionCapability, id_mysql>::
    init(image_type& i, const value_type& o, mysql::statement_kind sk) {
  ODB_POTENTIALLY_UNUSED(i);
  ODB_POTENTIALLY_UNUSED(o);
  ODB_POTENTIALLY_UNUSED(sk);

  using namespace mysql;

  bool grew(false);

  // m_value
  //
  {
    ::oai::model::common::PreemptionCapability_anyOf const& v = o.m_value;

    if (composite_value_traits<
            ::oai::model::common::PreemptionCapability_anyOf,
            id_mysql>::init(i.m_value_value, v, sk))
      grew = true;
  }

  return grew;
}

void access::composite_value_traits<
    ::oai::model::common::PreemptionCapability,
    id_mysql>::init(value_type& o, const image_type& i, database* db) {
  ODB_POTENTIALLY_UNUSED(o);
  ODB_POTENTIALLY_UNUSED(i);
  ODB_POTENTIALLY_UNUSED(db);

  // m_value
  //
  {
    ::oai::model::common::PreemptionCapability_anyOf& v = o.m_value;

    composite_value_traits<
        ::oai::model::common::PreemptionCapability_anyOf,
        id_mysql>::init(v, i.m_value_value, db);
  }
}
}  // namespace odb

#include <odb/post.hxx>
