// -*- C++ -*-
//
// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#include "QosData-odb.hxx"

#include <cassert>
#include <cstring>  // std::memcpy

#include <odb/mysql/traits.hxx>
#include <odb/mysql/database.hxx>
#include <odb/mysql/transaction.hxx>
#include <odb/mysql/connection.hxx>
#include <odb/mysql/statement.hxx>
#include <odb/mysql/statement-cache.hxx>
#include <odb/mysql/simple-object-statements.hxx>
#include <odb/mysql/container-statements.hxx>
#include <odb/mysql/exceptions.hxx>
#include <odb/mysql/simple-object-result.hxx>
#include <odb/mysql/enum.hxx>

namespace odb {
// QosData
//

struct access::object_traits_impl<
    ::oai::model::pcf::QosData, id_mysql>::extra_statement_cache_type {
  extra_statement_cache_type(
      mysql::connection&, image_type&, id_image_type&, mysql::binding&,
      mysql::binding&) {}
};

access::object_traits_impl< ::oai::model::pcf::QosData, id_mysql>::id_type
access::object_traits_impl< ::oai::model::pcf::QosData, id_mysql>::id(
    const image_type& i) {
  mysql::database* db(0);
  ODB_POTENTIALLY_UNUSED(db);

  id_type id;
  {
    mysql::value_traits< ::std::string, mysql::id_string>::set_value(
        id, i.m_QosId_value, i.m_QosId_size, i.m_QosId_null);
  }

  return id;
}

bool access::object_traits_impl< ::oai::model::pcf::QosData, id_mysql>::grow(
    image_type& i, my_bool* t) {
  ODB_POTENTIALLY_UNUSED(i);
  ODB_POTENTIALLY_UNUSED(t);

  bool grew(false);

  // m_QosId
  //
  if (t[0UL]) {
    i.m_QosId_value.capacity(i.m_QosId_size);
    grew = true;
  }

  // m_r_5qi
  //
  t[1UL] = 0;

  // m_r_5qiIsSet
  //
  t[2UL] = 0;

  // m_MaxbrUl
  //
  if (t[3UL]) {
    i.m_MaxbrUl_value.capacity(i.m_MaxbrUl_size);
    grew = true;
  }

  // m_MaxbrUlIsSet
  //
  t[4UL] = 0;

  // m_MaxbrDl
  //
  if (t[5UL]) {
    i.m_MaxbrDl_value.capacity(i.m_MaxbrDl_size);
    grew = true;
  }

  // m_MaxbrDlIsSet
  //
  t[6UL] = 0;

  // m_GbrUl
  //
  if (t[7UL]) {
    i.m_GbrUl_value.capacity(i.m_GbrUl_size);
    grew = true;
  }

  // m_GbrUlIsSet
  //
  t[8UL] = 0;

  // m_GbrDl
  //
  if (t[9UL]) {
    i.m_GbrDl_value.capacity(i.m_GbrDl_size);
    grew = true;
  }

  // m_GbrDlIsSet
  //
  t[10UL] = 0;

  // m_Arp
  //
  if (composite_value_traits< ::oai::model::common::Arp, id_mysql>::grow(
          i.m_Arp_value, t + 11UL))
    grew = true;

  // m_ArpIsSet
  //
  t[14UL] = 0;

  // m_Qnc
  //
  t[15UL] = 0;

  // m_QncIsSet
  //
  t[16UL] = 0;

  // m_PriorityLevel
  //
  t[17UL] = 0;

  // m_PriorityLevelIsSet
  //
  t[18UL] = 0;

  // m_AverWindow
  //
  t[19UL] = 0;

  // m_AverWindowIsSet
  //
  t[20UL] = 0;

  // m_MaxDataBurstVol
  //
  t[21UL] = 0;

  // m_MaxDataBurstVolIsSet
  //
  t[22UL] = 0;

  // m_ReflectiveQos
  //
  t[23UL] = 0;

  // m_ReflectiveQosIsSet
  //
  t[24UL] = 0;

  // m_SharingKeyDl
  //
  if (t[25UL]) {
    i.m_SharingKeyDl_value.capacity(i.m_SharingKeyDl_size);
    grew = true;
  }

  // m_SharingKeyDlIsSet
  //
  t[26UL] = 0;

  // m_SharingKeyUl
  //
  if (t[27UL]) {
    i.m_SharingKeyUl_value.capacity(i.m_SharingKeyUl_size);
    grew = true;
  }

  // m_SharingKeyUlIsSet
  //
  t[28UL] = 0;

  // m_MaxPacketLossRateDl
  //
  t[29UL] = 0;

  // m_MaxPacketLossRateDlIsSet
  //
  t[30UL] = 0;

  // m_MaxPacketLossRateUl
  //
  t[31UL] = 0;

  // m_MaxPacketLossRateUlIsSet
  //
  t[32UL] = 0;

  // m_DefQosFlowIndication
  //
  t[33UL] = 0;

  // m_DefQosFlowIndicationIsSet
  //
  t[34UL] = 0;

  // m_ExtMaxDataBurstVol
  //
  t[35UL] = 0;

  // m_ExtMaxDataBurstVolIsSet
  //
  t[36UL] = 0;

  // m_PacketDelayBudget
  //
  t[37UL] = 0;

  // m_PacketDelayBudgetIsSet
  //
  t[38UL] = 0;

  // m_PacketErrorRate
  //
  if (t[39UL]) {
    i.m_PacketErrorRate_value.capacity(i.m_PacketErrorRate_size);
    grew = true;
  }

  // m_PacketErrorRateIsSet
  //
  t[40UL] = 0;

  return grew;
}

void access::object_traits_impl< ::oai::model::pcf::QosData, id_mysql>::bind(
    MYSQL_BIND* b, image_type& i, mysql::statement_kind sk) {
  ODB_POTENTIALLY_UNUSED(sk);

  using namespace mysql;

  std::size_t n(0);

  // m_QosId
  //
  if (sk != statement_update) {
    b[n].buffer_type   = MYSQL_TYPE_STRING;
    b[n].buffer        = i.m_QosId_value.data();
    b[n].buffer_length = static_cast<unsigned long>(i.m_QosId_value.capacity());
    b[n].length        = &i.m_QosId_size;
    b[n].is_null       = &i.m_QosId_null;
    n++;
  }

  // m_r_5qi
  //
  b[n].buffer_type = MYSQL_TYPE_LONG;
  b[n].is_unsigned = 0;
  b[n].buffer      = &i.m_r_5qi_value;
  b[n].is_null     = &i.m_r_5qi_null;
  n++;

  // m_r_5qiIsSet
  //
  b[n].buffer_type = MYSQL_TYPE_TINY;
  b[n].is_unsigned = 0;
  b[n].buffer      = &i.m_r_5qiIsSet_value;
  b[n].is_null     = &i.m_r_5qiIsSet_null;
  n++;

  // m_MaxbrUl
  //
  b[n].buffer_type   = MYSQL_TYPE_STRING;
  b[n].buffer        = i.m_MaxbrUl_value.data();
  b[n].buffer_length = static_cast<unsigned long>(i.m_MaxbrUl_value.capacity());
  b[n].length        = &i.m_MaxbrUl_size;
  b[n].is_null       = &i.m_MaxbrUl_null;
  n++;

  // m_MaxbrUlIsSet
  //
  b[n].buffer_type = MYSQL_TYPE_TINY;
  b[n].is_unsigned = 0;
  b[n].buffer      = &i.m_MaxbrUlIsSet_value;
  b[n].is_null     = &i.m_MaxbrUlIsSet_null;
  n++;

  // m_MaxbrDl
  //
  b[n].buffer_type   = MYSQL_TYPE_STRING;
  b[n].buffer        = i.m_MaxbrDl_value.data();
  b[n].buffer_length = static_cast<unsigned long>(i.m_MaxbrDl_value.capacity());
  b[n].length        = &i.m_MaxbrDl_size;
  b[n].is_null       = &i.m_MaxbrDl_null;
  n++;

  // m_MaxbrDlIsSet
  //
  b[n].buffer_type = MYSQL_TYPE_TINY;
  b[n].is_unsigned = 0;
  b[n].buffer      = &i.m_MaxbrDlIsSet_value;
  b[n].is_null     = &i.m_MaxbrDlIsSet_null;
  n++;

  // m_GbrUl
  //
  b[n].buffer_type   = MYSQL_TYPE_STRING;
  b[n].buffer        = i.m_GbrUl_value.data();
  b[n].buffer_length = static_cast<unsigned long>(i.m_GbrUl_value.capacity());
  b[n].length        = &i.m_GbrUl_size;
  b[n].is_null       = &i.m_GbrUl_null;
  n++;

  // m_GbrUlIsSet
  //
  b[n].buffer_type = MYSQL_TYPE_TINY;
  b[n].is_unsigned = 0;
  b[n].buffer      = &i.m_GbrUlIsSet_value;
  b[n].is_null     = &i.m_GbrUlIsSet_null;
  n++;

  // m_GbrDl
  //
  b[n].buffer_type   = MYSQL_TYPE_STRING;
  b[n].buffer        = i.m_GbrDl_value.data();
  b[n].buffer_length = static_cast<unsigned long>(i.m_GbrDl_value.capacity());
  b[n].length        = &i.m_GbrDl_size;
  b[n].is_null       = &i.m_GbrDl_null;
  n++;

  // m_GbrDlIsSet
  //
  b[n].buffer_type = MYSQL_TYPE_TINY;
  b[n].is_unsigned = 0;
  b[n].buffer      = &i.m_GbrDlIsSet_value;
  b[n].is_null     = &i.m_GbrDlIsSet_null;
  n++;

  // m_Arp
  //
  composite_value_traits< ::oai::model::common::Arp, id_mysql>::bind(
      b + n, i.m_Arp_value, sk);
  n += 3UL;

  // m_ArpIsSet
  //
  b[n].buffer_type = MYSQL_TYPE_TINY;
  b[n].is_unsigned = 0;
  b[n].buffer      = &i.m_ArpIsSet_value;
  b[n].is_null     = &i.m_ArpIsSet_null;
  n++;

  // m_Qnc
  //
  b[n].buffer_type = MYSQL_TYPE_TINY;
  b[n].is_unsigned = 0;
  b[n].buffer      = &i.m_Qnc_value;
  b[n].is_null     = &i.m_Qnc_null;
  n++;

  // m_QncIsSet
  //
  b[n].buffer_type = MYSQL_TYPE_TINY;
  b[n].is_unsigned = 0;
  b[n].buffer      = &i.m_QncIsSet_value;
  b[n].is_null     = &i.m_QncIsSet_null;
  n++;

  // m_PriorityLevel
  //
  b[n].buffer_type = MYSQL_TYPE_LONG;
  b[n].is_unsigned = 0;
  b[n].buffer      = &i.m_PriorityLevel_value;
  b[n].is_null     = &i.m_PriorityLevel_null;
  n++;

  // m_PriorityLevelIsSet
  //
  b[n].buffer_type = MYSQL_TYPE_TINY;
  b[n].is_unsigned = 0;
  b[n].buffer      = &i.m_PriorityLevelIsSet_value;
  b[n].is_null     = &i.m_PriorityLevelIsSet_null;
  n++;

  // m_AverWindow
  //
  b[n].buffer_type = MYSQL_TYPE_LONG;
  b[n].is_unsigned = 0;
  b[n].buffer      = &i.m_AverWindow_value;
  b[n].is_null     = &i.m_AverWindow_null;
  n++;

  // m_AverWindowIsSet
  //
  b[n].buffer_type = MYSQL_TYPE_TINY;
  b[n].is_unsigned = 0;
  b[n].buffer      = &i.m_AverWindowIsSet_value;
  b[n].is_null     = &i.m_AverWindowIsSet_null;
  n++;

  // m_MaxDataBurstVol
  //
  b[n].buffer_type = MYSQL_TYPE_LONG;
  b[n].is_unsigned = 0;
  b[n].buffer      = &i.m_MaxDataBurstVol_value;
  b[n].is_null     = &i.m_MaxDataBurstVol_null;
  n++;

  // m_MaxDataBurstVolIsSet
  //
  b[n].buffer_type = MYSQL_TYPE_TINY;
  b[n].is_unsigned = 0;
  b[n].buffer      = &i.m_MaxDataBurstVolIsSet_value;
  b[n].is_null     = &i.m_MaxDataBurstVolIsSet_null;
  n++;

  // m_ReflectiveQos
  //
  b[n].buffer_type = MYSQL_TYPE_TINY;
  b[n].is_unsigned = 0;
  b[n].buffer      = &i.m_ReflectiveQos_value;
  b[n].is_null     = &i.m_ReflectiveQos_null;
  n++;

  // m_ReflectiveQosIsSet
  //
  b[n].buffer_type = MYSQL_TYPE_TINY;
  b[n].is_unsigned = 0;
  b[n].buffer      = &i.m_ReflectiveQosIsSet_value;
  b[n].is_null     = &i.m_ReflectiveQosIsSet_null;
  n++;

  // m_SharingKeyDl
  //
  b[n].buffer_type = MYSQL_TYPE_STRING;
  b[n].buffer      = i.m_SharingKeyDl_value.data();
  b[n].buffer_length =
      static_cast<unsigned long>(i.m_SharingKeyDl_value.capacity());
  b[n].length  = &i.m_SharingKeyDl_size;
  b[n].is_null = &i.m_SharingKeyDl_null;
  n++;

  // m_SharingKeyDlIsSet
  //
  b[n].buffer_type = MYSQL_TYPE_TINY;
  b[n].is_unsigned = 0;
  b[n].buffer      = &i.m_SharingKeyDlIsSet_value;
  b[n].is_null     = &i.m_SharingKeyDlIsSet_null;
  n++;

  // m_SharingKeyUl
  //
  b[n].buffer_type = MYSQL_TYPE_STRING;
  b[n].buffer      = i.m_SharingKeyUl_value.data();
  b[n].buffer_length =
      static_cast<unsigned long>(i.m_SharingKeyUl_value.capacity());
  b[n].length  = &i.m_SharingKeyUl_size;
  b[n].is_null = &i.m_SharingKeyUl_null;
  n++;

  // m_SharingKeyUlIsSet
  //
  b[n].buffer_type = MYSQL_TYPE_TINY;
  b[n].is_unsigned = 0;
  b[n].buffer      = &i.m_SharingKeyUlIsSet_value;
  b[n].is_null     = &i.m_SharingKeyUlIsSet_null;
  n++;

  // m_MaxPacketLossRateDl
  //
  b[n].buffer_type = MYSQL_TYPE_LONG;
  b[n].is_unsigned = 0;
  b[n].buffer      = &i.m_MaxPacketLossRateDl_value;
  b[n].is_null     = &i.m_MaxPacketLossRateDl_null;
  n++;

  // m_MaxPacketLossRateDlIsSet
  //
  b[n].buffer_type = MYSQL_TYPE_TINY;
  b[n].is_unsigned = 0;
  b[n].buffer      = &i.m_MaxPacketLossRateDlIsSet_value;
  b[n].is_null     = &i.m_MaxPacketLossRateDlIsSet_null;
  n++;

  // m_MaxPacketLossRateUl
  //
  b[n].buffer_type = MYSQL_TYPE_LONG;
  b[n].is_unsigned = 0;
  b[n].buffer      = &i.m_MaxPacketLossRateUl_value;
  b[n].is_null     = &i.m_MaxPacketLossRateUl_null;
  n++;

  // m_MaxPacketLossRateUlIsSet
  //
  b[n].buffer_type = MYSQL_TYPE_TINY;
  b[n].is_unsigned = 0;
  b[n].buffer      = &i.m_MaxPacketLossRateUlIsSet_value;
  b[n].is_null     = &i.m_MaxPacketLossRateUlIsSet_null;
  n++;

  // m_DefQosFlowIndication
  //
  b[n].buffer_type = MYSQL_TYPE_TINY;
  b[n].is_unsigned = 0;
  b[n].buffer      = &i.m_DefQosFlowIndication_value;
  b[n].is_null     = &i.m_DefQosFlowIndication_null;
  n++;

  // m_DefQosFlowIndicationIsSet
  //
  b[n].buffer_type = MYSQL_TYPE_TINY;
  b[n].is_unsigned = 0;
  b[n].buffer      = &i.m_DefQosFlowIndicationIsSet_value;
  b[n].is_null     = &i.m_DefQosFlowIndicationIsSet_null;
  n++;

  // m_ExtMaxDataBurstVol
  //
  b[n].buffer_type = MYSQL_TYPE_LONG;
  b[n].is_unsigned = 0;
  b[n].buffer      = &i.m_ExtMaxDataBurstVol_value;
  b[n].is_null     = &i.m_ExtMaxDataBurstVol_null;
  n++;

  // m_ExtMaxDataBurstVolIsSet
  //
  b[n].buffer_type = MYSQL_TYPE_TINY;
  b[n].is_unsigned = 0;
  b[n].buffer      = &i.m_ExtMaxDataBurstVolIsSet_value;
  b[n].is_null     = &i.m_ExtMaxDataBurstVolIsSet_null;
  n++;

  // m_PacketDelayBudget
  //
  b[n].buffer_type = MYSQL_TYPE_LONG;
  b[n].is_unsigned = 0;
  b[n].buffer      = &i.m_PacketDelayBudget_value;
  b[n].is_null     = &i.m_PacketDelayBudget_null;
  n++;

  // m_PacketDelayBudgetIsSet
  //
  b[n].buffer_type = MYSQL_TYPE_TINY;
  b[n].is_unsigned = 0;
  b[n].buffer      = &i.m_PacketDelayBudgetIsSet_value;
  b[n].is_null     = &i.m_PacketDelayBudgetIsSet_null;
  n++;

  // m_PacketErrorRate
  //
  b[n].buffer_type = MYSQL_TYPE_STRING;
  b[n].buffer      = i.m_PacketErrorRate_value.data();
  b[n].buffer_length =
      static_cast<unsigned long>(i.m_PacketErrorRate_value.capacity());
  b[n].length  = &i.m_PacketErrorRate_size;
  b[n].is_null = &i.m_PacketErrorRate_null;
  n++;

  // m_PacketErrorRateIsSet
  //
  b[n].buffer_type = MYSQL_TYPE_TINY;
  b[n].is_unsigned = 0;
  b[n].buffer      = &i.m_PacketErrorRateIsSet_value;
  b[n].is_null     = &i.m_PacketErrorRateIsSet_null;
  n++;
}

void access::object_traits_impl< ::oai::model::pcf::QosData, id_mysql>::bind(
    MYSQL_BIND* b, id_image_type& i) {
  std::size_t n(0);
  b[n].buffer_type   = MYSQL_TYPE_STRING;
  b[n].buffer        = i.id_value.data();
  b[n].buffer_length = static_cast<unsigned long>(i.id_value.capacity());
  b[n].length        = &i.id_size;
  b[n].is_null       = &i.id_null;
}

bool access::object_traits_impl< ::oai::model::pcf::QosData, id_mysql>::init(
    image_type& i, const object_type& o, mysql::statement_kind sk) {
  ODB_POTENTIALLY_UNUSED(i);
  ODB_POTENTIALLY_UNUSED(o);
  ODB_POTENTIALLY_UNUSED(sk);

  using namespace mysql;

  bool grew(false);

  // m_QosId
  //
  if (sk == statement_insert) {
    ::std::string const& v = o.m_QosId;

    bool is_null(false);
    std::size_t size(0);
    std::size_t cap(i.m_QosId_value.capacity());
    mysql::value_traits< ::std::string, mysql::id_string>::set_image(
        i.m_QosId_value, size, is_null, v);
    i.m_QosId_null = is_null;
    i.m_QosId_size = static_cast<unsigned long>(size);
    grew           = grew || (cap != i.m_QosId_value.capacity());
  }

  // m_r_5qi
  //
  {
    ::int32_t const& v = o.m_r_5qi;

    bool is_null(false);
    mysql::value_traits< ::int32_t, mysql::id_long>::set_image(
        i.m_r_5qi_value, is_null, v);
    i.m_r_5qi_null = is_null;
  }

  // m_r_5qiIsSet
  //
  {
    bool const& v = o.m_r_5qiIsSet;

    bool is_null(false);
    mysql::value_traits<bool, mysql::id_tiny>::set_image(
        i.m_r_5qiIsSet_value, is_null, v);
    i.m_r_5qiIsSet_null = is_null;
  }

  // m_MaxbrUl
  //
  {
    ::std::string const& v = o.m_MaxbrUl;

    bool is_null(false);
    std::size_t size(0);
    std::size_t cap(i.m_MaxbrUl_value.capacity());
    mysql::value_traits< ::std::string, mysql::id_string>::set_image(
        i.m_MaxbrUl_value, size, is_null, v);
    i.m_MaxbrUl_null = is_null;
    i.m_MaxbrUl_size = static_cast<unsigned long>(size);
    grew             = grew || (cap != i.m_MaxbrUl_value.capacity());
  }

  // m_MaxbrUlIsSet
  //
  {
    bool const& v = o.m_MaxbrUlIsSet;

    bool is_null(false);
    mysql::value_traits<bool, mysql::id_tiny>::set_image(
        i.m_MaxbrUlIsSet_value, is_null, v);
    i.m_MaxbrUlIsSet_null = is_null;
  }

  // m_MaxbrDl
  //
  {
    ::std::string const& v = o.m_MaxbrDl;

    bool is_null(false);
    std::size_t size(0);
    std::size_t cap(i.m_MaxbrDl_value.capacity());
    mysql::value_traits< ::std::string, mysql::id_string>::set_image(
        i.m_MaxbrDl_value, size, is_null, v);
    i.m_MaxbrDl_null = is_null;
    i.m_MaxbrDl_size = static_cast<unsigned long>(size);
    grew             = grew || (cap != i.m_MaxbrDl_value.capacity());
  }

  // m_MaxbrDlIsSet
  //
  {
    bool const& v = o.m_MaxbrDlIsSet;

    bool is_null(false);
    mysql::value_traits<bool, mysql::id_tiny>::set_image(
        i.m_MaxbrDlIsSet_value, is_null, v);
    i.m_MaxbrDlIsSet_null = is_null;
  }

  // m_GbrUl
  //
  {
    ::std::string const& v = o.m_GbrUl;

    bool is_null(false);
    std::size_t size(0);
    std::size_t cap(i.m_GbrUl_value.capacity());
    mysql::value_traits< ::std::string, mysql::id_string>::set_image(
        i.m_GbrUl_value, size, is_null, v);
    i.m_GbrUl_null = is_null;
    i.m_GbrUl_size = static_cast<unsigned long>(size);
    grew           = grew || (cap != i.m_GbrUl_value.capacity());
  }

  // m_GbrUlIsSet
  //
  {
    bool const& v = o.m_GbrUlIsSet;

    bool is_null(false);
    mysql::value_traits<bool, mysql::id_tiny>::set_image(
        i.m_GbrUlIsSet_value, is_null, v);
    i.m_GbrUlIsSet_null = is_null;
  }

  // m_GbrDl
  //
  {
    ::std::string const& v = o.m_GbrDl;

    bool is_null(false);
    std::size_t size(0);
    std::size_t cap(i.m_GbrDl_value.capacity());
    mysql::value_traits< ::std::string, mysql::id_string>::set_image(
        i.m_GbrDl_value, size, is_null, v);
    i.m_GbrDl_null = is_null;
    i.m_GbrDl_size = static_cast<unsigned long>(size);
    grew           = grew || (cap != i.m_GbrDl_value.capacity());
  }

  // m_GbrDlIsSet
  //
  {
    bool const& v = o.m_GbrDlIsSet;

    bool is_null(false);
    mysql::value_traits<bool, mysql::id_tiny>::set_image(
        i.m_GbrDlIsSet_value, is_null, v);
    i.m_GbrDlIsSet_null = is_null;
  }

  // m_Arp
  //
  {
    ::oai::model::common::Arp const& v = o.m_Arp;

    if (composite_value_traits< ::oai::model::common::Arp, id_mysql>::init(
            i.m_Arp_value, v, sk))
      grew = true;
  }

  // m_ArpIsSet
  //
  {
    bool const& v = o.m_ArpIsSet;

    bool is_null(false);
    mysql::value_traits<bool, mysql::id_tiny>::set_image(
        i.m_ArpIsSet_value, is_null, v);
    i.m_ArpIsSet_null = is_null;
  }

  // m_Qnc
  //
  {
    bool const& v = o.m_Qnc;

    bool is_null(false);
    mysql::value_traits<bool, mysql::id_tiny>::set_image(
        i.m_Qnc_value, is_null, v);
    i.m_Qnc_null = is_null;
  }

  // m_QncIsSet
  //
  {
    bool const& v = o.m_QncIsSet;

    bool is_null(false);
    mysql::value_traits<bool, mysql::id_tiny>::set_image(
        i.m_QncIsSet_value, is_null, v);
    i.m_QncIsSet_null = is_null;
  }

  // m_PriorityLevel
  //
  {
    ::int32_t const& v = o.m_PriorityLevel;

    bool is_null(false);
    mysql::value_traits< ::int32_t, mysql::id_long>::set_image(
        i.m_PriorityLevel_value, is_null, v);
    i.m_PriorityLevel_null = is_null;
  }

  // m_PriorityLevelIsSet
  //
  {
    bool const& v = o.m_PriorityLevelIsSet;

    bool is_null(false);
    mysql::value_traits<bool, mysql::id_tiny>::set_image(
        i.m_PriorityLevelIsSet_value, is_null, v);
    i.m_PriorityLevelIsSet_null = is_null;
  }

  // m_AverWindow
  //
  {
    ::int32_t const& v = o.m_AverWindow;

    bool is_null(false);
    mysql::value_traits< ::int32_t, mysql::id_long>::set_image(
        i.m_AverWindow_value, is_null, v);
    i.m_AverWindow_null = is_null;
  }

  // m_AverWindowIsSet
  //
  {
    bool const& v = o.m_AverWindowIsSet;

    bool is_null(false);
    mysql::value_traits<bool, mysql::id_tiny>::set_image(
        i.m_AverWindowIsSet_value, is_null, v);
    i.m_AverWindowIsSet_null = is_null;
  }

  // m_MaxDataBurstVol
  //
  {
    ::int32_t const& v = o.m_MaxDataBurstVol;

    bool is_null(false);
    mysql::value_traits< ::int32_t, mysql::id_long>::set_image(
        i.m_MaxDataBurstVol_value, is_null, v);
    i.m_MaxDataBurstVol_null = is_null;
  }

  // m_MaxDataBurstVolIsSet
  //
  {
    bool const& v = o.m_MaxDataBurstVolIsSet;

    bool is_null(false);
    mysql::value_traits<bool, mysql::id_tiny>::set_image(
        i.m_MaxDataBurstVolIsSet_value, is_null, v);
    i.m_MaxDataBurstVolIsSet_null = is_null;
  }

  // m_ReflectiveQos
  //
  {
    bool const& v = o.m_ReflectiveQos;

    bool is_null(false);
    mysql::value_traits<bool, mysql::id_tiny>::set_image(
        i.m_ReflectiveQos_value, is_null, v);
    i.m_ReflectiveQos_null = is_null;
  }

  // m_ReflectiveQosIsSet
  //
  {
    bool const& v = o.m_ReflectiveQosIsSet;

    bool is_null(false);
    mysql::value_traits<bool, mysql::id_tiny>::set_image(
        i.m_ReflectiveQosIsSet_value, is_null, v);
    i.m_ReflectiveQosIsSet_null = is_null;
  }

  // m_SharingKeyDl
  //
  {
    ::std::string const& v = o.m_SharingKeyDl;

    bool is_null(false);
    std::size_t size(0);
    std::size_t cap(i.m_SharingKeyDl_value.capacity());
    mysql::value_traits< ::std::string, mysql::id_string>::set_image(
        i.m_SharingKeyDl_value, size, is_null, v);
    i.m_SharingKeyDl_null = is_null;
    i.m_SharingKeyDl_size = static_cast<unsigned long>(size);
    grew                  = grew || (cap != i.m_SharingKeyDl_value.capacity());
  }

  // m_SharingKeyDlIsSet
  //
  {
    bool const& v = o.m_SharingKeyDlIsSet;

    bool is_null(false);
    mysql::value_traits<bool, mysql::id_tiny>::set_image(
        i.m_SharingKeyDlIsSet_value, is_null, v);
    i.m_SharingKeyDlIsSet_null = is_null;
  }

  // m_SharingKeyUl
  //
  {
    ::std::string const& v = o.m_SharingKeyUl;

    bool is_null(false);
    std::size_t size(0);
    std::size_t cap(i.m_SharingKeyUl_value.capacity());
    mysql::value_traits< ::std::string, mysql::id_string>::set_image(
        i.m_SharingKeyUl_value, size, is_null, v);
    i.m_SharingKeyUl_null = is_null;
    i.m_SharingKeyUl_size = static_cast<unsigned long>(size);
    grew                  = grew || (cap != i.m_SharingKeyUl_value.capacity());
  }

  // m_SharingKeyUlIsSet
  //
  {
    bool const& v = o.m_SharingKeyUlIsSet;

    bool is_null(false);
    mysql::value_traits<bool, mysql::id_tiny>::set_image(
        i.m_SharingKeyUlIsSet_value, is_null, v);
    i.m_SharingKeyUlIsSet_null = is_null;
  }

  // m_MaxPacketLossRateDl
  //
  {
    ::int32_t const& v = o.m_MaxPacketLossRateDl;

    bool is_null(false);
    mysql::value_traits< ::int32_t, mysql::id_long>::set_image(
        i.m_MaxPacketLossRateDl_value, is_null, v);
    i.m_MaxPacketLossRateDl_null = is_null;
  }

  // m_MaxPacketLossRateDlIsSet
  //
  {
    bool const& v = o.m_MaxPacketLossRateDlIsSet;

    bool is_null(false);
    mysql::value_traits<bool, mysql::id_tiny>::set_image(
        i.m_MaxPacketLossRateDlIsSet_value, is_null, v);
    i.m_MaxPacketLossRateDlIsSet_null = is_null;
  }

  // m_MaxPacketLossRateUl
  //
  {
    ::int32_t const& v = o.m_MaxPacketLossRateUl;

    bool is_null(false);
    mysql::value_traits< ::int32_t, mysql::id_long>::set_image(
        i.m_MaxPacketLossRateUl_value, is_null, v);
    i.m_MaxPacketLossRateUl_null = is_null;
  }

  // m_MaxPacketLossRateUlIsSet
  //
  {
    bool const& v = o.m_MaxPacketLossRateUlIsSet;

    bool is_null(false);
    mysql::value_traits<bool, mysql::id_tiny>::set_image(
        i.m_MaxPacketLossRateUlIsSet_value, is_null, v);
    i.m_MaxPacketLossRateUlIsSet_null = is_null;
  }

  // m_DefQosFlowIndication
  //
  {
    bool const& v = o.m_DefQosFlowIndication;

    bool is_null(false);
    mysql::value_traits<bool, mysql::id_tiny>::set_image(
        i.m_DefQosFlowIndication_value, is_null, v);
    i.m_DefQosFlowIndication_null = is_null;
  }

  // m_DefQosFlowIndicationIsSet
  //
  {
    bool const& v = o.m_DefQosFlowIndicationIsSet;

    bool is_null(false);
    mysql::value_traits<bool, mysql::id_tiny>::set_image(
        i.m_DefQosFlowIndicationIsSet_value, is_null, v);
    i.m_DefQosFlowIndicationIsSet_null = is_null;
  }

  // m_ExtMaxDataBurstVol
  //
  {
    ::int32_t const& v = o.m_ExtMaxDataBurstVol;

    bool is_null(false);
    mysql::value_traits< ::int32_t, mysql::id_long>::set_image(
        i.m_ExtMaxDataBurstVol_value, is_null, v);
    i.m_ExtMaxDataBurstVol_null = is_null;
  }

  // m_ExtMaxDataBurstVolIsSet
  //
  {
    bool const& v = o.m_ExtMaxDataBurstVolIsSet;

    bool is_null(false);
    mysql::value_traits<bool, mysql::id_tiny>::set_image(
        i.m_ExtMaxDataBurstVolIsSet_value, is_null, v);
    i.m_ExtMaxDataBurstVolIsSet_null = is_null;
  }

  // m_PacketDelayBudget
  //
  {
    ::int32_t const& v = o.m_PacketDelayBudget;

    bool is_null(false);
    mysql::value_traits< ::int32_t, mysql::id_long>::set_image(
        i.m_PacketDelayBudget_value, is_null, v);
    i.m_PacketDelayBudget_null = is_null;
  }

  // m_PacketDelayBudgetIsSet
  //
  {
    bool const& v = o.m_PacketDelayBudgetIsSet;

    bool is_null(false);
    mysql::value_traits<bool, mysql::id_tiny>::set_image(
        i.m_PacketDelayBudgetIsSet_value, is_null, v);
    i.m_PacketDelayBudgetIsSet_null = is_null;
  }

  // m_PacketErrorRate
  //
  {
    ::std::string const& v = o.m_PacketErrorRate;

    bool is_null(false);
    std::size_t size(0);
    std::size_t cap(i.m_PacketErrorRate_value.capacity());
    mysql::value_traits< ::std::string, mysql::id_string>::set_image(
        i.m_PacketErrorRate_value, size, is_null, v);
    i.m_PacketErrorRate_null = is_null;
    i.m_PacketErrorRate_size = static_cast<unsigned long>(size);
    grew = grew || (cap != i.m_PacketErrorRate_value.capacity());
  }

  // m_PacketErrorRateIsSet
  //
  {
    bool const& v = o.m_PacketErrorRateIsSet;

    bool is_null(false);
    mysql::value_traits<bool, mysql::id_tiny>::set_image(
        i.m_PacketErrorRateIsSet_value, is_null, v);
    i.m_PacketErrorRateIsSet_null = is_null;
  }

  return grew;
}

void access::object_traits_impl< ::oai::model::pcf::QosData, id_mysql>::init(
    object_type& o, const image_type& i, database* db) {
  ODB_POTENTIALLY_UNUSED(o);
  ODB_POTENTIALLY_UNUSED(i);
  ODB_POTENTIALLY_UNUSED(db);

  // m_QosId
  //
  {
    ::std::string& v = o.m_QosId;

    mysql::value_traits< ::std::string, mysql::id_string>::set_value(
        v, i.m_QosId_value, i.m_QosId_size, i.m_QosId_null);
  }

  // m_r_5qi
  //
  {
    ::int32_t& v = o.m_r_5qi;

    mysql::value_traits< ::int32_t, mysql::id_long>::set_value(
        v, i.m_r_5qi_value, i.m_r_5qi_null);
  }

  // m_r_5qiIsSet
  //
  {
    bool& v = o.m_r_5qiIsSet;

    mysql::value_traits<bool, mysql::id_tiny>::set_value(
        v, i.m_r_5qiIsSet_value, i.m_r_5qiIsSet_null);
  }

  // m_MaxbrUl
  //
  {
    ::std::string& v = o.m_MaxbrUl;

    mysql::value_traits< ::std::string, mysql::id_string>::set_value(
        v, i.m_MaxbrUl_value, i.m_MaxbrUl_size, i.m_MaxbrUl_null);
  }

  // m_MaxbrUlIsSet
  //
  {
    bool& v = o.m_MaxbrUlIsSet;

    mysql::value_traits<bool, mysql::id_tiny>::set_value(
        v, i.m_MaxbrUlIsSet_value, i.m_MaxbrUlIsSet_null);
  }

  // m_MaxbrDl
  //
  {
    ::std::string& v = o.m_MaxbrDl;

    mysql::value_traits< ::std::string, mysql::id_string>::set_value(
        v, i.m_MaxbrDl_value, i.m_MaxbrDl_size, i.m_MaxbrDl_null);
  }

  // m_MaxbrDlIsSet
  //
  {
    bool& v = o.m_MaxbrDlIsSet;

    mysql::value_traits<bool, mysql::id_tiny>::set_value(
        v, i.m_MaxbrDlIsSet_value, i.m_MaxbrDlIsSet_null);
  }

  // m_GbrUl
  //
  {
    ::std::string& v = o.m_GbrUl;

    mysql::value_traits< ::std::string, mysql::id_string>::set_value(
        v, i.m_GbrUl_value, i.m_GbrUl_size, i.m_GbrUl_null);
  }

  // m_GbrUlIsSet
  //
  {
    bool& v = o.m_GbrUlIsSet;

    mysql::value_traits<bool, mysql::id_tiny>::set_value(
        v, i.m_GbrUlIsSet_value, i.m_GbrUlIsSet_null);
  }

  // m_GbrDl
  //
  {
    ::std::string& v = o.m_GbrDl;

    mysql::value_traits< ::std::string, mysql::id_string>::set_value(
        v, i.m_GbrDl_value, i.m_GbrDl_size, i.m_GbrDl_null);
  }

  // m_GbrDlIsSet
  //
  {
    bool& v = o.m_GbrDlIsSet;

    mysql::value_traits<bool, mysql::id_tiny>::set_value(
        v, i.m_GbrDlIsSet_value, i.m_GbrDlIsSet_null);
  }

  // m_Arp
  //
  {
    ::oai::model::common::Arp& v = o.m_Arp;

    composite_value_traits< ::oai::model::common::Arp, id_mysql>::init(
        v, i.m_Arp_value, db);
  }

  // m_ArpIsSet
  //
  {
    bool& v = o.m_ArpIsSet;

    mysql::value_traits<bool, mysql::id_tiny>::set_value(
        v, i.m_ArpIsSet_value, i.m_ArpIsSet_null);
  }

  // m_Qnc
  //
  {
    bool& v = o.m_Qnc;

    mysql::value_traits<bool, mysql::id_tiny>::set_value(
        v, i.m_Qnc_value, i.m_Qnc_null);
  }

  // m_QncIsSet
  //
  {
    bool& v = o.m_QncIsSet;

    mysql::value_traits<bool, mysql::id_tiny>::set_value(
        v, i.m_QncIsSet_value, i.m_QncIsSet_null);
  }

  // m_PriorityLevel
  //
  {
    ::int32_t& v = o.m_PriorityLevel;

    mysql::value_traits< ::int32_t, mysql::id_long>::set_value(
        v, i.m_PriorityLevel_value, i.m_PriorityLevel_null);
  }

  // m_PriorityLevelIsSet
  //
  {
    bool& v = o.m_PriorityLevelIsSet;

    mysql::value_traits<bool, mysql::id_tiny>::set_value(
        v, i.m_PriorityLevelIsSet_value, i.m_PriorityLevelIsSet_null);
  }

  // m_AverWindow
  //
  {
    ::int32_t& v = o.m_AverWindow;

    mysql::value_traits< ::int32_t, mysql::id_long>::set_value(
        v, i.m_AverWindow_value, i.m_AverWindow_null);
  }

  // m_AverWindowIsSet
  //
  {
    bool& v = o.m_AverWindowIsSet;

    mysql::value_traits<bool, mysql::id_tiny>::set_value(
        v, i.m_AverWindowIsSet_value, i.m_AverWindowIsSet_null);
  }

  // m_MaxDataBurstVol
  //
  {
    ::int32_t& v = o.m_MaxDataBurstVol;

    mysql::value_traits< ::int32_t, mysql::id_long>::set_value(
        v, i.m_MaxDataBurstVol_value, i.m_MaxDataBurstVol_null);
  }

  // m_MaxDataBurstVolIsSet
  //
  {
    bool& v = o.m_MaxDataBurstVolIsSet;

    mysql::value_traits<bool, mysql::id_tiny>::set_value(
        v, i.m_MaxDataBurstVolIsSet_value, i.m_MaxDataBurstVolIsSet_null);
  }

  // m_ReflectiveQos
  //
  {
    bool& v = o.m_ReflectiveQos;

    mysql::value_traits<bool, mysql::id_tiny>::set_value(
        v, i.m_ReflectiveQos_value, i.m_ReflectiveQos_null);
  }

  // m_ReflectiveQosIsSet
  //
  {
    bool& v = o.m_ReflectiveQosIsSet;

    mysql::value_traits<bool, mysql::id_tiny>::set_value(
        v, i.m_ReflectiveQosIsSet_value, i.m_ReflectiveQosIsSet_null);
  }

  // m_SharingKeyDl
  //
  {
    ::std::string& v = o.m_SharingKeyDl;

    mysql::value_traits< ::std::string, mysql::id_string>::set_value(
        v, i.m_SharingKeyDl_value, i.m_SharingKeyDl_size,
        i.m_SharingKeyDl_null);
  }

  // m_SharingKeyDlIsSet
  //
  {
    bool& v = o.m_SharingKeyDlIsSet;

    mysql::value_traits<bool, mysql::id_tiny>::set_value(
        v, i.m_SharingKeyDlIsSet_value, i.m_SharingKeyDlIsSet_null);
  }

  // m_SharingKeyUl
  //
  {
    ::std::string& v = o.m_SharingKeyUl;

    mysql::value_traits< ::std::string, mysql::id_string>::set_value(
        v, i.m_SharingKeyUl_value, i.m_SharingKeyUl_size,
        i.m_SharingKeyUl_null);
  }

  // m_SharingKeyUlIsSet
  //
  {
    bool& v = o.m_SharingKeyUlIsSet;

    mysql::value_traits<bool, mysql::id_tiny>::set_value(
        v, i.m_SharingKeyUlIsSet_value, i.m_SharingKeyUlIsSet_null);
  }

  // m_MaxPacketLossRateDl
  //
  {
    ::int32_t& v = o.m_MaxPacketLossRateDl;

    mysql::value_traits< ::int32_t, mysql::id_long>::set_value(
        v, i.m_MaxPacketLossRateDl_value, i.m_MaxPacketLossRateDl_null);
  }

  // m_MaxPacketLossRateDlIsSet
  //
  {
    bool& v = o.m_MaxPacketLossRateDlIsSet;

    mysql::value_traits<bool, mysql::id_tiny>::set_value(
        v, i.m_MaxPacketLossRateDlIsSet_value,
        i.m_MaxPacketLossRateDlIsSet_null);
  }

  // m_MaxPacketLossRateUl
  //
  {
    ::int32_t& v = o.m_MaxPacketLossRateUl;

    mysql::value_traits< ::int32_t, mysql::id_long>::set_value(
        v, i.m_MaxPacketLossRateUl_value, i.m_MaxPacketLossRateUl_null);
  }

  // m_MaxPacketLossRateUlIsSet
  //
  {
    bool& v = o.m_MaxPacketLossRateUlIsSet;

    mysql::value_traits<bool, mysql::id_tiny>::set_value(
        v, i.m_MaxPacketLossRateUlIsSet_value,
        i.m_MaxPacketLossRateUlIsSet_null);
  }

  // m_DefQosFlowIndication
  //
  {
    bool& v = o.m_DefQosFlowIndication;

    mysql::value_traits<bool, mysql::id_tiny>::set_value(
        v, i.m_DefQosFlowIndication_value, i.m_DefQosFlowIndication_null);
  }

  // m_DefQosFlowIndicationIsSet
  //
  {
    bool& v = o.m_DefQosFlowIndicationIsSet;

    mysql::value_traits<bool, mysql::id_tiny>::set_value(
        v, i.m_DefQosFlowIndicationIsSet_value,
        i.m_DefQosFlowIndicationIsSet_null);
  }

  // m_ExtMaxDataBurstVol
  //
  {
    ::int32_t& v = o.m_ExtMaxDataBurstVol;

    mysql::value_traits< ::int32_t, mysql::id_long>::set_value(
        v, i.m_ExtMaxDataBurstVol_value, i.m_ExtMaxDataBurstVol_null);
  }

  // m_ExtMaxDataBurstVolIsSet
  //
  {
    bool& v = o.m_ExtMaxDataBurstVolIsSet;

    mysql::value_traits<bool, mysql::id_tiny>::set_value(
        v, i.m_ExtMaxDataBurstVolIsSet_value, i.m_ExtMaxDataBurstVolIsSet_null);
  }

  // m_PacketDelayBudget
  //
  {
    ::int32_t& v = o.m_PacketDelayBudget;

    mysql::value_traits< ::int32_t, mysql::id_long>::set_value(
        v, i.m_PacketDelayBudget_value, i.m_PacketDelayBudget_null);
  }

  // m_PacketDelayBudgetIsSet
  //
  {
    bool& v = o.m_PacketDelayBudgetIsSet;

    mysql::value_traits<bool, mysql::id_tiny>::set_value(
        v, i.m_PacketDelayBudgetIsSet_value, i.m_PacketDelayBudgetIsSet_null);
  }

  // m_PacketErrorRate
  //
  {
    ::std::string& v = o.m_PacketErrorRate;

    mysql::value_traits< ::std::string, mysql::id_string>::set_value(
        v, i.m_PacketErrorRate_value, i.m_PacketErrorRate_size,
        i.m_PacketErrorRate_null);
  }

  // m_PacketErrorRateIsSet
  //
  {
    bool& v = o.m_PacketErrorRateIsSet;

    mysql::value_traits<bool, mysql::id_tiny>::set_value(
        v, i.m_PacketErrorRateIsSet_value, i.m_PacketErrorRateIsSet_null);
  }
}

void access::object_traits_impl< ::oai::model::pcf::QosData, id_mysql>::init(
    id_image_type& i, const id_type& id) {
  bool grew(false);
  {
    bool is_null(false);
    std::size_t size(0);
    std::size_t cap(i.id_value.capacity());
    mysql::value_traits< ::std::string, mysql::id_string>::set_image(
        i.id_value, size, is_null, id);
    i.id_null = is_null;
    i.id_size = static_cast<unsigned long>(size);
    grew      = grew || (cap != i.id_value.capacity());
  }

  if (grew) i.version++;
}

const char access::object_traits_impl<
    ::oai::model::pcf::QosData, id_mysql>::persist_statement[] =
    "INSERT INTO `QosData` "
    "(`QosId`, "
    "`r_5qi`, "
    "`r_5qiIsSet`, "
    "`MaxbrUl`, "
    "`MaxbrUlIsSet`, "
    "`MaxbrDl`, "
    "`MaxbrDlIsSet`, "
    "`GbrUl`, "
    "`GbrUlIsSet`, "
    "`GbrDl`, "
    "`GbrDlIsSet`, "
    "`Arp_PriorityLevel`, "
    "`Arp_PreemptCap_value_value`, "
    "`Arp_PreemptVuln_value_value`, "
    "`ArpIsSet`, "
    "`Qnc`, "
    "`QncIsSet`, "
    "`PriorityLevel`, "
    "`PriorityLevelIsSet`, "
    "`AverWindow`, "
    "`AverWindowIsSet`, "
    "`MaxDataBurstVol`, "
    "`MaxDataBurstVolIsSet`, "
    "`ReflectiveQos`, "
    "`ReflectiveQosIsSet`, "
    "`SharingKeyDl`, "
    "`SharingKeyDlIsSet`, "
    "`SharingKeyUl`, "
    "`SharingKeyUlIsSet`, "
    "`MaxPacketLossRateDl`, "
    "`MaxPacketLossRateDlIsSet`, "
    "`MaxPacketLossRateUl`, "
    "`MaxPacketLossRateUlIsSet`, "
    "`DefQosFlowIndication`, "
    "`DefQosFlowIndicationIsSet`, "
    "`ExtMaxDataBurstVol`, "
    "`ExtMaxDataBurstVolIsSet`, "
    "`PacketDelayBudget`, "
    "`PacketDelayBudgetIsSet`, "
    "`PacketErrorRate`, "
    "`PacketErrorRateIsSet`) "
    "VALUES "
    "(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, "
    "?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

const char access::object_traits_impl<
    ::oai::model::pcf::QosData, id_mysql>::find_statement[] =
    "SELECT "
    "`QosData`.`QosId`, "
    "`QosData`.`r_5qi`, "
    "`QosData`.`r_5qiIsSet`, "
    "`QosData`.`MaxbrUl`, "
    "`QosData`.`MaxbrUlIsSet`, "
    "`QosData`.`MaxbrDl`, "
    "`QosData`.`MaxbrDlIsSet`, "
    "`QosData`.`GbrUl`, "
    "`QosData`.`GbrUlIsSet`, "
    "`QosData`.`GbrDl`, "
    "`QosData`.`GbrDlIsSet`, "
    "`QosData`.`Arp_PriorityLevel`, "
    "CONCAT(`QosData`.`Arp_PreemptCap_value_value`+0,' "
    "',`QosData`.`Arp_PreemptCap_value_value`), "
    "CONCAT(`QosData`.`Arp_PreemptVuln_value_value`+0,' "
    "',`QosData`.`Arp_PreemptVuln_value_value`), "
    "`QosData`.`ArpIsSet`, "
    "`QosData`.`Qnc`, "
    "`QosData`.`QncIsSet`, "
    "`QosData`.`PriorityLevel`, "
    "`QosData`.`PriorityLevelIsSet`, "
    "`QosData`.`AverWindow`, "
    "`QosData`.`AverWindowIsSet`, "
    "`QosData`.`MaxDataBurstVol`, "
    "`QosData`.`MaxDataBurstVolIsSet`, "
    "`QosData`.`ReflectiveQos`, "
    "`QosData`.`ReflectiveQosIsSet`, "
    "`QosData`.`SharingKeyDl`, "
    "`QosData`.`SharingKeyDlIsSet`, "
    "`QosData`.`SharingKeyUl`, "
    "`QosData`.`SharingKeyUlIsSet`, "
    "`QosData`.`MaxPacketLossRateDl`, "
    "`QosData`.`MaxPacketLossRateDlIsSet`, "
    "`QosData`.`MaxPacketLossRateUl`, "
    "`QosData`.`MaxPacketLossRateUlIsSet`, "
    "`QosData`.`DefQosFlowIndication`, "
    "`QosData`.`DefQosFlowIndicationIsSet`, "
    "`QosData`.`ExtMaxDataBurstVol`, "
    "`QosData`.`ExtMaxDataBurstVolIsSet`, "
    "`QosData`.`PacketDelayBudget`, "
    "`QosData`.`PacketDelayBudgetIsSet`, "
    "`QosData`.`PacketErrorRate`, "
    "`QosData`.`PacketErrorRateIsSet` "
    "FROM `QosData` "
    "WHERE `QosData`.`QosId`=?";

const char access::object_traits_impl<
    ::oai::model::pcf::QosData, id_mysql>::update_statement[] =
    "UPDATE `QosData` "
    "SET "
    "`r_5qi`=?, "
    "`r_5qiIsSet`=?, "
    "`MaxbrUl`=?, "
    "`MaxbrUlIsSet`=?, "
    "`MaxbrDl`=?, "
    "`MaxbrDlIsSet`=?, "
    "`GbrUl`=?, "
    "`GbrUlIsSet`=?, "
    "`GbrDl`=?, "
    "`GbrDlIsSet`=?, "
    "`Arp_PriorityLevel`=?, "
    "`Arp_PreemptCap_value_value`=?, "
    "`Arp_PreemptVuln_value_value`=?, "
    "`ArpIsSet`=?, "
    "`Qnc`=?, "
    "`QncIsSet`=?, "
    "`PriorityLevel`=?, "
    "`PriorityLevelIsSet`=?, "
    "`AverWindow`=?, "
    "`AverWindowIsSet`=?, "
    "`MaxDataBurstVol`=?, "
    "`MaxDataBurstVolIsSet`=?, "
    "`ReflectiveQos`=?, "
    "`ReflectiveQosIsSet`=?, "
    "`SharingKeyDl`=?, "
    "`SharingKeyDlIsSet`=?, "
    "`SharingKeyUl`=?, "
    "`SharingKeyUlIsSet`=?, "
    "`MaxPacketLossRateDl`=?, "
    "`MaxPacketLossRateDlIsSet`=?, "
    "`MaxPacketLossRateUl`=?, "
    "`MaxPacketLossRateUlIsSet`=?, "
    "`DefQosFlowIndication`=?, "
    "`DefQosFlowIndicationIsSet`=?, "
    "`ExtMaxDataBurstVol`=?, "
    "`ExtMaxDataBurstVolIsSet`=?, "
    "`PacketDelayBudget`=?, "
    "`PacketDelayBudgetIsSet`=?, "
    "`PacketErrorRate`=?, "
    "`PacketErrorRateIsSet`=? "
    "WHERE `QosId`=?";

const char access::object_traits_impl<
    ::oai::model::pcf::QosData, id_mysql>::erase_statement[] =
    "DELETE FROM `QosData` "
    "WHERE `QosId`=?";

const char access::object_traits_impl<
    ::oai::model::pcf::QosData, id_mysql>::query_statement[] =
    "SELECT "
    "`QosData`.`QosId`, "
    "`QosData`.`r_5qi`, "
    "`QosData`.`r_5qiIsSet`, "
    "`QosData`.`MaxbrUl`, "
    "`QosData`.`MaxbrUlIsSet`, "
    "`QosData`.`MaxbrDl`, "
    "`QosData`.`MaxbrDlIsSet`, "
    "`QosData`.`GbrUl`, "
    "`QosData`.`GbrUlIsSet`, "
    "`QosData`.`GbrDl`, "
    "`QosData`.`GbrDlIsSet`, "
    "`QosData`.`Arp_PriorityLevel`, "
    "CONCAT(`QosData`.`Arp_PreemptCap_value_value`+0,' "
    "',`QosData`.`Arp_PreemptCap_value_value`), "
    "CONCAT(`QosData`.`Arp_PreemptVuln_value_value`+0,' "
    "',`QosData`.`Arp_PreemptVuln_value_value`), "
    "`QosData`.`ArpIsSet`, "
    "`QosData`.`Qnc`, "
    "`QosData`.`QncIsSet`, "
    "`QosData`.`PriorityLevel`, "
    "`QosData`.`PriorityLevelIsSet`, "
    "`QosData`.`AverWindow`, "
    "`QosData`.`AverWindowIsSet`, "
    "`QosData`.`MaxDataBurstVol`, "
    "`QosData`.`MaxDataBurstVolIsSet`, "
    "`QosData`.`ReflectiveQos`, "
    "`QosData`.`ReflectiveQosIsSet`, "
    "`QosData`.`SharingKeyDl`, "
    "`QosData`.`SharingKeyDlIsSet`, "
    "`QosData`.`SharingKeyUl`, "
    "`QosData`.`SharingKeyUlIsSet`, "
    "`QosData`.`MaxPacketLossRateDl`, "
    "`QosData`.`MaxPacketLossRateDlIsSet`, "
    "`QosData`.`MaxPacketLossRateUl`, "
    "`QosData`.`MaxPacketLossRateUlIsSet`, "
    "`QosData`.`DefQosFlowIndication`, "
    "`QosData`.`DefQosFlowIndicationIsSet`, "
    "`QosData`.`ExtMaxDataBurstVol`, "
    "`QosData`.`ExtMaxDataBurstVolIsSet`, "
    "`QosData`.`PacketDelayBudget`, "
    "`QosData`.`PacketDelayBudgetIsSet`, "
    "`QosData`.`PacketErrorRate`, "
    "`QosData`.`PacketErrorRateIsSet` "
    "FROM `QosData`";

const char access::object_traits_impl<
    ::oai::model::pcf::QosData, id_mysql>::erase_query_statement[] =
    "DELETE FROM `QosData`";

const char access::object_traits_impl<
    ::oai::model::pcf::QosData, id_mysql>::table_name[] = "`QosData`";

void access::object_traits_impl< ::oai::model::pcf::QosData, id_mysql>::persist(
    database& db, const object_type& obj) {
  using namespace mysql;

  mysql::connection& conn(mysql::transaction::current().connection(db));
  statements_type& sts(conn.statement_cache().find_object<object_type>());

  callback(db, obj, callback_event::pre_persist);

  image_type& im(sts.image());
  binding& imb(sts.insert_image_binding());

  if (init(im, obj, statement_insert)) im.version++;

  if (im.version != sts.insert_image_version() || imb.version == 0) {
    bind(imb.bind, im, statement_insert);
    sts.insert_image_version(im.version);
    imb.version++;
  }

  insert_statement& st(sts.persist_statement());
  if (!st.execute()) throw object_already_persistent();

  callback(db, obj, callback_event::post_persist);
}

void access::object_traits_impl< ::oai::model::pcf::QosData, id_mysql>::update(
    database& db, const object_type& obj) {
  ODB_POTENTIALLY_UNUSED(db);

  using namespace mysql;
  using mysql::update_statement;

  callback(db, obj, callback_event::pre_update);

  mysql::transaction& tr(mysql::transaction::current());
  mysql::connection& conn(tr.connection(db));
  statements_type& sts(conn.statement_cache().find_object<object_type>());

  id_image_type& idi(sts.id_image());
  init(idi, id(obj));

  image_type& im(sts.image());
  if (init(im, obj, statement_update)) im.version++;

  bool u(false);
  binding& imb(sts.update_image_binding());
  if (im.version != sts.update_image_version() || imb.version == 0) {
    bind(imb.bind, im, statement_update);
    sts.update_image_version(im.version);
    imb.version++;
    u = true;
  }

  binding& idb(sts.id_image_binding());
  if (idi.version != sts.update_id_image_version() || idb.version == 0) {
    if (idi.version != sts.id_image_version() || idb.version == 0) {
      bind(idb.bind, idi);
      sts.id_image_version(idi.version);
      idb.version++;
    }

    sts.update_id_image_version(idi.version);

    if (!u) imb.version++;
  }

  update_statement& st(sts.update_statement());
  if (st.execute() == 0) throw object_not_persistent();

  callback(db, obj, callback_event::post_update);
  pointer_cache_traits::update(db, obj);
}

void access::object_traits_impl< ::oai::model::pcf::QosData, id_mysql>::erase(
    database& db, const id_type& id) {
  using namespace mysql;

  mysql::connection& conn(mysql::transaction::current().connection(db));
  statements_type& sts(conn.statement_cache().find_object<object_type>());

  id_image_type& i(sts.id_image());
  init(i, id);

  binding& idb(sts.id_image_binding());
  if (i.version != sts.id_image_version() || idb.version == 0) {
    bind(idb.bind, i);
    sts.id_image_version(i.version);
    idb.version++;
  }

  if (sts.erase_statement().execute() != 1) throw object_not_persistent();

  pointer_cache_traits::erase(db, id);
}

access::object_traits_impl< ::oai::model::pcf::QosData, id_mysql>::pointer_type
access::object_traits_impl< ::oai::model::pcf::QosData, id_mysql>::find(
    database& db, const id_type& id) {
  using namespace mysql;

  {
    pointer_type p(pointer_cache_traits::find(db, id));

    if (!pointer_traits::null_ptr(p)) return p;
  }

  mysql::connection& conn(mysql::transaction::current().connection(db));
  statements_type& sts(conn.statement_cache().find_object<object_type>());

  statements_type::auto_lock l(sts);

  if (l.locked()) {
    if (!find_(sts, &id)) return pointer_type();
  }

  pointer_type p(access::object_factory<object_type, pointer_type>::create());
  pointer_traits::guard pg(p);

  pointer_cache_traits::insert_guard ig(
      pointer_cache_traits::insert(db, id, p));

  object_type& obj(pointer_traits::get_ref(p));

  if (l.locked()) {
    select_statement& st(sts.find_statement());
    ODB_POTENTIALLY_UNUSED(st);

    callback(db, obj, callback_event::pre_load);
    init(obj, sts.image(), &db);
    load_(sts, obj, false);
    sts.load_delayed(0);
    l.unlock();
    callback(db, obj, callback_event::post_load);
    pointer_cache_traits::load(ig.position());
  } else
    sts.delay_load(id, obj, ig.position());

  ig.release();
  pg.release();
  return p;
}

bool access::object_traits_impl< ::oai::model::pcf::QosData, id_mysql>::find(
    database& db, const id_type& id, object_type& obj) {
  using namespace mysql;

  mysql::connection& conn(mysql::transaction::current().connection(db));
  statements_type& sts(conn.statement_cache().find_object<object_type>());

  statements_type::auto_lock l(sts);
  assert(l.locked()) /* Must be a top-level call. */;

  if (!find_(sts, &id)) return false;

  select_statement& st(sts.find_statement());
  ODB_POTENTIALLY_UNUSED(st);

  reference_cache_traits::position_type pos(
      reference_cache_traits::insert(db, id, obj));
  reference_cache_traits::insert_guard ig(pos);

  callback(db, obj, callback_event::pre_load);
  init(obj, sts.image(), &db);
  load_(sts, obj, false);
  sts.load_delayed(0);
  l.unlock();
  callback(db, obj, callback_event::post_load);
  reference_cache_traits::load(pos);
  ig.release();
  return true;
}

bool access::object_traits_impl< ::oai::model::pcf::QosData, id_mysql>::reload(
    database& db, object_type& obj) {
  using namespace mysql;

  mysql::connection& conn(mysql::transaction::current().connection(db));
  statements_type& sts(conn.statement_cache().find_object<object_type>());

  statements_type::auto_lock l(sts);
  assert(l.locked()) /* Must be a top-level call. */;

  const id_type& id(object_traits_impl::id(obj));
  if (!find_(sts, &id)) return false;

  select_statement& st(sts.find_statement());
  ODB_POTENTIALLY_UNUSED(st);

  callback(db, obj, callback_event::pre_load);
  init(obj, sts.image(), &db);
  load_(sts, obj, true);
  sts.load_delayed(0);
  l.unlock();
  callback(db, obj, callback_event::post_load);
  return true;
}

bool access::object_traits_impl< ::oai::model::pcf::QosData, id_mysql>::find_(
    statements_type& sts, const id_type* id) {
  using namespace mysql;

  id_image_type& i(sts.id_image());
  init(i, *id);

  binding& idb(sts.id_image_binding());
  if (i.version != sts.id_image_version() || idb.version == 0) {
    bind(idb.bind, i);
    sts.id_image_version(i.version);
    idb.version++;
  }

  image_type& im(sts.image());
  binding& imb(sts.select_image_binding());

  if (im.version != sts.select_image_version() || imb.version == 0) {
    bind(imb.bind, im, statement_select);
    sts.select_image_version(im.version);
    imb.version++;
  }

  select_statement& st(sts.find_statement());

  st.execute();
  auto_result ar(st);
  select_statement::result r(st.fetch());

  if (r == select_statement::truncated) {
    if (grow(im, sts.select_image_truncated())) im.version++;

    if (im.version != sts.select_image_version()) {
      bind(imb.bind, im, statement_select);
      sts.select_image_version(im.version);
      imb.version++;
      st.refetch();
    }
  }

  return r != select_statement::no_data;
}

result<access::object_traits_impl<
    ::oai::model::pcf::QosData, id_mysql>::object_type>
access::object_traits_impl< ::oai::model::pcf::QosData, id_mysql>::query(
    database& db, const query_base_type& q) {
  using namespace mysql;
  using odb::details::shared;
  using odb::details::shared_ptr;

  mysql::connection& conn(mysql::transaction::current().connection(db));

  statements_type& sts(conn.statement_cache().find_object<object_type>());

  image_type& im(sts.image());
  binding& imb(sts.select_image_binding());

  if (im.version != sts.select_image_version() || imb.version == 0) {
    bind(imb.bind, im, statement_select);
    sts.select_image_version(im.version);
    imb.version++;
  }

  std::string text(query_statement);
  if (!q.empty()) {
    text += " ";
    text += q.clause();
  }

  q.init_parameters();
  shared_ptr<select_statement> st(new (shared) select_statement(
      conn, text, false, true, q.parameters_binding(), imb));

  st->execute();

  shared_ptr<odb::object_result_impl<object_type> > r(
      new (shared) mysql::object_result_impl<object_type>(q, st, sts, 0));

  return result<object_type>(r);
}

unsigned long long
access::object_traits_impl< ::oai::model::pcf::QosData, id_mysql>::erase_query(
    database& db, const query_base_type& q) {
  using namespace mysql;

  mysql::connection& conn(mysql::transaction::current().connection(db));

  std::string text(erase_query_statement);
  if (!q.empty()) {
    text += ' ';
    text += q.clause();
  }

  q.init_parameters();
  delete_statement st(conn, text, q.parameters_binding());

  return st.execute();
}
}  // namespace odb

#include <odb/post.hxx>
