// -*- C++ -*-
//
// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#include "SlicePolicyDecision-odb.hxx"

#include <cassert>
#include <cstring>  // std::memcpy

#include <odb/mysql/traits.hxx>
#include <odb/mysql/database.hxx>
#include <odb/mysql/transaction.hxx>
#include <odb/mysql/connection.hxx>
#include <odb/mysql/statement.hxx>
#include <odb/mysql/statement-cache.hxx>
#include <odb/mysql/simple-object-statements.hxx>
#include <odb/mysql/container-statements.hxx>
#include <odb/mysql/exceptions.hxx>
#include <odb/mysql/simple-object-result.hxx>
#include <odb/mysql/enum.hxx>

namespace odb {
// SlicePolicyDecision
//

struct access::object_traits_impl<
    ::oai::pcf::provisioning::model::SlicePolicyDecision,
    id_mysql>::extra_statement_cache_type {
  mysql::container_statements_impl<PccRuleIds_traits> m_PccRuleIds;

  extra_statement_cache_type(
      mysql::connection& c, image_type&, id_image_type&, mysql::binding& id,
      mysql::binding&)
      : m_PccRuleIds(c, id) {}
};

// m_PccRuleIds
//

const char access::object_traits_impl<
    ::oai::pcf::provisioning::model::SlicePolicyDecision,
    id_mysql>::PccRuleIds_traits::select_statement[] =
    "SELECT "
    "`SlicePolicyDecision_PccRuleIds`.`index`, "
    "`SlicePolicyDecision_PccRuleIds`.`value` "
    "FROM `SlicePolicyDecision_PccRuleIds` "
    "WHERE `SlicePolicyDecision_PccRuleIds`.`object_id_Sst`=? AND "
    "`SlicePolicyDecision_PccRuleIds`.`object_id_Sd`=? AND "
    "`SlicePolicyDecision_PccRuleIds`.`object_id_SdIsSet`=? ORDER BY "
    "`SlicePolicyDecision_PccRuleIds`.`index`";

const char access::object_traits_impl<
    ::oai::pcf::provisioning::model::SlicePolicyDecision,
    id_mysql>::PccRuleIds_traits::insert_statement[] =
    "INSERT INTO `SlicePolicyDecision_PccRuleIds` "
    "(`object_id_Sst`, "
    "`object_id_Sd`, "
    "`object_id_SdIsSet`, "
    "`index`, "
    "`value`) "
    "VALUES "
    "(?, ?, ?, ?, ?)";

const char access::object_traits_impl<
    ::oai::pcf::provisioning::model::SlicePolicyDecision,
    id_mysql>::PccRuleIds_traits::delete_statement[] =
    "DELETE FROM `SlicePolicyDecision_PccRuleIds` "
    "WHERE `object_id_Sst`=? AND `object_id_Sd`=? AND `object_id_SdIsSet`=?";

void access::object_traits_impl<
    ::oai::pcf::provisioning::model::SlicePolicyDecision, id_mysql>::
    PccRuleIds_traits::bind(
        MYSQL_BIND* b, const MYSQL_BIND* id, std::size_t id_size,
        data_image_type& d) {
  using namespace mysql;

  statement_kind sk(statement_select);
  ODB_POTENTIALLY_UNUSED(sk);

  size_t n(0);

  // object_id
  //
  if (id != 0) std::memcpy(&b[n], id, id_size * sizeof(id[0]));
  n += id_size;

  // index
  //
  b[n].buffer_type = MYSQL_TYPE_LONGLONG;
  b[n].is_unsigned = 1;
  b[n].buffer      = &d.index_value;
  b[n].is_null     = &d.index_null;
  n++;

  // value
  //
  b[n].buffer_type   = MYSQL_TYPE_STRING;
  b[n].buffer        = d.value_value.data();
  b[n].buffer_length = static_cast<unsigned long>(d.value_value.capacity());
  b[n].length        = &d.value_size;
  b[n].is_null       = &d.value_null;
}

void access::object_traits_impl<
    ::oai::pcf::provisioning::model::SlicePolicyDecision,
    id_mysql>::PccRuleIds_traits::grow(data_image_type& i, my_bool* t) {
  bool grew(false);

  // index
  //
  t[0UL] = 0;

  // value
  //
  if (t[1UL]) {
    i.value_value.capacity(i.value_size);
    grew = true;
  }

  if (grew) i.version++;
}

void access::object_traits_impl<
    ::oai::pcf::provisioning::model::SlicePolicyDecision, id_mysql>::
    PccRuleIds_traits::init(
        data_image_type& i, index_type* j, const value_type& v) {
  using namespace mysql;

  statement_kind sk(statement_insert);
  ODB_POTENTIALLY_UNUSED(sk);

  bool grew(false);

  // index
  //
  if (j != 0) {
    bool is_null(false);
    mysql::value_traits<index_type, mysql::id_ulonglong>::set_image(
        i.index_value, is_null, *j);
    i.index_null = is_null;
  }

  // value
  //
  {
    bool is_null(false);
    std::size_t size(0);
    std::size_t cap(i.value_value.capacity());
    mysql::value_traits<value_type, mysql::id_string>::set_image(
        i.value_value, size, is_null, v);
    i.value_null = is_null;
    i.value_size = static_cast<unsigned long>(size);
    grew         = grew || (cap != i.value_value.capacity());
  }

  if (grew) i.version++;
}

void access::object_traits_impl<
    ::oai::pcf::provisioning::model::SlicePolicyDecision, id_mysql>::
    PccRuleIds_traits::init(
        index_type& j, value_type& v, const data_image_type& i, database* db) {
  ODB_POTENTIALLY_UNUSED(db);

  // index
  //
  {
    mysql::value_traits<index_type, mysql::id_ulonglong>::set_value(
        j, i.index_value, i.index_null);
  }

  // value
  //
  {
    mysql::value_traits<value_type, mysql::id_string>::set_value(
        v, i.value_value, i.value_size, i.value_null);
  }
}

void access::object_traits_impl<
    ::oai::pcf::provisioning::model::SlicePolicyDecision, id_mysql>::
    PccRuleIds_traits::insert(index_type i, const value_type& v, void* d) {
  using namespace mysql;

  statements_type& sts(*static_cast<statements_type*>(d));
  data_image_type& di(sts.data_image());

  init(di, &i, v);

  if (sts.data_binding_test_version()) {
    const binding& id(sts.id_binding());
    bind(sts.data_bind(), id.bind, id.count, di);
    sts.data_binding_update_version();
  }

  if (!sts.insert_statement().execute()) throw object_already_persistent();
}

bool access::object_traits_impl<
    ::oai::pcf::provisioning::model::SlicePolicyDecision, id_mysql>::
    PccRuleIds_traits::select(index_type& i, value_type& v, void* d) {
  using namespace mysql;
  using mysql::select_statement;

  statements_type& sts(*static_cast<statements_type*>(d));
  data_image_type& di(sts.data_image());

  init(i, v, di, &sts.connection().database());

  select_statement& st(sts.select_statement());
  select_statement::result r(st.fetch());

  if (r == select_statement::truncated) {
    grow(di, sts.select_image_truncated());

    if (sts.data_binding_test_version()) {
      bind(sts.data_bind(), 0, sts.id_binding().count, di);
      sts.data_binding_update_version();
      st.refetch();
    }
  }

  return r != select_statement::no_data;
}

void access::object_traits_impl<
    ::oai::pcf::provisioning::model::SlicePolicyDecision,
    id_mysql>::PccRuleIds_traits::delete_(void* d) {
  using namespace mysql;

  statements_type& sts(*static_cast<statements_type*>(d));
  sts.delete_statement().execute();
}

void access::object_traits_impl<
    ::oai::pcf::provisioning::model::SlicePolicyDecision, id_mysql>::
    PccRuleIds_traits::persist(const container_type& c, statements_type& sts) {
  using namespace mysql;

  functions_type& fs(sts.functions());
  fs.ordered_ = true;
  container_traits_type::persist(c, fs);
}

void access::object_traits_impl<
    ::oai::pcf::provisioning::model::SlicePolicyDecision, id_mysql>::
    PccRuleIds_traits::load(container_type& c, statements_type& sts) {
  using namespace mysql;
  using mysql::select_statement;

  const binding& id(sts.id_binding());

  if (sts.data_binding_test_version()) {
    bind(sts.data_bind(), id.bind, id.count, sts.data_image());
    sts.data_binding_update_version();
  }

  select_statement& st(sts.select_statement());
  st.execute();
  auto_result ar(st);
  select_statement::result r(st.fetch());

  if (r == select_statement::truncated) {
    data_image_type& di(sts.data_image());
    grow(di, sts.select_image_truncated());

    if (sts.data_binding_test_version()) {
      bind(sts.data_bind(), 0, id.count, di);
      sts.data_binding_update_version();
      st.refetch();
    }
  }

  bool more(r != select_statement::no_data);

  functions_type& fs(sts.functions());
  fs.ordered_ = true;
  container_traits_type::load(c, more, fs);
}

void access::object_traits_impl<
    ::oai::pcf::provisioning::model::SlicePolicyDecision, id_mysql>::
    PccRuleIds_traits::update(const container_type& c, statements_type& sts) {
  using namespace mysql;

  functions_type& fs(sts.functions());
  fs.ordered_ = true;
  container_traits_type::update(c, fs);
}

void access::object_traits_impl<
    ::oai::pcf::provisioning::model::SlicePolicyDecision,
    id_mysql>::PccRuleIds_traits::erase(statements_type& sts) {
  using namespace mysql;

  functions_type& fs(sts.functions());
  fs.ordered_ = true;
  container_traits_type::erase(fs);
}

access::object_traits_impl<
    ::oai::pcf::provisioning::model::SlicePolicyDecision, id_mysql>::id_type
access::object_traits_impl<
    ::oai::pcf::provisioning::model::SlicePolicyDecision,
    id_mysql>::id(const image_type& i) {
  mysql::database* db(0);
  ODB_POTENTIALLY_UNUSED(db);

  id_type id;
  {
    composite_value_traits< ::oai::model::common::Snssai, id_mysql>::init(
        id, i.m_Snssai_value, db);
  }

  return id;
}

bool access::object_traits_impl<
    ::oai::pcf::provisioning::model::SlicePolicyDecision,
    id_mysql>::grow(image_type& i, my_bool* t) {
  ODB_POTENTIALLY_UNUSED(i);
  ODB_POTENTIALLY_UNUSED(t);

  bool grew(false);

  // m_Snssai
  //
  if (composite_value_traits< ::oai::model::common::Snssai, id_mysql>::grow(
          i.m_Snssai_value, t + 0UL))
    grew = true;

  // m_SnssaiIsSet
  //
  t[3UL] = 0;

  // m_PccRuleIdsIsSet
  //
  t[4UL] = 0;

  return grew;
}

void access::object_traits_impl<
    ::oai::pcf::provisioning::model::SlicePolicyDecision,
    id_mysql>::bind(MYSQL_BIND* b, image_type& i, mysql::statement_kind sk) {
  ODB_POTENTIALLY_UNUSED(sk);

  using namespace mysql;

  std::size_t n(0);

  // m_Snssai
  //
  if (sk != statement_update) {
    composite_value_traits< ::oai::model::common::Snssai, id_mysql>::bind(
        b + n, i.m_Snssai_value, sk);
    n += 3UL;
  }

  // m_SnssaiIsSet
  //
  b[n].buffer_type = MYSQL_TYPE_TINY;
  b[n].is_unsigned = 0;
  b[n].buffer      = &i.m_SnssaiIsSet_value;
  b[n].is_null     = &i.m_SnssaiIsSet_null;
  n++;

  // m_PccRuleIdsIsSet
  //
  b[n].buffer_type = MYSQL_TYPE_TINY;
  b[n].is_unsigned = 0;
  b[n].buffer      = &i.m_PccRuleIdsIsSet_value;
  b[n].is_null     = &i.m_PccRuleIdsIsSet_null;
  n++;
}

void access::object_traits_impl<
    ::oai::pcf::provisioning::model::SlicePolicyDecision,
    id_mysql>::bind(MYSQL_BIND* b, id_image_type& i) {
  std::size_t n(0);
  mysql::statement_kind sk(mysql::statement_select);
  composite_value_traits< ::oai::model::common::Snssai, id_mysql>::bind(
      b + n, i.id_value, sk);
}

bool access::object_traits_impl<
    ::oai::pcf::provisioning::model::SlicePolicyDecision, id_mysql>::
    init(image_type& i, const object_type& o, mysql::statement_kind sk) {
  ODB_POTENTIALLY_UNUSED(i);
  ODB_POTENTIALLY_UNUSED(o);
  ODB_POTENTIALLY_UNUSED(sk);

  using namespace mysql;

  bool grew(false);

  // m_Snssai
  //
  if (sk == statement_insert) {
    ::oai::model::common::Snssai const& v = o.m_Snssai;

    if (composite_value_traits< ::oai::model::common::Snssai, id_mysql>::init(
            i.m_Snssai_value, v, sk))
      grew = true;
  }

  // m_SnssaiIsSet
  //
  {
    bool const& v = o.m_SnssaiIsSet;

    bool is_null(false);
    mysql::value_traits<bool, mysql::id_tiny>::set_image(
        i.m_SnssaiIsSet_value, is_null, v);
    i.m_SnssaiIsSet_null = is_null;
  }

  // m_PccRuleIdsIsSet
  //
  {
    bool const& v = o.m_PccRuleIdsIsSet;

    bool is_null(false);
    mysql::value_traits<bool, mysql::id_tiny>::set_image(
        i.m_PccRuleIdsIsSet_value, is_null, v);
    i.m_PccRuleIdsIsSet_null = is_null;
  }

  return grew;
}

void access::object_traits_impl<
    ::oai::pcf::provisioning::model::SlicePolicyDecision,
    id_mysql>::init(object_type& o, const image_type& i, database* db) {
  ODB_POTENTIALLY_UNUSED(o);
  ODB_POTENTIALLY_UNUSED(i);
  ODB_POTENTIALLY_UNUSED(db);

  // m_Snssai
  //
  {
    ::oai::model::common::Snssai& v = o.m_Snssai;

    composite_value_traits< ::oai::model::common::Snssai, id_mysql>::init(
        v, i.m_Snssai_value, db);
  }

  // m_SnssaiIsSet
  //
  {
    bool& v = o.m_SnssaiIsSet;

    mysql::value_traits<bool, mysql::id_tiny>::set_value(
        v, i.m_SnssaiIsSet_value, i.m_SnssaiIsSet_null);
  }

  // m_PccRuleIdsIsSet
  //
  {
    bool& v = o.m_PccRuleIdsIsSet;

    mysql::value_traits<bool, mysql::id_tiny>::set_value(
        v, i.m_PccRuleIdsIsSet_value, i.m_PccRuleIdsIsSet_null);
  }
}

void access::object_traits_impl<
    ::oai::pcf::provisioning::model::SlicePolicyDecision,
    id_mysql>::init(id_image_type& i, const id_type& id) {
  bool grew(false);
  mysql::statement_kind sk(mysql::statement_select);
  {
    if (composite_value_traits< ::oai::model::common::Snssai, id_mysql>::init(
            i.id_value, id, sk))
      grew = true;
  }

  if (grew) i.version++;
}

const char access::object_traits_impl<
    ::oai::pcf::provisioning::model::SlicePolicyDecision,
    id_mysql>::persist_statement[] =
    "INSERT INTO `SlicePolicyDecision` "
    "(`Snssai_Sst`, "
    "`Snssai_Sd`, "
    "`Snssai_SdIsSet`, "
    "`SnssaiIsSet`, "
    "`PccRuleIdsIsSet`) "
    "VALUES "
    "(?, ?, ?, ?, ?)";

const char access::object_traits_impl<
    ::oai::pcf::provisioning::model::SlicePolicyDecision,
    id_mysql>::find_statement[] =
    "SELECT "
    "`SlicePolicyDecision`.`Snssai_Sst`, "
    "`SlicePolicyDecision`.`Snssai_Sd`, "
    "`SlicePolicyDecision`.`Snssai_SdIsSet`, "
    "`SlicePolicyDecision`.`SnssaiIsSet`, "
    "`SlicePolicyDecision`.`PccRuleIdsIsSet` "
    "FROM `SlicePolicyDecision` "
    "WHERE `SlicePolicyDecision`.`Snssai_Sst`=? AND "
    "`SlicePolicyDecision`.`Snssai_Sd`=? AND "
    "`SlicePolicyDecision`.`Snssai_SdIsSet`=?";

const char access::object_traits_impl<
    ::oai::pcf::provisioning::model::SlicePolicyDecision,
    id_mysql>::update_statement[] =
    "UPDATE `SlicePolicyDecision` "
    "SET "
    "`SnssaiIsSet`=?, "
    "`PccRuleIdsIsSet`=? "
    "WHERE `Snssai_Sst`=? AND `Snssai_Sd`=? AND `Snssai_SdIsSet`=?";

const char access::object_traits_impl<
    ::oai::pcf::provisioning::model::SlicePolicyDecision,
    id_mysql>::erase_statement[] =
    "DELETE FROM `SlicePolicyDecision` "
    "WHERE `Snssai_Sst`=? AND `Snssai_Sd`=? AND `Snssai_SdIsSet`=?";

const char access::object_traits_impl<
    ::oai::pcf::provisioning::model::SlicePolicyDecision,
    id_mysql>::query_statement[] =
    "SELECT "
    "`SlicePolicyDecision`.`Snssai_Sst`, "
    "`SlicePolicyDecision`.`Snssai_Sd`, "
    "`SlicePolicyDecision`.`Snssai_SdIsSet`, "
    "`SlicePolicyDecision`.`SnssaiIsSet`, "
    "`SlicePolicyDecision`.`PccRuleIdsIsSet` "
    "FROM `SlicePolicyDecision`";

const char access::object_traits_impl<
    ::oai::pcf::provisioning::model::SlicePolicyDecision,
    id_mysql>::erase_query_statement[] = "DELETE FROM `SlicePolicyDecision`";

const char access::object_traits_impl<
    ::oai::pcf::provisioning::model::SlicePolicyDecision,
    id_mysql>::table_name[] = "`SlicePolicyDecision`";

void access::object_traits_impl<
    ::oai::pcf::provisioning::model::SlicePolicyDecision,
    id_mysql>::persist(database& db, const object_type& obj) {
  using namespace mysql;

  mysql::connection& conn(mysql::transaction::current().connection(db));
  statements_type& sts(conn.statement_cache().find_object<object_type>());

  callback(db, obj, callback_event::pre_persist);

  image_type& im(sts.image());
  binding& imb(sts.insert_image_binding());

  if (init(im, obj, statement_insert)) im.version++;

  if (im.version != sts.insert_image_version() || imb.version == 0) {
    bind(imb.bind, im, statement_insert);
    sts.insert_image_version(im.version);
    imb.version++;
  }

  insert_statement& st(sts.persist_statement());
  if (!st.execute()) throw object_already_persistent();

  id_image_type& i(sts.id_image());
  init(i, id(obj));

  binding& idb(sts.id_image_binding());
  if (i.version != sts.id_image_version() || idb.version == 0) {
    bind(idb.bind, i);
    sts.id_image_version(i.version);
    idb.version++;
  }

  extra_statement_cache_type& esc(sts.extra_statement_cache());

  // m_PccRuleIds
  //
  {
    ::std::vector< ::std::basic_string<char> > const& v = obj.m_PccRuleIds;

    PccRuleIds_traits::persist(v, esc.m_PccRuleIds);
  }

  callback(db, obj, callback_event::post_persist);
}

void access::object_traits_impl<
    ::oai::pcf::provisioning::model::SlicePolicyDecision,
    id_mysql>::update(database& db, const object_type& obj) {
  ODB_POTENTIALLY_UNUSED(db);

  using namespace mysql;
  using mysql::update_statement;

  callback(db, obj, callback_event::pre_update);

  mysql::transaction& tr(mysql::transaction::current());
  mysql::connection& conn(tr.connection(db));
  statements_type& sts(conn.statement_cache().find_object<object_type>());

  id_image_type& idi(sts.id_image());
  init(idi, id(obj));

  image_type& im(sts.image());
  if (init(im, obj, statement_update)) im.version++;

  bool u(false);
  binding& imb(sts.update_image_binding());
  if (im.version != sts.update_image_version() || imb.version == 0) {
    bind(imb.bind, im, statement_update);
    sts.update_image_version(im.version);
    imb.version++;
    u = true;
  }

  binding& idb(sts.id_image_binding());
  if (idi.version != sts.update_id_image_version() || idb.version == 0) {
    if (idi.version != sts.id_image_version() || idb.version == 0) {
      bind(idb.bind, idi);
      sts.id_image_version(idi.version);
      idb.version++;
    }

    sts.update_id_image_version(idi.version);

    if (!u) imb.version++;
  }

  update_statement& st(sts.update_statement());
  if (st.execute() == 0) throw object_not_persistent();

  extra_statement_cache_type& esc(sts.extra_statement_cache());

  // m_PccRuleIds
  //
  {
    ::std::vector< ::std::basic_string<char> > const& v = obj.m_PccRuleIds;

    PccRuleIds_traits::update(v, esc.m_PccRuleIds);
  }

  callback(db, obj, callback_event::post_update);
  pointer_cache_traits::update(db, obj);
}

void access::object_traits_impl<
    ::oai::pcf::provisioning::model::SlicePolicyDecision,
    id_mysql>::erase(database& db, const id_type& id) {
  using namespace mysql;

  mysql::connection& conn(mysql::transaction::current().connection(db));
  statements_type& sts(conn.statement_cache().find_object<object_type>());

  id_image_type& i(sts.id_image());
  init(i, id);

  binding& idb(sts.id_image_binding());
  if (i.version != sts.id_image_version() || idb.version == 0) {
    bind(idb.bind, i);
    sts.id_image_version(i.version);
    idb.version++;
  }

  extra_statement_cache_type& esc(sts.extra_statement_cache());

  // m_PccRuleIds
  //
  { PccRuleIds_traits::erase(esc.m_PccRuleIds); }

  if (sts.erase_statement().execute() != 1) throw object_not_persistent();

  pointer_cache_traits::erase(db, id);
}

access::object_traits_impl<
    ::oai::pcf::provisioning::model::SlicePolicyDecision,
    id_mysql>::pointer_type
access::object_traits_impl<
    ::oai::pcf::provisioning::model::SlicePolicyDecision,
    id_mysql>::find(database& db, const id_type& id) {
  using namespace mysql;

  {
    pointer_type p(pointer_cache_traits::find(db, id));

    if (!pointer_traits::null_ptr(p)) return p;
  }

  mysql::connection& conn(mysql::transaction::current().connection(db));
  statements_type& sts(conn.statement_cache().find_object<object_type>());

  statements_type::auto_lock l(sts);

  if (l.locked()) {
    if (!find_(sts, &id)) return pointer_type();
  }

  pointer_type p(access::object_factory<object_type, pointer_type>::create());
  pointer_traits::guard pg(p);

  pointer_cache_traits::insert_guard ig(
      pointer_cache_traits::insert(db, id, p));

  object_type& obj(pointer_traits::get_ref(p));

  if (l.locked()) {
    select_statement& st(sts.find_statement());
    ODB_POTENTIALLY_UNUSED(st);

    callback(db, obj, callback_event::pre_load);
    init(obj, sts.image(), &db);
    load_(sts, obj, false);
    sts.load_delayed(0);
    l.unlock();
    callback(db, obj, callback_event::post_load);
    pointer_cache_traits::load(ig.position());
  } else
    sts.delay_load(id, obj, ig.position());

  ig.release();
  pg.release();
  return p;
}

bool access::object_traits_impl<
    ::oai::pcf::provisioning::model::SlicePolicyDecision,
    id_mysql>::find(database& db, const id_type& id, object_type& obj) {
  using namespace mysql;

  mysql::connection& conn(mysql::transaction::current().connection(db));
  statements_type& sts(conn.statement_cache().find_object<object_type>());

  statements_type::auto_lock l(sts);
  assert(l.locked()) /* Must be a top-level call. */;

  if (!find_(sts, &id)) return false;

  select_statement& st(sts.find_statement());
  ODB_POTENTIALLY_UNUSED(st);

  reference_cache_traits::position_type pos(
      reference_cache_traits::insert(db, id, obj));
  reference_cache_traits::insert_guard ig(pos);

  callback(db, obj, callback_event::pre_load);
  init(obj, sts.image(), &db);
  load_(sts, obj, false);
  sts.load_delayed(0);
  l.unlock();
  callback(db, obj, callback_event::post_load);
  reference_cache_traits::load(pos);
  ig.release();
  return true;
}

bool access::object_traits_impl<
    ::oai::pcf::provisioning::model::SlicePolicyDecision,
    id_mysql>::reload(database& db, object_type& obj) {
  using namespace mysql;

  mysql::connection& conn(mysql::transaction::current().connection(db));
  statements_type& sts(conn.statement_cache().find_object<object_type>());

  statements_type::auto_lock l(sts);
  assert(l.locked()) /* Must be a top-level call. */;

  const id_type& id(object_traits_impl::id(obj));
  if (!find_(sts, &id)) return false;

  select_statement& st(sts.find_statement());
  ODB_POTENTIALLY_UNUSED(st);

  callback(db, obj, callback_event::pre_load);
  init(obj, sts.image(), &db);
  load_(sts, obj, true);
  sts.load_delayed(0);
  l.unlock();
  callback(db, obj, callback_event::post_load);
  return true;
}

bool access::object_traits_impl<
    ::oai::pcf::provisioning::model::SlicePolicyDecision,
    id_mysql>::find_(statements_type& sts, const id_type* id) {
  using namespace mysql;

  id_image_type& i(sts.id_image());
  init(i, *id);

  binding& idb(sts.id_image_binding());
  if (i.version != sts.id_image_version() || idb.version == 0) {
    bind(idb.bind, i);
    sts.id_image_version(i.version);
    idb.version++;
  }

  image_type& im(sts.image());
  binding& imb(sts.select_image_binding());

  if (im.version != sts.select_image_version() || imb.version == 0) {
    bind(imb.bind, im, statement_select);
    sts.select_image_version(im.version);
    imb.version++;
  }

  select_statement& st(sts.find_statement());

  st.execute();
  auto_result ar(st);
  select_statement::result r(st.fetch());

  if (r == select_statement::truncated) {
    if (grow(im, sts.select_image_truncated())) im.version++;

    if (im.version != sts.select_image_version()) {
      bind(imb.bind, im, statement_select);
      sts.select_image_version(im.version);
      imb.version++;
      st.refetch();
    }
  }

  return r != select_statement::no_data;
}

void access::object_traits_impl<
    ::oai::pcf::provisioning::model::SlicePolicyDecision,
    id_mysql>::load_(statements_type& sts, object_type& obj, bool reload) {
  ODB_POTENTIALLY_UNUSED(reload);

  extra_statement_cache_type& esc(sts.extra_statement_cache());

  // m_PccRuleIds
  //
  {
    ::std::vector< ::std::basic_string<char> >& v = obj.m_PccRuleIds;

    PccRuleIds_traits::load(v, esc.m_PccRuleIds);
  }
}

result<access::object_traits_impl<
    ::oai::pcf::provisioning::model::SlicePolicyDecision,
    id_mysql>::object_type>
access::object_traits_impl<
    ::oai::pcf::provisioning::model::SlicePolicyDecision,
    id_mysql>::query(database& db, const query_base_type& q) {
  using namespace mysql;
  using odb::details::shared;
  using odb::details::shared_ptr;

  mysql::connection& conn(mysql::transaction::current().connection(db));

  statements_type& sts(conn.statement_cache().find_object<object_type>());

  image_type& im(sts.image());
  binding& imb(sts.select_image_binding());

  if (im.version != sts.select_image_version() || imb.version == 0) {
    bind(imb.bind, im, statement_select);
    sts.select_image_version(im.version);
    imb.version++;
  }

  std::string text(query_statement);
  if (!q.empty()) {
    text += " ";
    text += q.clause();
  }

  q.init_parameters();
  shared_ptr<select_statement> st(new (shared) select_statement(
      conn, text, false, true, q.parameters_binding(), imb));

  st->execute();

  shared_ptr<odb::object_result_impl<object_type> > r(
      new (shared) mysql::object_result_impl<object_type>(q, st, sts, 0));

  return result<object_type>(r);
}

unsigned long long access::object_traits_impl<
    ::oai::pcf::provisioning::model::SlicePolicyDecision,
    id_mysql>::erase_query(database& db, const query_base_type& q) {
  using namespace mysql;

  mysql::connection& conn(mysql::transaction::current().connection(db));

  std::string text(erase_query_statement);
  if (!q.empty()) {
    text += ' ';
    text += q.clause();
  }

  q.init_parameters();
  delete_statement st(conn, text, q.parameters_binding());

  return st.execute();
}
}  // namespace odb

#include <odb/post.hxx>
