/**
 * Policy Decisions API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * SlicePolicyDecision.h
 *
 *
 */

#ifndef SlicePolicyDecision_H_
#define SlicePolicyDecision_H_

#include <string>
#include <vector>
#include <nlohmann/json.hpp>
#include "Snssai.h"
#ifdef USE_ODB
#include <odb/core.hxx>
#endif

namespace oai::pcf::provisioning::model {

/// <summary>
///
/// </summary>
#ifdef USE_ODB
#pragma db object
#endif
class SlicePolicyDecision {
 public:
  SlicePolicyDecision();
  virtual ~SlicePolicyDecision() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const SlicePolicyDecision& rhs) const;
  bool operator!=(const SlicePolicyDecision& rhs) const;

  /////////////////////////////////////////////
  /// SlicePolicyDecision members

  /// <summary>
  ///
  /// </summary>
  oai::_3gpp::model::Snssai getSnssai() const;
  void setSnssai(oai::_3gpp::model::Snssai const& value);
  bool snssaiIsSet() const;
  void unsetSnssai();
  /// <summary>
  ///
  /// </summary>
  std::vector<std::string> getPccRuleIds() const;
  void setPccRuleIds(std::vector<std::string> const& value);
  bool pccRuleIdsIsSet() const;
  void unsetPccRuleIds();

  friend void to_json(nlohmann::json& j, const SlicePolicyDecision& o);
  friend void from_json(const nlohmann::json& j, SlicePolicyDecision& o);

 protected:
#ifdef USE_ODB
#pragma db id
  oai::_3gpp::model::Snssai m_Snssai;
  bool m_SnssaiIsSet;
  std::vector<std::string> m_PccRuleIds;
  bool m_PccRuleIdsIsSet;

 private:
#ifdef USE_ODB
  friend class odb::access;
#endif
};

}  // namespace oai::pcf::provisioning::model

#endif /* SlicePolicyDecision_H_ */
