/**
 * Policy Decisions API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "SlicePolicyDecision.h"
#include "Helpers.h"

#include <sstream>

namespace oai::pcf::provisioning::model {

SlicePolicyDecision::SlicePolicyDecision() {
  m_SnssaiIsSet     = false;
  m_PccRuleIdsIsSet = false;
}

void SlicePolicyDecision::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::model::common::helpers::ValidationException(msg.str());
  }
}

bool SlicePolicyDecision::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool SlicePolicyDecision::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "SlicePolicyDecision" : pathPrefix;

  if (pccRuleIdsIsSet()) {
    const std::vector<std::string>& value = m_PccRuleIds;
    const std::string currentValuePath    = _pathPrefix + ".pccRuleIds";

    {  // Recursive validation of array elements
      const std::string oldValuePath = currentValuePath;
      int i                          = 0;
      for (const std::string& value : value) {
        const std::string currentValuePath =
            oldValuePath + "[" + std::to_string(i) + "]";

        i++;
      }
    }
  }

  return success;
}

bool SlicePolicyDecision::operator==(const SlicePolicyDecision& rhs) const {
  return

      ((!snssaiIsSet() && !rhs.snssaiIsSet()) ||
       (snssaiIsSet() && rhs.snssaiIsSet() &&
        getSnssai() == rhs.getSnssai())) &&

      ((!pccRuleIdsIsSet() && !rhs.pccRuleIdsIsSet()) ||
       (pccRuleIdsIsSet() && rhs.pccRuleIdsIsSet() &&
        getPccRuleIds() == rhs.getPccRuleIds()))

          ;
}

bool SlicePolicyDecision::operator!=(const SlicePolicyDecision& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const SlicePolicyDecision& o) {
  j = nlohmann::json();
  if (o.snssaiIsSet()) j["snssai"] = o.m_Snssai;
  if (o.pccRuleIdsIsSet() || !o.m_PccRuleIds.empty())
    j["pccRuleIds"] = o.m_PccRuleIds;
}

void from_json(const nlohmann::json& j, SlicePolicyDecision& o) {
  if (j.find("snssai") != j.end()) {
    j.at("snssai").get_to(o.m_Snssai);
    o.m_SnssaiIsSet = true;
  }
  if (j.find("pccRuleIds") != j.end()) {
    j.at("pccRuleIds").get_to(o.m_PccRuleIds);
    o.m_PccRuleIdsIsSet = true;
  }
}

oai::model::common::Snssai SlicePolicyDecision::getSnssai() const {
  return m_Snssai;
}
void SlicePolicyDecision::setSnssai(oai::model::common::Snssai const& value) {
  m_Snssai      = value;
  m_SnssaiIsSet = true;
}
bool SlicePolicyDecision::snssaiIsSet() const {
  return m_SnssaiIsSet;
}
void SlicePolicyDecision::unsetSnssai() {
  m_SnssaiIsSet = false;
}
std::vector<std::string> SlicePolicyDecision::getPccRuleIds() const {
  return m_PccRuleIds;
}
void SlicePolicyDecision::setPccRuleIds(std::vector<std::string> const& value) {
  m_PccRuleIds      = value;
  m_PccRuleIdsIsSet = true;
}
bool SlicePolicyDecision::pccRuleIdsIsSet() const {
  return m_PccRuleIdsIsSet;
}
void SlicePolicyDecision::unsetPccRuleIds() {
  m_PccRuleIdsIsSet = false;
}

}  // namespace oai::pcf::provisioning::model
