// -*- C++ -*-
//
// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

namespace odb {}

namespace odb {
// Snssai
//

inline bool access::composite_value_traits<
    ::oai::model::common::Snssai, id_mysql>::get_null(const image_type& i) {
  bool r(true);
  r = r && i.m_Sst_null;
  r = r && i.m_Sd_null;
  r = r && i.m_SdIsSet_null;
  return r;
}

inline void access::composite_value_traits<
    ::oai::model::common::Snssai,
    id_mysql>::set_null(image_type& i, mysql::statement_kind sk) {
  ODB_POTENTIALLY_UNUSED(sk);

  using namespace mysql;

  i.m_Sst_null     = 1;
  i.m_Sd_null      = 1;
  i.m_SdIsSet_null = 1;
}
}  // namespace odb
