/**
 * Policy Decisions API
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * SupiPolicyDecision.h
 *
 *
 */

#ifndef SupiPolicyDecision_H_
#define SupiPolicyDecision_H_

#include <string>
#include <vector>
#include <nlohmann/json.hpp>
#include <odb/core.hxx>

namespace oai::pcf::provisioning::model {

/// <summary>
///
/// </summary>
#pragma db object
class SupiPolicyDecision {
 public:
  SupiPolicyDecision();
  virtual ~SupiPolicyDecision() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const SupiPolicyDecision& rhs) const;
  bool operator!=(const SupiPolicyDecision& rhs) const;

  /////////////////////////////////////////////
  /// SupiPolicyDecision members

  /// <summary>
  ///
  /// </summary>
  std::string getSupi() const;
  void setSupi(std::string const& value);
  bool supiIsSet() const;
  void unsetSupi();
  /// <summary>
  ///
  /// </summary>
  std::vector<std::string> getPccRuleIds() const;
  void setPccRuleIds(std::vector<std::string> const& value);
  bool pccRuleIdsIsSet() const;
  void unsetPccRuleIds();

  friend void to_json(nlohmann::json& j, const SupiPolicyDecision& o);
  friend void from_json(const nlohmann::json& j, SupiPolicyDecision& o);

 protected:
#pragma db id
  std::string m_Supi;
  bool m_SupiIsSet;
  std::vector<std::string> m_PccRuleIds;
  bool m_PccRuleIdsIsSet;

 private:
  friend class odb::access;
};

}  // namespace oai::pcf::provisioning::model

#endif /* SupiPolicyDecision_H_ */
