/**
 * Npcf_SMPolicyControl API
 * Session Management Policy Control Service © 2023, 3GPP Organizational
 * Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.9
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * TrafficControlData.h
 *
 *
 */

#ifndef TrafficControlDataODB_H_
#define TrafficControlDataODB_H_

#include <string>
#include <vector>
#include <nlohmann/json.hpp>

namespace oai::pcf::provisioning::model {

/// <summary>
///
/// </summary>
#pragma db object
class TrafficControlDataODB {
 public:
  TrafficControlDataODB();
  virtual ~TrafficControlDataODB() = default;

  bool operator==(const TrafficControlDataODB& rhs) const;
  bool operator!=(const TrafficControlDataODB& rhs) const;

  friend void to_json(nlohmann::json& j, const TrafficControlDataODB& o);
  friend void from_json(const nlohmann::json& j, TrafficControlDataODB& o);

#pragma db id
  std::string m_TcId;

  std::string m_FlowStatus;
  bool m_FlowStatusIsSet;
  std::string m_RedirectInfo;
  bool m_RedirectInfoIsSet;
  std::string m_AddRedirectInfo;
  bool m_AddRedirectInfoIsSet;
  bool m_MuteNotif;
  bool m_MuteNotifIsSet;
  std::string m_TrafficSteeringPolIdDl;
  bool m_TrafficSteeringPolIdDlIsSet;
  std::string m_TrafficSteeringPolIdUl;
  bool m_TrafficSteeringPolIdUlIsSet;
  std::string m_RouteToLocs;
  bool m_RouteToLocsIsSet;
  bool m_TraffCorreInd;
  bool m_TraffCorreIndIsSet;
  std::string m_UpPathChgEvent;
  bool m_UpPathChgEventIsSet;
  std::string m_SteerFun;
  bool m_SteerFunIsSet;
  std::string m_SteerModeDl;
  bool m_SteerModeDlIsSet;
  std::string m_SteerModeUl;
  bool m_SteerModeUlIsSet;
  std::string m_MulAccCtrl;
  bool m_MulAccCtrlIsSet;
};

}  // namespace oai::pcf::provisioning::model

#endif /* TrafficControlDataODB_H_ */
