// -*- C++ -*-
//
// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#include "TrafficControlDataODB-odb.hxx"

#include <cassert>
#include <cstring>  // std::memcpy

#include <odb/mysql/traits.hxx>
#include <odb/mysql/database.hxx>
#include <odb/mysql/transaction.hxx>
#include <odb/mysql/connection.hxx>
#include <odb/mysql/statement.hxx>
#include <odb/mysql/statement-cache.hxx>
#include <odb/mysql/simple-object-statements.hxx>
#include <odb/mysql/container-statements.hxx>
#include <odb/mysql/exceptions.hxx>
#include <odb/mysql/simple-object-result.hxx>
#include <odb/mysql/enum.hxx>

namespace odb {
// TrafficControlDataODB
//

struct access::object_traits_impl<
    ::oai::pcf::provisioning::model::TrafficControlDataODB,
    id_mysql>::extra_statement_cache_type {
  extra_statement_cache_type(
      mysql::connection&, image_type&, id_image_type&, mysql::binding&,
      mysql::binding&) {}
};

access::object_traits_impl<
    ::oai::pcf::provisioning::model::TrafficControlDataODB, id_mysql>::id_type
access::object_traits_impl<
    ::oai::pcf::provisioning::model::TrafficControlDataODB,
    id_mysql>::id(const image_type& i) {
  mysql::database* db(0);
  ODB_POTENTIALLY_UNUSED(db);

  id_type id;
  {
    mysql::value_traits< ::std::string, mysql::id_string>::set_value(
        id, i.m_TcId_value, i.m_TcId_size, i.m_TcId_null);
  }

  return id;
}

bool access::object_traits_impl<
    ::oai::pcf::provisioning::model::TrafficControlDataODB,
    id_mysql>::grow(image_type& i, my_bool* t) {
  ODB_POTENTIALLY_UNUSED(i);
  ODB_POTENTIALLY_UNUSED(t);

  bool grew(false);

  // m_TcId
  //
  if (t[0UL]) {
    i.m_TcId_value.capacity(i.m_TcId_size);
    grew = true;
  }

  // m_FlowStatus
  //
  if (t[1UL]) {
    i.m_FlowStatus_value.capacity(i.m_FlowStatus_size);
    grew = true;
  }

  // m_FlowStatusIsSet
  //
  t[2UL] = 0;

  // m_RedirectInfo
  //
  if (t[3UL]) {
    i.m_RedirectInfo_value.capacity(i.m_RedirectInfo_size);
    grew = true;
  }

  // m_RedirectInfoIsSet
  //
  t[4UL] = 0;

  // m_AddRedirectInfo
  //
  if (t[5UL]) {
    i.m_AddRedirectInfo_value.capacity(i.m_AddRedirectInfo_size);
    grew = true;
  }

  // m_AddRedirectInfoIsSet
  //
  t[6UL] = 0;

  // m_MuteNotif
  //
  t[7UL] = 0;

  // m_MuteNotifIsSet
  //
  t[8UL] = 0;

  // m_TrafficSteeringPolIdDl
  //
  if (t[9UL]) {
    i.m_TrafficSteeringPolIdDl_value.capacity(i.m_TrafficSteeringPolIdDl_size);
    grew = true;
  }

  // m_TrafficSteeringPolIdDlIsSet
  //
  t[10UL] = 0;

  // m_TrafficSteeringPolIdUl
  //
  if (t[11UL]) {
    i.m_TrafficSteeringPolIdUl_value.capacity(i.m_TrafficSteeringPolIdUl_size);
    grew = true;
  }

  // m_TrafficSteeringPolIdUlIsSet
  //
  t[12UL] = 0;

  // m_RouteToLocs
  //
  if (t[13UL]) {
    i.m_RouteToLocs_value.capacity(i.m_RouteToLocs_size);
    grew = true;
  }

  // m_RouteToLocsIsSet
  //
  t[14UL] = 0;

  // m_TraffCorreInd
  //
  t[15UL] = 0;

  // m_TraffCorreIndIsSet
  //
  t[16UL] = 0;

  // m_UpPathChgEvent
  //
  if (t[17UL]) {
    i.m_UpPathChgEvent_value.capacity(i.m_UpPathChgEvent_size);
    grew = true;
  }

  // m_UpPathChgEventIsSet
  //
  t[18UL] = 0;

  // m_SteerFun
  //
  if (t[19UL]) {
    i.m_SteerFun_value.capacity(i.m_SteerFun_size);
    grew = true;
  }

  // m_SteerFunIsSet
  //
  t[20UL] = 0;

  // m_SteerModeDl
  //
  if (t[21UL]) {
    i.m_SteerModeDl_value.capacity(i.m_SteerModeDl_size);
    grew = true;
  }

  // m_SteerModeDlIsSet
  //
  t[22UL] = 0;

  // m_SteerModeUl
  //
  if (t[23UL]) {
    i.m_SteerModeUl_value.capacity(i.m_SteerModeUl_size);
    grew = true;
  }

  // m_SteerModeUlIsSet
  //
  t[24UL] = 0;

  // m_MulAccCtrl
  //
  if (t[25UL]) {
    i.m_MulAccCtrl_value.capacity(i.m_MulAccCtrl_size);
    grew = true;
  }

  // m_MulAccCtrlIsSet
  //
  t[26UL] = 0;

  return grew;
}

void access::object_traits_impl<
    ::oai::pcf::provisioning::model::TrafficControlDataODB,
    id_mysql>::bind(MYSQL_BIND* b, image_type& i, mysql::statement_kind sk) {
  ODB_POTENTIALLY_UNUSED(sk);

  using namespace mysql;

  std::size_t n(0);

  // m_TcId
  //
  if (sk != statement_update) {
    b[n].buffer_type   = MYSQL_TYPE_STRING;
    b[n].buffer        = i.m_TcId_value.data();
    b[n].buffer_length = static_cast<unsigned long>(i.m_TcId_value.capacity());
    b[n].length        = &i.m_TcId_size;
    b[n].is_null       = &i.m_TcId_null;
    n++;
  }

  // m_FlowStatus
  //
  b[n].buffer_type = MYSQL_TYPE_STRING;
  b[n].buffer      = i.m_FlowStatus_value.data();
  b[n].buffer_length =
      static_cast<unsigned long>(i.m_FlowStatus_value.capacity());
  b[n].length  = &i.m_FlowStatus_size;
  b[n].is_null = &i.m_FlowStatus_null;
  n++;

  // m_FlowStatusIsSet
  //
  b[n].buffer_type = MYSQL_TYPE_TINY;
  b[n].is_unsigned = 0;
  b[n].buffer      = &i.m_FlowStatusIsSet_value;
  b[n].is_null     = &i.m_FlowStatusIsSet_null;
  n++;

  // m_RedirectInfo
  //
  b[n].buffer_type = MYSQL_TYPE_STRING;
  b[n].buffer      = i.m_RedirectInfo_value.data();
  b[n].buffer_length =
      static_cast<unsigned long>(i.m_RedirectInfo_value.capacity());
  b[n].length  = &i.m_RedirectInfo_size;
  b[n].is_null = &i.m_RedirectInfo_null;
  n++;

  // m_RedirectInfoIsSet
  //
  b[n].buffer_type = MYSQL_TYPE_TINY;
  b[n].is_unsigned = 0;
  b[n].buffer      = &i.m_RedirectInfoIsSet_value;
  b[n].is_null     = &i.m_RedirectInfoIsSet_null;
  n++;

  // m_AddRedirectInfo
  //
  b[n].buffer_type = MYSQL_TYPE_STRING;
  b[n].buffer      = i.m_AddRedirectInfo_value.data();
  b[n].buffer_length =
      static_cast<unsigned long>(i.m_AddRedirectInfo_value.capacity());
  b[n].length  = &i.m_AddRedirectInfo_size;
  b[n].is_null = &i.m_AddRedirectInfo_null;
  n++;

  // m_AddRedirectInfoIsSet
  //
  b[n].buffer_type = MYSQL_TYPE_TINY;
  b[n].is_unsigned = 0;
  b[n].buffer      = &i.m_AddRedirectInfoIsSet_value;
  b[n].is_null     = &i.m_AddRedirectInfoIsSet_null;
  n++;

  // m_MuteNotif
  //
  b[n].buffer_type = MYSQL_TYPE_TINY;
  b[n].is_unsigned = 0;
  b[n].buffer      = &i.m_MuteNotif_value;
  b[n].is_null     = &i.m_MuteNotif_null;
  n++;

  // m_MuteNotifIsSet
  //
  b[n].buffer_type = MYSQL_TYPE_TINY;
  b[n].is_unsigned = 0;
  b[n].buffer      = &i.m_MuteNotifIsSet_value;
  b[n].is_null     = &i.m_MuteNotifIsSet_null;
  n++;

  // m_TrafficSteeringPolIdDl
  //
  b[n].buffer_type = MYSQL_TYPE_STRING;
  b[n].buffer      = i.m_TrafficSteeringPolIdDl_value.data();
  b[n].buffer_length =
      static_cast<unsigned long>(i.m_TrafficSteeringPolIdDl_value.capacity());
  b[n].length  = &i.m_TrafficSteeringPolIdDl_size;
  b[n].is_null = &i.m_TrafficSteeringPolIdDl_null;
  n++;

  // m_TrafficSteeringPolIdDlIsSet
  //
  b[n].buffer_type = MYSQL_TYPE_TINY;
  b[n].is_unsigned = 0;
  b[n].buffer      = &i.m_TrafficSteeringPolIdDlIsSet_value;
  b[n].is_null     = &i.m_TrafficSteeringPolIdDlIsSet_null;
  n++;

  // m_TrafficSteeringPolIdUl
  //
  b[n].buffer_type = MYSQL_TYPE_STRING;
  b[n].buffer      = i.m_TrafficSteeringPolIdUl_value.data();
  b[n].buffer_length =
      static_cast<unsigned long>(i.m_TrafficSteeringPolIdUl_value.capacity());
  b[n].length  = &i.m_TrafficSteeringPolIdUl_size;
  b[n].is_null = &i.m_TrafficSteeringPolIdUl_null;
  n++;

  // m_TrafficSteeringPolIdUlIsSet
  //
  b[n].buffer_type = MYSQL_TYPE_TINY;
  b[n].is_unsigned = 0;
  b[n].buffer      = &i.m_TrafficSteeringPolIdUlIsSet_value;
  b[n].is_null     = &i.m_TrafficSteeringPolIdUlIsSet_null;
  n++;

  // m_RouteToLocs
  //
  b[n].buffer_type = MYSQL_TYPE_STRING;
  b[n].buffer      = i.m_RouteToLocs_value.data();
  b[n].buffer_length =
      static_cast<unsigned long>(i.m_RouteToLocs_value.capacity());
  b[n].length  = &i.m_RouteToLocs_size;
  b[n].is_null = &i.m_RouteToLocs_null;
  n++;

  // m_RouteToLocsIsSet
  //
  b[n].buffer_type = MYSQL_TYPE_TINY;
  b[n].is_unsigned = 0;
  b[n].buffer      = &i.m_RouteToLocsIsSet_value;
  b[n].is_null     = &i.m_RouteToLocsIsSet_null;
  n++;

  // m_TraffCorreInd
  //
  b[n].buffer_type = MYSQL_TYPE_TINY;
  b[n].is_unsigned = 0;
  b[n].buffer      = &i.m_TraffCorreInd_value;
  b[n].is_null     = &i.m_TraffCorreInd_null;
  n++;

  // m_TraffCorreIndIsSet
  //
  b[n].buffer_type = MYSQL_TYPE_TINY;
  b[n].is_unsigned = 0;
  b[n].buffer      = &i.m_TraffCorreIndIsSet_value;
  b[n].is_null     = &i.m_TraffCorreIndIsSet_null;
  n++;

  // m_UpPathChgEvent
  //
  b[n].buffer_type = MYSQL_TYPE_STRING;
  b[n].buffer      = i.m_UpPathChgEvent_value.data();
  b[n].buffer_length =
      static_cast<unsigned long>(i.m_UpPathChgEvent_value.capacity());
  b[n].length  = &i.m_UpPathChgEvent_size;
  b[n].is_null = &i.m_UpPathChgEvent_null;
  n++;

  // m_UpPathChgEventIsSet
  //
  b[n].buffer_type = MYSQL_TYPE_TINY;
  b[n].is_unsigned = 0;
  b[n].buffer      = &i.m_UpPathChgEventIsSet_value;
  b[n].is_null     = &i.m_UpPathChgEventIsSet_null;
  n++;

  // m_SteerFun
  //
  b[n].buffer_type = MYSQL_TYPE_STRING;
  b[n].buffer      = i.m_SteerFun_value.data();
  b[n].buffer_length =
      static_cast<unsigned long>(i.m_SteerFun_value.capacity());
  b[n].length  = &i.m_SteerFun_size;
  b[n].is_null = &i.m_SteerFun_null;
  n++;

  // m_SteerFunIsSet
  //
  b[n].buffer_type = MYSQL_TYPE_TINY;
  b[n].is_unsigned = 0;
  b[n].buffer      = &i.m_SteerFunIsSet_value;
  b[n].is_null     = &i.m_SteerFunIsSet_null;
  n++;

  // m_SteerModeDl
  //
  b[n].buffer_type = MYSQL_TYPE_STRING;
  b[n].buffer      = i.m_SteerModeDl_value.data();
  b[n].buffer_length =
      static_cast<unsigned long>(i.m_SteerModeDl_value.capacity());
  b[n].length  = &i.m_SteerModeDl_size;
  b[n].is_null = &i.m_SteerModeDl_null;
  n++;

  // m_SteerModeDlIsSet
  //
  b[n].buffer_type = MYSQL_TYPE_TINY;
  b[n].is_unsigned = 0;
  b[n].buffer      = &i.m_SteerModeDlIsSet_value;
  b[n].is_null     = &i.m_SteerModeDlIsSet_null;
  n++;

  // m_SteerModeUl
  //
  b[n].buffer_type = MYSQL_TYPE_STRING;
  b[n].buffer      = i.m_SteerModeUl_value.data();
  b[n].buffer_length =
      static_cast<unsigned long>(i.m_SteerModeUl_value.capacity());
  b[n].length  = &i.m_SteerModeUl_size;
  b[n].is_null = &i.m_SteerModeUl_null;
  n++;

  // m_SteerModeUlIsSet
  //
  b[n].buffer_type = MYSQL_TYPE_TINY;
  b[n].is_unsigned = 0;
  b[n].buffer      = &i.m_SteerModeUlIsSet_value;
  b[n].is_null     = &i.m_SteerModeUlIsSet_null;
  n++;

  // m_MulAccCtrl
  //
  b[n].buffer_type = MYSQL_TYPE_STRING;
  b[n].buffer      = i.m_MulAccCtrl_value.data();
  b[n].buffer_length =
      static_cast<unsigned long>(i.m_MulAccCtrl_value.capacity());
  b[n].length  = &i.m_MulAccCtrl_size;
  b[n].is_null = &i.m_MulAccCtrl_null;
  n++;

  // m_MulAccCtrlIsSet
  //
  b[n].buffer_type = MYSQL_TYPE_TINY;
  b[n].is_unsigned = 0;
  b[n].buffer      = &i.m_MulAccCtrlIsSet_value;
  b[n].is_null     = &i.m_MulAccCtrlIsSet_null;
  n++;
}

void access::object_traits_impl<
    ::oai::pcf::provisioning::model::TrafficControlDataODB,
    id_mysql>::bind(MYSQL_BIND* b, id_image_type& i) {
  std::size_t n(0);
  b[n].buffer_type   = MYSQL_TYPE_STRING;
  b[n].buffer        = i.id_value.data();
  b[n].buffer_length = static_cast<unsigned long>(i.id_value.capacity());
  b[n].length        = &i.id_size;
  b[n].is_null       = &i.id_null;
}

bool access::object_traits_impl<
    ::oai::pcf::provisioning::model::TrafficControlDataODB, id_mysql>::
    init(image_type& i, const object_type& o, mysql::statement_kind sk) {
  ODB_POTENTIALLY_UNUSED(i);
  ODB_POTENTIALLY_UNUSED(o);
  ODB_POTENTIALLY_UNUSED(sk);

  using namespace mysql;

  bool grew(false);

  // m_TcId
  //
  if (sk == statement_insert) {
    ::std::string const& v = o.m_TcId;

    bool is_null(false);
    std::size_t size(0);
    std::size_t cap(i.m_TcId_value.capacity());
    mysql::value_traits< ::std::string, mysql::id_string>::set_image(
        i.m_TcId_value, size, is_null, v);
    i.m_TcId_null = is_null;
    i.m_TcId_size = static_cast<unsigned long>(size);
    grew          = grew || (cap != i.m_TcId_value.capacity());
  }

  // m_FlowStatus
  //
  {
    ::std::string const& v = o.m_FlowStatus;

    bool is_null(false);
    std::size_t size(0);
    std::size_t cap(i.m_FlowStatus_value.capacity());
    mysql::value_traits< ::std::string, mysql::id_string>::set_image(
        i.m_FlowStatus_value, size, is_null, v);
    i.m_FlowStatus_null = is_null;
    i.m_FlowStatus_size = static_cast<unsigned long>(size);
    grew                = grew || (cap != i.m_FlowStatus_value.capacity());
  }

  // m_FlowStatusIsSet
  //
  {
    bool const& v = o.m_FlowStatusIsSet;

    bool is_null(false);
    mysql::value_traits<bool, mysql::id_tiny>::set_image(
        i.m_FlowStatusIsSet_value, is_null, v);
    i.m_FlowStatusIsSet_null = is_null;
  }

  // m_RedirectInfo
  //
  {
    ::std::string const& v = o.m_RedirectInfo;

    bool is_null(false);
    std::size_t size(0);
    std::size_t cap(i.m_RedirectInfo_value.capacity());
    mysql::value_traits< ::std::string, mysql::id_string>::set_image(
        i.m_RedirectInfo_value, size, is_null, v);
    i.m_RedirectInfo_null = is_null;
    i.m_RedirectInfo_size = static_cast<unsigned long>(size);
    grew                  = grew || (cap != i.m_RedirectInfo_value.capacity());
  }

  // m_RedirectInfoIsSet
  //
  {
    bool const& v = o.m_RedirectInfoIsSet;

    bool is_null(false);
    mysql::value_traits<bool, mysql::id_tiny>::set_image(
        i.m_RedirectInfoIsSet_value, is_null, v);
    i.m_RedirectInfoIsSet_null = is_null;
  }

  // m_AddRedirectInfo
  //
  {
    ::std::string const& v = o.m_AddRedirectInfo;

    bool is_null(false);
    std::size_t size(0);
    std::size_t cap(i.m_AddRedirectInfo_value.capacity());
    mysql::value_traits< ::std::string, mysql::id_string>::set_image(
        i.m_AddRedirectInfo_value, size, is_null, v);
    i.m_AddRedirectInfo_null = is_null;
    i.m_AddRedirectInfo_size = static_cast<unsigned long>(size);
    grew = grew || (cap != i.m_AddRedirectInfo_value.capacity());
  }

  // m_AddRedirectInfoIsSet
  //
  {
    bool const& v = o.m_AddRedirectInfoIsSet;

    bool is_null(false);
    mysql::value_traits<bool, mysql::id_tiny>::set_image(
        i.m_AddRedirectInfoIsSet_value, is_null, v);
    i.m_AddRedirectInfoIsSet_null = is_null;
  }

  // m_MuteNotif
  //
  {
    bool const& v = o.m_MuteNotif;

    bool is_null(false);
    mysql::value_traits<bool, mysql::id_tiny>::set_image(
        i.m_MuteNotif_value, is_null, v);
    i.m_MuteNotif_null = is_null;
  }

  // m_MuteNotifIsSet
  //
  {
    bool const& v = o.m_MuteNotifIsSet;

    bool is_null(false);
    mysql::value_traits<bool, mysql::id_tiny>::set_image(
        i.m_MuteNotifIsSet_value, is_null, v);
    i.m_MuteNotifIsSet_null = is_null;
  }

  // m_TrafficSteeringPolIdDl
  //
  {
    ::std::string const& v = o.m_TrafficSteeringPolIdDl;

    bool is_null(false);
    std::size_t size(0);
    std::size_t cap(i.m_TrafficSteeringPolIdDl_value.capacity());
    mysql::value_traits< ::std::string, mysql::id_string>::set_image(
        i.m_TrafficSteeringPolIdDl_value, size, is_null, v);
    i.m_TrafficSteeringPolIdDl_null = is_null;
    i.m_TrafficSteeringPolIdDl_size = static_cast<unsigned long>(size);
    grew = grew || (cap != i.m_TrafficSteeringPolIdDl_value.capacity());
  }

  // m_TrafficSteeringPolIdDlIsSet
  //
  {
    bool const& v = o.m_TrafficSteeringPolIdDlIsSet;

    bool is_null(false);
    mysql::value_traits<bool, mysql::id_tiny>::set_image(
        i.m_TrafficSteeringPolIdDlIsSet_value, is_null, v);
    i.m_TrafficSteeringPolIdDlIsSet_null = is_null;
  }

  // m_TrafficSteeringPolIdUl
  //
  {
    ::std::string const& v = o.m_TrafficSteeringPolIdUl;

    bool is_null(false);
    std::size_t size(0);
    std::size_t cap(i.m_TrafficSteeringPolIdUl_value.capacity());
    mysql::value_traits< ::std::string, mysql::id_string>::set_image(
        i.m_TrafficSteeringPolIdUl_value, size, is_null, v);
    i.m_TrafficSteeringPolIdUl_null = is_null;
    i.m_TrafficSteeringPolIdUl_size = static_cast<unsigned long>(size);
    grew = grew || (cap != i.m_TrafficSteeringPolIdUl_value.capacity());
  }

  // m_TrafficSteeringPolIdUlIsSet
  //
  {
    bool const& v = o.m_TrafficSteeringPolIdUlIsSet;

    bool is_null(false);
    mysql::value_traits<bool, mysql::id_tiny>::set_image(
        i.m_TrafficSteeringPolIdUlIsSet_value, is_null, v);
    i.m_TrafficSteeringPolIdUlIsSet_null = is_null;
  }

  // m_RouteToLocs
  //
  {
    ::std::string const& v = o.m_RouteToLocs;

    bool is_null(false);
    std::size_t size(0);
    std::size_t cap(i.m_RouteToLocs_value.capacity());
    mysql::value_traits< ::std::string, mysql::id_string>::set_image(
        i.m_RouteToLocs_value, size, is_null, v);
    i.m_RouteToLocs_null = is_null;
    i.m_RouteToLocs_size = static_cast<unsigned long>(size);
    grew                 = grew || (cap != i.m_RouteToLocs_value.capacity());
  }

  // m_RouteToLocsIsSet
  //
  {
    bool const& v = o.m_RouteToLocsIsSet;

    bool is_null(false);
    mysql::value_traits<bool, mysql::id_tiny>::set_image(
        i.m_RouteToLocsIsSet_value, is_null, v);
    i.m_RouteToLocsIsSet_null = is_null;
  }

  // m_TraffCorreInd
  //
  {
    bool const& v = o.m_TraffCorreInd;

    bool is_null(false);
    mysql::value_traits<bool, mysql::id_tiny>::set_image(
        i.m_TraffCorreInd_value, is_null, v);
    i.m_TraffCorreInd_null = is_null;
  }

  // m_TraffCorreIndIsSet
  //
  {
    bool const& v = o.m_TraffCorreIndIsSet;

    bool is_null(false);
    mysql::value_traits<bool, mysql::id_tiny>::set_image(
        i.m_TraffCorreIndIsSet_value, is_null, v);
    i.m_TraffCorreIndIsSet_null = is_null;
  }

  // m_UpPathChgEvent
  //
  {
    ::std::string const& v = o.m_UpPathChgEvent;

    bool is_null(false);
    std::size_t size(0);
    std::size_t cap(i.m_UpPathChgEvent_value.capacity());
    mysql::value_traits< ::std::string, mysql::id_string>::set_image(
        i.m_UpPathChgEvent_value, size, is_null, v);
    i.m_UpPathChgEvent_null = is_null;
    i.m_UpPathChgEvent_size = static_cast<unsigned long>(size);
    grew = grew || (cap != i.m_UpPathChgEvent_value.capacity());
  }

  // m_UpPathChgEventIsSet
  //
  {
    bool const& v = o.m_UpPathChgEventIsSet;

    bool is_null(false);
    mysql::value_traits<bool, mysql::id_tiny>::set_image(
        i.m_UpPathChgEventIsSet_value, is_null, v);
    i.m_UpPathChgEventIsSet_null = is_null;
  }

  // m_SteerFun
  //
  {
    ::std::string const& v = o.m_SteerFun;

    bool is_null(false);
    std::size_t size(0);
    std::size_t cap(i.m_SteerFun_value.capacity());
    mysql::value_traits< ::std::string, mysql::id_string>::set_image(
        i.m_SteerFun_value, size, is_null, v);
    i.m_SteerFun_null = is_null;
    i.m_SteerFun_size = static_cast<unsigned long>(size);
    grew              = grew || (cap != i.m_SteerFun_value.capacity());
  }

  // m_SteerFunIsSet
  //
  {
    bool const& v = o.m_SteerFunIsSet;

    bool is_null(false);
    mysql::value_traits<bool, mysql::id_tiny>::set_image(
        i.m_SteerFunIsSet_value, is_null, v);
    i.m_SteerFunIsSet_null = is_null;
  }

  // m_SteerModeDl
  //
  {
    ::std::string const& v = o.m_SteerModeDl;

    bool is_null(false);
    std::size_t size(0);
    std::size_t cap(i.m_SteerModeDl_value.capacity());
    mysql::value_traits< ::std::string, mysql::id_string>::set_image(
        i.m_SteerModeDl_value, size, is_null, v);
    i.m_SteerModeDl_null = is_null;
    i.m_SteerModeDl_size = static_cast<unsigned long>(size);
    grew                 = grew || (cap != i.m_SteerModeDl_value.capacity());
  }

  // m_SteerModeDlIsSet
  //
  {
    bool const& v = o.m_SteerModeDlIsSet;

    bool is_null(false);
    mysql::value_traits<bool, mysql::id_tiny>::set_image(
        i.m_SteerModeDlIsSet_value, is_null, v);
    i.m_SteerModeDlIsSet_null = is_null;
  }

  // m_SteerModeUl
  //
  {
    ::std::string const& v = o.m_SteerModeUl;

    bool is_null(false);
    std::size_t size(0);
    std::size_t cap(i.m_SteerModeUl_value.capacity());
    mysql::value_traits< ::std::string, mysql::id_string>::set_image(
        i.m_SteerModeUl_value, size, is_null, v);
    i.m_SteerModeUl_null = is_null;
    i.m_SteerModeUl_size = static_cast<unsigned long>(size);
    grew                 = grew || (cap != i.m_SteerModeUl_value.capacity());
  }

  // m_SteerModeUlIsSet
  //
  {
    bool const& v = o.m_SteerModeUlIsSet;

    bool is_null(false);
    mysql::value_traits<bool, mysql::id_tiny>::set_image(
        i.m_SteerModeUlIsSet_value, is_null, v);
    i.m_SteerModeUlIsSet_null = is_null;
  }

  // m_MulAccCtrl
  //
  {
    ::std::string const& v = o.m_MulAccCtrl;

    bool is_null(false);
    std::size_t size(0);
    std::size_t cap(i.m_MulAccCtrl_value.capacity());
    mysql::value_traits< ::std::string, mysql::id_string>::set_image(
        i.m_MulAccCtrl_value, size, is_null, v);
    i.m_MulAccCtrl_null = is_null;
    i.m_MulAccCtrl_size = static_cast<unsigned long>(size);
    grew                = grew || (cap != i.m_MulAccCtrl_value.capacity());
  }

  // m_MulAccCtrlIsSet
  //
  {
    bool const& v = o.m_MulAccCtrlIsSet;

    bool is_null(false);
    mysql::value_traits<bool, mysql::id_tiny>::set_image(
        i.m_MulAccCtrlIsSet_value, is_null, v);
    i.m_MulAccCtrlIsSet_null = is_null;
  }

  return grew;
}

void access::object_traits_impl<
    ::oai::pcf::provisioning::model::TrafficControlDataODB,
    id_mysql>::init(object_type& o, const image_type& i, database* db) {
  ODB_POTENTIALLY_UNUSED(o);
  ODB_POTENTIALLY_UNUSED(i);
  ODB_POTENTIALLY_UNUSED(db);

  // m_TcId
  //
  {
    ::std::string& v = o.m_TcId;

    mysql::value_traits< ::std::string, mysql::id_string>::set_value(
        v, i.m_TcId_value, i.m_TcId_size, i.m_TcId_null);
  }

  // m_FlowStatus
  //
  {
    ::std::string& v = o.m_FlowStatus;

    mysql::value_traits< ::std::string, mysql::id_string>::set_value(
        v, i.m_FlowStatus_value, i.m_FlowStatus_size, i.m_FlowStatus_null);
  }

  // m_FlowStatusIsSet
  //
  {
    bool& v = o.m_FlowStatusIsSet;

    mysql::value_traits<bool, mysql::id_tiny>::set_value(
        v, i.m_FlowStatusIsSet_value, i.m_FlowStatusIsSet_null);
  }

  // m_RedirectInfo
  //
  {
    ::std::string& v = o.m_RedirectInfo;

    mysql::value_traits< ::std::string, mysql::id_string>::set_value(
        v, i.m_RedirectInfo_value, i.m_RedirectInfo_size,
        i.m_RedirectInfo_null);
  }

  // m_RedirectInfoIsSet
  //
  {
    bool& v = o.m_RedirectInfoIsSet;

    mysql::value_traits<bool, mysql::id_tiny>::set_value(
        v, i.m_RedirectInfoIsSet_value, i.m_RedirectInfoIsSet_null);
  }

  // m_AddRedirectInfo
  //
  {
    ::std::string& v = o.m_AddRedirectInfo;

    mysql::value_traits< ::std::string, mysql::id_string>::set_value(
        v, i.m_AddRedirectInfo_value, i.m_AddRedirectInfo_size,
        i.m_AddRedirectInfo_null);
  }

  // m_AddRedirectInfoIsSet
  //
  {
    bool& v = o.m_AddRedirectInfoIsSet;

    mysql::value_traits<bool, mysql::id_tiny>::set_value(
        v, i.m_AddRedirectInfoIsSet_value, i.m_AddRedirectInfoIsSet_null);
  }

  // m_MuteNotif
  //
  {
    bool& v = o.m_MuteNotif;

    mysql::value_traits<bool, mysql::id_tiny>::set_value(
        v, i.m_MuteNotif_value, i.m_MuteNotif_null);
  }

  // m_MuteNotifIsSet
  //
  {
    bool& v = o.m_MuteNotifIsSet;

    mysql::value_traits<bool, mysql::id_tiny>::set_value(
        v, i.m_MuteNotifIsSet_value, i.m_MuteNotifIsSet_null);
  }

  // m_TrafficSteeringPolIdDl
  //
  {
    ::std::string& v = o.m_TrafficSteeringPolIdDl;

    mysql::value_traits< ::std::string, mysql::id_string>::set_value(
        v, i.m_TrafficSteeringPolIdDl_value, i.m_TrafficSteeringPolIdDl_size,
        i.m_TrafficSteeringPolIdDl_null);
  }

  // m_TrafficSteeringPolIdDlIsSet
  //
  {
    bool& v = o.m_TrafficSteeringPolIdDlIsSet;

    mysql::value_traits<bool, mysql::id_tiny>::set_value(
        v, i.m_TrafficSteeringPolIdDlIsSet_value,
        i.m_TrafficSteeringPolIdDlIsSet_null);
  }

  // m_TrafficSteeringPolIdUl
  //
  {
    ::std::string& v = o.m_TrafficSteeringPolIdUl;

    mysql::value_traits< ::std::string, mysql::id_string>::set_value(
        v, i.m_TrafficSteeringPolIdUl_value, i.m_TrafficSteeringPolIdUl_size,
        i.m_TrafficSteeringPolIdUl_null);
  }

  // m_TrafficSteeringPolIdUlIsSet
  //
  {
    bool& v = o.m_TrafficSteeringPolIdUlIsSet;

    mysql::value_traits<bool, mysql::id_tiny>::set_value(
        v, i.m_TrafficSteeringPolIdUlIsSet_value,
        i.m_TrafficSteeringPolIdUlIsSet_null);
  }

  // m_RouteToLocs
  //
  {
    ::std::string& v = o.m_RouteToLocs;

    mysql::value_traits< ::std::string, mysql::id_string>::set_value(
        v, i.m_RouteToLocs_value, i.m_RouteToLocs_size, i.m_RouteToLocs_null);
  }

  // m_RouteToLocsIsSet
  //
  {
    bool& v = o.m_RouteToLocsIsSet;

    mysql::value_traits<bool, mysql::id_tiny>::set_value(
        v, i.m_RouteToLocsIsSet_value, i.m_RouteToLocsIsSet_null);
  }

  // m_TraffCorreInd
  //
  {
    bool& v = o.m_TraffCorreInd;

    mysql::value_traits<bool, mysql::id_tiny>::set_value(
        v, i.m_TraffCorreInd_value, i.m_TraffCorreInd_null);
  }

  // m_TraffCorreIndIsSet
  //
  {
    bool& v = o.m_TraffCorreIndIsSet;

    mysql::value_traits<bool, mysql::id_tiny>::set_value(
        v, i.m_TraffCorreIndIsSet_value, i.m_TraffCorreIndIsSet_null);
  }

  // m_UpPathChgEvent
  //
  {
    ::std::string& v = o.m_UpPathChgEvent;

    mysql::value_traits< ::std::string, mysql::id_string>::set_value(
        v, i.m_UpPathChgEvent_value, i.m_UpPathChgEvent_size,
        i.m_UpPathChgEvent_null);
  }

  // m_UpPathChgEventIsSet
  //
  {
    bool& v = o.m_UpPathChgEventIsSet;

    mysql::value_traits<bool, mysql::id_tiny>::set_value(
        v, i.m_UpPathChgEventIsSet_value, i.m_UpPathChgEventIsSet_null);
  }

  // m_SteerFun
  //
  {
    ::std::string& v = o.m_SteerFun;

    mysql::value_traits< ::std::string, mysql::id_string>::set_value(
        v, i.m_SteerFun_value, i.m_SteerFun_size, i.m_SteerFun_null);
  }

  // m_SteerFunIsSet
  //
  {
    bool& v = o.m_SteerFunIsSet;

    mysql::value_traits<bool, mysql::id_tiny>::set_value(
        v, i.m_SteerFunIsSet_value, i.m_SteerFunIsSet_null);
  }

  // m_SteerModeDl
  //
  {
    ::std::string& v = o.m_SteerModeDl;

    mysql::value_traits< ::std::string, mysql::id_string>::set_value(
        v, i.m_SteerModeDl_value, i.m_SteerModeDl_size, i.m_SteerModeDl_null);
  }

  // m_SteerModeDlIsSet
  //
  {
    bool& v = o.m_SteerModeDlIsSet;

    mysql::value_traits<bool, mysql::id_tiny>::set_value(
        v, i.m_SteerModeDlIsSet_value, i.m_SteerModeDlIsSet_null);
  }

  // m_SteerModeUl
  //
  {
    ::std::string& v = o.m_SteerModeUl;

    mysql::value_traits< ::std::string, mysql::id_string>::set_value(
        v, i.m_SteerModeUl_value, i.m_SteerModeUl_size, i.m_SteerModeUl_null);
  }

  // m_SteerModeUlIsSet
  //
  {
    bool& v = o.m_SteerModeUlIsSet;

    mysql::value_traits<bool, mysql::id_tiny>::set_value(
        v, i.m_SteerModeUlIsSet_value, i.m_SteerModeUlIsSet_null);
  }

  // m_MulAccCtrl
  //
  {
    ::std::string& v = o.m_MulAccCtrl;

    mysql::value_traits< ::std::string, mysql::id_string>::set_value(
        v, i.m_MulAccCtrl_value, i.m_MulAccCtrl_size, i.m_MulAccCtrl_null);
  }

  // m_MulAccCtrlIsSet
  //
  {
    bool& v = o.m_MulAccCtrlIsSet;

    mysql::value_traits<bool, mysql::id_tiny>::set_value(
        v, i.m_MulAccCtrlIsSet_value, i.m_MulAccCtrlIsSet_null);
  }
}

void access::object_traits_impl<
    ::oai::pcf::provisioning::model::TrafficControlDataODB,
    id_mysql>::init(id_image_type& i, const id_type& id) {
  bool grew(false);
  {
    bool is_null(false);
    std::size_t size(0);
    std::size_t cap(i.id_value.capacity());
    mysql::value_traits< ::std::string, mysql::id_string>::set_image(
        i.id_value, size, is_null, id);
    i.id_null = is_null;
    i.id_size = static_cast<unsigned long>(size);
    grew      = grew || (cap != i.id_value.capacity());
  }

  if (grew) i.version++;
}

const char access::object_traits_impl<
    ::oai::pcf::provisioning::model::TrafficControlDataODB,
    id_mysql>::persist_statement[] =
    "INSERT INTO `TrafficControlDataODB` "
    "(`TcId`, "
    "`FlowStatus`, "
    "`FlowStatusIsSet`, "
    "`RedirectInfo`, "
    "`RedirectInfoIsSet`, "
    "`AddRedirectInfo`, "
    "`AddRedirectInfoIsSet`, "
    "`MuteNotif`, "
    "`MuteNotifIsSet`, "
    "`TrafficSteeringPolIdDl`, "
    "`TrafficSteeringPolIdDlIsSet`, "
    "`TrafficSteeringPolIdUl`, "
    "`TrafficSteeringPolIdUlIsSet`, "
    "`RouteToLocs`, "
    "`RouteToLocsIsSet`, "
    "`TraffCorreInd`, "
    "`TraffCorreIndIsSet`, "
    "`UpPathChgEvent`, "
    "`UpPathChgEventIsSet`, "
    "`SteerFun`, "
    "`SteerFunIsSet`, "
    "`SteerModeDl`, "
    "`SteerModeDlIsSet`, "
    "`SteerModeUl`, "
    "`SteerModeUlIsSet`, "
    "`MulAccCtrl`, "
    "`MulAccCtrlIsSet`) "
    "VALUES "
    "(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, "
    "?, ?, ?)";

const char access::object_traits_impl<
    ::oai::pcf::provisioning::model::TrafficControlDataODB,
    id_mysql>::find_statement[] =
    "SELECT "
    "`TrafficControlDataODB`.`TcId`, "
    "`TrafficControlDataODB`.`FlowStatus`, "
    "`TrafficControlDataODB`.`FlowStatusIsSet`, "
    "`TrafficControlDataODB`.`RedirectInfo`, "
    "`TrafficControlDataODB`.`RedirectInfoIsSet`, "
    "`TrafficControlDataODB`.`AddRedirectInfo`, "
    "`TrafficControlDataODB`.`AddRedirectInfoIsSet`, "
    "`TrafficControlDataODB`.`MuteNotif`, "
    "`TrafficControlDataODB`.`MuteNotifIsSet`, "
    "`TrafficControlDataODB`.`TrafficSteeringPolIdDl`, "
    "`TrafficControlDataODB`.`TrafficSteeringPolIdDlIsSet`, "
    "`TrafficControlDataODB`.`TrafficSteeringPolIdUl`, "
    "`TrafficControlDataODB`.`TrafficSteeringPolIdUlIsSet`, "
    "`TrafficControlDataODB`.`RouteToLocs`, "
    "`TrafficControlDataODB`.`RouteToLocsIsSet`, "
    "`TrafficControlDataODB`.`TraffCorreInd`, "
    "`TrafficControlDataODB`.`TraffCorreIndIsSet`, "
    "`TrafficControlDataODB`.`UpPathChgEvent`, "
    "`TrafficControlDataODB`.`UpPathChgEventIsSet`, "
    "`TrafficControlDataODB`.`SteerFun`, "
    "`TrafficControlDataODB`.`SteerFunIsSet`, "
    "`TrafficControlDataODB`.`SteerModeDl`, "
    "`TrafficControlDataODB`.`SteerModeDlIsSet`, "
    "`TrafficControlDataODB`.`SteerModeUl`, "
    "`TrafficControlDataODB`.`SteerModeUlIsSet`, "
    "`TrafficControlDataODB`.`MulAccCtrl`, "
    "`TrafficControlDataODB`.`MulAccCtrlIsSet` "
    "FROM `TrafficControlDataODB` "
    "WHERE `TrafficControlDataODB`.`TcId`=?";

const char access::object_traits_impl<
    ::oai::pcf::provisioning::model::TrafficControlDataODB,
    id_mysql>::update_statement[] =
    "UPDATE `TrafficControlDataODB` "
    "SET "
    "`FlowStatus`=?, "
    "`FlowStatusIsSet`=?, "
    "`RedirectInfo`=?, "
    "`RedirectInfoIsSet`=?, "
    "`AddRedirectInfo`=?, "
    "`AddRedirectInfoIsSet`=?, "
    "`MuteNotif`=?, "
    "`MuteNotifIsSet`=?, "
    "`TrafficSteeringPolIdDl`=?, "
    "`TrafficSteeringPolIdDlIsSet`=?, "
    "`TrafficSteeringPolIdUl`=?, "
    "`TrafficSteeringPolIdUlIsSet`=?, "
    "`RouteToLocs`=?, "
    "`RouteToLocsIsSet`=?, "
    "`TraffCorreInd`=?, "
    "`TraffCorreIndIsSet`=?, "
    "`UpPathChgEvent`=?, "
    "`UpPathChgEventIsSet`=?, "
    "`SteerFun`=?, "
    "`SteerFunIsSet`=?, "
    "`SteerModeDl`=?, "
    "`SteerModeDlIsSet`=?, "
    "`SteerModeUl`=?, "
    "`SteerModeUlIsSet`=?, "
    "`MulAccCtrl`=?, "
    "`MulAccCtrlIsSet`=? "
    "WHERE `TcId`=?";

const char access::object_traits_impl<
    ::oai::pcf::provisioning::model::TrafficControlDataODB,
    id_mysql>::erase_statement[] =
    "DELETE FROM `TrafficControlDataODB` "
    "WHERE `TcId`=?";

const char access::object_traits_impl<
    ::oai::pcf::provisioning::model::TrafficControlDataODB,
    id_mysql>::query_statement[] =
    "SELECT "
    "`TrafficControlDataODB`.`TcId`, "
    "`TrafficControlDataODB`.`FlowStatus`, "
    "`TrafficControlDataODB`.`FlowStatusIsSet`, "
    "`TrafficControlDataODB`.`RedirectInfo`, "
    "`TrafficControlDataODB`.`RedirectInfoIsSet`, "
    "`TrafficControlDataODB`.`AddRedirectInfo`, "
    "`TrafficControlDataODB`.`AddRedirectInfoIsSet`, "
    "`TrafficControlDataODB`.`MuteNotif`, "
    "`TrafficControlDataODB`.`MuteNotifIsSet`, "
    "`TrafficControlDataODB`.`TrafficSteeringPolIdDl`, "
    "`TrafficControlDataODB`.`TrafficSteeringPolIdDlIsSet`, "
    "`TrafficControlDataODB`.`TrafficSteeringPolIdUl`, "
    "`TrafficControlDataODB`.`TrafficSteeringPolIdUlIsSet`, "
    "`TrafficControlDataODB`.`RouteToLocs`, "
    "`TrafficControlDataODB`.`RouteToLocsIsSet`, "
    "`TrafficControlDataODB`.`TraffCorreInd`, "
    "`TrafficControlDataODB`.`TraffCorreIndIsSet`, "
    "`TrafficControlDataODB`.`UpPathChgEvent`, "
    "`TrafficControlDataODB`.`UpPathChgEventIsSet`, "
    "`TrafficControlDataODB`.`SteerFun`, "
    "`TrafficControlDataODB`.`SteerFunIsSet`, "
    "`TrafficControlDataODB`.`SteerModeDl`, "
    "`TrafficControlDataODB`.`SteerModeDlIsSet`, "
    "`TrafficControlDataODB`.`SteerModeUl`, "
    "`TrafficControlDataODB`.`SteerModeUlIsSet`, "
    "`TrafficControlDataODB`.`MulAccCtrl`, "
    "`TrafficControlDataODB`.`MulAccCtrlIsSet` "
    "FROM `TrafficControlDataODB`";

const char access::object_traits_impl<
    ::oai::pcf::provisioning::model::TrafficControlDataODB,
    id_mysql>::erase_query_statement[] = "DELETE FROM `TrafficControlDataODB`";

const char access::object_traits_impl<
    ::oai::pcf::provisioning::model::TrafficControlDataODB,
    id_mysql>::table_name[] = "`TrafficControlDataODB`";

void access::object_traits_impl<
    ::oai::pcf::provisioning::model::TrafficControlDataODB,
    id_mysql>::persist(database& db, const object_type& obj) {
  using namespace mysql;

  mysql::connection& conn(mysql::transaction::current().connection(db));
  statements_type& sts(conn.statement_cache().find_object<object_type>());

  callback(db, obj, callback_event::pre_persist);

  image_type& im(sts.image());
  binding& imb(sts.insert_image_binding());

  if (init(im, obj, statement_insert)) im.version++;

  if (im.version != sts.insert_image_version() || imb.version == 0) {
    bind(imb.bind, im, statement_insert);
    sts.insert_image_version(im.version);
    imb.version++;
  }

  insert_statement& st(sts.persist_statement());
  if (!st.execute()) throw object_already_persistent();

  callback(db, obj, callback_event::post_persist);
}

void access::object_traits_impl<
    ::oai::pcf::provisioning::model::TrafficControlDataODB,
    id_mysql>::update(database& db, const object_type& obj) {
  ODB_POTENTIALLY_UNUSED(db);

  using namespace mysql;
  using mysql::update_statement;

  callback(db, obj, callback_event::pre_update);

  mysql::transaction& tr(mysql::transaction::current());
  mysql::connection& conn(tr.connection(db));
  statements_type& sts(conn.statement_cache().find_object<object_type>());

  id_image_type& idi(sts.id_image());
  init(idi, id(obj));

  image_type& im(sts.image());
  if (init(im, obj, statement_update)) im.version++;

  bool u(false);
  binding& imb(sts.update_image_binding());
  if (im.version != sts.update_image_version() || imb.version == 0) {
    bind(imb.bind, im, statement_update);
    sts.update_image_version(im.version);
    imb.version++;
    u = true;
  }

  binding& idb(sts.id_image_binding());
  if (idi.version != sts.update_id_image_version() || idb.version == 0) {
    if (idi.version != sts.id_image_version() || idb.version == 0) {
      bind(idb.bind, idi);
      sts.id_image_version(idi.version);
      idb.version++;
    }

    sts.update_id_image_version(idi.version);

    if (!u) imb.version++;
  }

  update_statement& st(sts.update_statement());
  if (st.execute() == 0) throw object_not_persistent();

  callback(db, obj, callback_event::post_update);
  pointer_cache_traits::update(db, obj);
}

void access::object_traits_impl<
    ::oai::pcf::provisioning::model::TrafficControlDataODB,
    id_mysql>::erase(database& db, const id_type& id) {
  using namespace mysql;

  mysql::connection& conn(mysql::transaction::current().connection(db));
  statements_type& sts(conn.statement_cache().find_object<object_type>());

  id_image_type& i(sts.id_image());
  init(i, id);

  binding& idb(sts.id_image_binding());
  if (i.version != sts.id_image_version() || idb.version == 0) {
    bind(idb.bind, i);
    sts.id_image_version(i.version);
    idb.version++;
  }

  if (sts.erase_statement().execute() != 1) throw object_not_persistent();

  pointer_cache_traits::erase(db, id);
}

access::object_traits_impl<
    ::oai::pcf::provisioning::model::TrafficControlDataODB,
    id_mysql>::pointer_type
access::object_traits_impl<
    ::oai::pcf::provisioning::model::TrafficControlDataODB,
    id_mysql>::find(database& db, const id_type& id) {
  using namespace mysql;

  {
    pointer_type p(pointer_cache_traits::find(db, id));

    if (!pointer_traits::null_ptr(p)) return p;
  }

  mysql::connection& conn(mysql::transaction::current().connection(db));
  statements_type& sts(conn.statement_cache().find_object<object_type>());

  statements_type::auto_lock l(sts);

  if (l.locked()) {
    if (!find_(sts, &id)) return pointer_type();
  }

  pointer_type p(access::object_factory<object_type, pointer_type>::create());
  pointer_traits::guard pg(p);

  pointer_cache_traits::insert_guard ig(
      pointer_cache_traits::insert(db, id, p));

  object_type& obj(pointer_traits::get_ref(p));

  if (l.locked()) {
    select_statement& st(sts.find_statement());
    ODB_POTENTIALLY_UNUSED(st);

    callback(db, obj, callback_event::pre_load);
    init(obj, sts.image(), &db);
    load_(sts, obj, false);
    sts.load_delayed(0);
    l.unlock();
    callback(db, obj, callback_event::post_load);
    pointer_cache_traits::load(ig.position());
  } else
    sts.delay_load(id, obj, ig.position());

  ig.release();
  pg.release();
  return p;
}

bool access::object_traits_impl<
    ::oai::pcf::provisioning::model::TrafficControlDataODB,
    id_mysql>::find(database& db, const id_type& id, object_type& obj) {
  using namespace mysql;

  mysql::connection& conn(mysql::transaction::current().connection(db));
  statements_type& sts(conn.statement_cache().find_object<object_type>());

  statements_type::auto_lock l(sts);
  assert(l.locked()) /* Must be a top-level call. */;

  if (!find_(sts, &id)) return false;

  select_statement& st(sts.find_statement());
  ODB_POTENTIALLY_UNUSED(st);

  reference_cache_traits::position_type pos(
      reference_cache_traits::insert(db, id, obj));
  reference_cache_traits::insert_guard ig(pos);

  callback(db, obj, callback_event::pre_load);
  init(obj, sts.image(), &db);
  load_(sts, obj, false);
  sts.load_delayed(0);
  l.unlock();
  callback(db, obj, callback_event::post_load);
  reference_cache_traits::load(pos);
  ig.release();
  return true;
}

bool access::object_traits_impl<
    ::oai::pcf::provisioning::model::TrafficControlDataODB,
    id_mysql>::reload(database& db, object_type& obj) {
  using namespace mysql;

  mysql::connection& conn(mysql::transaction::current().connection(db));
  statements_type& sts(conn.statement_cache().find_object<object_type>());

  statements_type::auto_lock l(sts);
  assert(l.locked()) /* Must be a top-level call. */;

  const id_type& id(object_traits_impl::id(obj));
  if (!find_(sts, &id)) return false;

  select_statement& st(sts.find_statement());
  ODB_POTENTIALLY_UNUSED(st);

  callback(db, obj, callback_event::pre_load);
  init(obj, sts.image(), &db);
  load_(sts, obj, true);
  sts.load_delayed(0);
  l.unlock();
  callback(db, obj, callback_event::post_load);
  return true;
}

bool access::object_traits_impl<
    ::oai::pcf::provisioning::model::TrafficControlDataODB,
    id_mysql>::find_(statements_type& sts, const id_type* id) {
  using namespace mysql;

  id_image_type& i(sts.id_image());
  init(i, *id);

  binding& idb(sts.id_image_binding());
  if (i.version != sts.id_image_version() || idb.version == 0) {
    bind(idb.bind, i);
    sts.id_image_version(i.version);
    idb.version++;
  }

  image_type& im(sts.image());
  binding& imb(sts.select_image_binding());

  if (im.version != sts.select_image_version() || imb.version == 0) {
    bind(imb.bind, im, statement_select);
    sts.select_image_version(im.version);
    imb.version++;
  }

  select_statement& st(sts.find_statement());

  st.execute();
  auto_result ar(st);
  select_statement::result r(st.fetch());

  if (r == select_statement::truncated) {
    if (grow(im, sts.select_image_truncated())) im.version++;

    if (im.version != sts.select_image_version()) {
      bind(imb.bind, im, statement_select);
      sts.select_image_version(im.version);
      imb.version++;
      st.refetch();
    }
  }

  return r != select_statement::no_data;
}

result<access::object_traits_impl<
    ::oai::pcf::provisioning::model::TrafficControlDataODB,
    id_mysql>::object_type>
access::object_traits_impl<
    ::oai::pcf::provisioning::model::TrafficControlDataODB,
    id_mysql>::query(database& db, const query_base_type& q) {
  using namespace mysql;
  using odb::details::shared;
  using odb::details::shared_ptr;

  mysql::connection& conn(mysql::transaction::current().connection(db));

  statements_type& sts(conn.statement_cache().find_object<object_type>());

  image_type& im(sts.image());
  binding& imb(sts.select_image_binding());

  if (im.version != sts.select_image_version() || imb.version == 0) {
    bind(imb.bind, im, statement_select);
    sts.select_image_version(im.version);
    imb.version++;
  }

  std::string text(query_statement);
  if (!q.empty()) {
    text += " ";
    text += q.clause();
  }

  q.init_parameters();
  shared_ptr<select_statement> st(new (shared) select_statement(
      conn, text, false, true, q.parameters_binding(), imb));

  st->execute();

  shared_ptr<odb::object_result_impl<object_type> > r(
      new (shared) mysql::object_result_impl<object_type>(q, st, sts, 0));

  return result<object_type>(r);
}

unsigned long long access::object_traits_impl<
    ::oai::pcf::provisioning::model::TrafficControlDataODB,
    id_mysql>::erase_query(database& db, const query_base_type& q) {
  using namespace mysql;

  mysql::connection& conn(mysql::transaction::current().connection(db));

  std::string text(erase_query_statement);
  if (!q.empty()) {
    text += ' ';
    text += q.clause();
  }

  q.init_parameters();
  delete_statement st(conn, text, q.parameters_binding());

  return st.execute();
}
}  // namespace odb

#include <odb/post.hxx>
