// -*- C++ -*-
//
// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef TRAFFIC_CONTROL_DATA_ODB_ODB_HXX
#define TRAFFIC_CONTROL_DATA_ODB_ODB_HXX

#include <odb/version.hxx>

#include <odb/pre.hxx>

#include "TrafficControlDataODB.h"

#include <memory>
#include <cstddef>
#include <utility>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/no-op-cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb {
// TrafficControlDataODB
//
template<>
struct class_traits< ::oai::pcf::provisioning::model::TrafficControlDataODB> {
  static const class_kind kind = class_object;
};

template<>
class access::object_traits<
    ::oai::pcf::provisioning::model::TrafficControlDataODB> {
 public:
  typedef ::oai::pcf::provisioning::model::TrafficControlDataODB object_type;
  typedef ::oai::pcf::provisioning::model::TrafficControlDataODB* pointer_type;
  typedef odb::pointer_traits<pointer_type> pointer_traits;

  static const bool polymorphic = false;

  typedef ::std::string id_type;

  static const bool auto_id = false;

  static const bool abstract = false;

  static id_type id(const object_type&);

  typedef no_op_pointer_cache_traits<pointer_type> pointer_cache_traits;

  typedef no_op_reference_cache_traits<object_type> reference_cache_traits;

  static void callback(database&, object_type&, callback_event);

  static void callback(database&, const object_type&, callback_event);
};
}  // namespace odb

#include <odb/details/buffer.hxx>

#include <odb/mysql/version.hxx>
#include <odb/mysql/forward.hxx>
#include <odb/mysql/binding.hxx>
#include <odb/mysql/mysql-types.hxx>
#include <odb/mysql/query.hxx>

namespace odb {
// TrafficControlDataODB
//
template<typename A>
struct query_columns<
    ::oai::pcf::provisioning::model::TrafficControlDataODB, id_mysql, A> {
  // TcId
  //
  typedef mysql::query_column<
      mysql::value_traits< ::std::string, mysql::id_string>::query_type,
      mysql::id_string>
      TcId_type_;

  static const TcId_type_ TcId;

  // FlowStatus
  //
  typedef mysql::query_column<
      mysql::value_traits< ::std::string, mysql::id_string>::query_type,
      mysql::id_string>
      FlowStatus_type_;

  static const FlowStatus_type_ FlowStatus;

  // FlowStatusIsSet
  //
  typedef mysql::query_column<
      mysql::value_traits<bool, mysql::id_tiny>::query_type, mysql::id_tiny>
      FlowStatusIsSet_type_;

  static const FlowStatusIsSet_type_ FlowStatusIsSet;

  // RedirectInfo
  //
  typedef mysql::query_column<
      mysql::value_traits< ::std::string, mysql::id_string>::query_type,
      mysql::id_string>
      RedirectInfo_type_;

  static const RedirectInfo_type_ RedirectInfo;

  // RedirectInfoIsSet
  //
  typedef mysql::query_column<
      mysql::value_traits<bool, mysql::id_tiny>::query_type, mysql::id_tiny>
      RedirectInfoIsSet_type_;

  static const RedirectInfoIsSet_type_ RedirectInfoIsSet;

  // AddRedirectInfo
  //
  typedef mysql::query_column<
      mysql::value_traits< ::std::string, mysql::id_string>::query_type,
      mysql::id_string>
      AddRedirectInfo_type_;

  static const AddRedirectInfo_type_ AddRedirectInfo;

  // AddRedirectInfoIsSet
  //
  typedef mysql::query_column<
      mysql::value_traits<bool, mysql::id_tiny>::query_type, mysql::id_tiny>
      AddRedirectInfoIsSet_type_;

  static const AddRedirectInfoIsSet_type_ AddRedirectInfoIsSet;

  // MuteNotif
  //
  typedef mysql::query_column<
      mysql::value_traits<bool, mysql::id_tiny>::query_type, mysql::id_tiny>
      MuteNotif_type_;

  static const MuteNotif_type_ MuteNotif;

  // MuteNotifIsSet
  //
  typedef mysql::query_column<
      mysql::value_traits<bool, mysql::id_tiny>::query_type, mysql::id_tiny>
      MuteNotifIsSet_type_;

  static const MuteNotifIsSet_type_ MuteNotifIsSet;

  // TrafficSteeringPolIdDl
  //
  typedef mysql::query_column<
      mysql::value_traits< ::std::string, mysql::id_string>::query_type,
      mysql::id_string>
      TrafficSteeringPolIdDl_type_;

  static const TrafficSteeringPolIdDl_type_ TrafficSteeringPolIdDl;

  // TrafficSteeringPolIdDlIsSet
  //
  typedef mysql::query_column<
      mysql::value_traits<bool, mysql::id_tiny>::query_type, mysql::id_tiny>
      TrafficSteeringPolIdDlIsSet_type_;

  static const TrafficSteeringPolIdDlIsSet_type_ TrafficSteeringPolIdDlIsSet;

  // TrafficSteeringPolIdUl
  //
  typedef mysql::query_column<
      mysql::value_traits< ::std::string, mysql::id_string>::query_type,
      mysql::id_string>
      TrafficSteeringPolIdUl_type_;

  static const TrafficSteeringPolIdUl_type_ TrafficSteeringPolIdUl;

  // TrafficSteeringPolIdUlIsSet
  //
  typedef mysql::query_column<
      mysql::value_traits<bool, mysql::id_tiny>::query_type, mysql::id_tiny>
      TrafficSteeringPolIdUlIsSet_type_;

  static const TrafficSteeringPolIdUlIsSet_type_ TrafficSteeringPolIdUlIsSet;

  // RouteToLocs
  //
  typedef mysql::query_column<
      mysql::value_traits< ::std::string, mysql::id_string>::query_type,
      mysql::id_string>
      RouteToLocs_type_;

  static const RouteToLocs_type_ RouteToLocs;

  // RouteToLocsIsSet
  //
  typedef mysql::query_column<
      mysql::value_traits<bool, mysql::id_tiny>::query_type, mysql::id_tiny>
      RouteToLocsIsSet_type_;

  static const RouteToLocsIsSet_type_ RouteToLocsIsSet;

  // TraffCorreInd
  //
  typedef mysql::query_column<
      mysql::value_traits<bool, mysql::id_tiny>::query_type, mysql::id_tiny>
      TraffCorreInd_type_;

  static const TraffCorreInd_type_ TraffCorreInd;

  // TraffCorreIndIsSet
  //
  typedef mysql::query_column<
      mysql::value_traits<bool, mysql::id_tiny>::query_type, mysql::id_tiny>
      TraffCorreIndIsSet_type_;

  static const TraffCorreIndIsSet_type_ TraffCorreIndIsSet;

  // UpPathChgEvent
  //
  typedef mysql::query_column<
      mysql::value_traits< ::std::string, mysql::id_string>::query_type,
      mysql::id_string>
      UpPathChgEvent_type_;

  static const UpPathChgEvent_type_ UpPathChgEvent;

  // UpPathChgEventIsSet
  //
  typedef mysql::query_column<
      mysql::value_traits<bool, mysql::id_tiny>::query_type, mysql::id_tiny>
      UpPathChgEventIsSet_type_;

  static const UpPathChgEventIsSet_type_ UpPathChgEventIsSet;

  // SteerFun
  //
  typedef mysql::query_column<
      mysql::value_traits< ::std::string, mysql::id_string>::query_type,
      mysql::id_string>
      SteerFun_type_;

  static const SteerFun_type_ SteerFun;

  // SteerFunIsSet
  //
  typedef mysql::query_column<
      mysql::value_traits<bool, mysql::id_tiny>::query_type, mysql::id_tiny>
      SteerFunIsSet_type_;

  static const SteerFunIsSet_type_ SteerFunIsSet;

  // SteerModeDl
  //
  typedef mysql::query_column<
      mysql::value_traits< ::std::string, mysql::id_string>::query_type,
      mysql::id_string>
      SteerModeDl_type_;

  static const SteerModeDl_type_ SteerModeDl;

  // SteerModeDlIsSet
  //
  typedef mysql::query_column<
      mysql::value_traits<bool, mysql::id_tiny>::query_type, mysql::id_tiny>
      SteerModeDlIsSet_type_;

  static const SteerModeDlIsSet_type_ SteerModeDlIsSet;

  // SteerModeUl
  //
  typedef mysql::query_column<
      mysql::value_traits< ::std::string, mysql::id_string>::query_type,
      mysql::id_string>
      SteerModeUl_type_;

  static const SteerModeUl_type_ SteerModeUl;

  // SteerModeUlIsSet
  //
  typedef mysql::query_column<
      mysql::value_traits<bool, mysql::id_tiny>::query_type, mysql::id_tiny>
      SteerModeUlIsSet_type_;

  static const SteerModeUlIsSet_type_ SteerModeUlIsSet;

  // MulAccCtrl
  //
  typedef mysql::query_column<
      mysql::value_traits< ::std::string, mysql::id_string>::query_type,
      mysql::id_string>
      MulAccCtrl_type_;

  static const MulAccCtrl_type_ MulAccCtrl;

  // MulAccCtrlIsSet
  //
  typedef mysql::query_column<
      mysql::value_traits<bool, mysql::id_tiny>::query_type, mysql::id_tiny>
      MulAccCtrlIsSet_type_;

  static const MulAccCtrlIsSet_type_ MulAccCtrlIsSet;
};

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::TrafficControlDataODB, id_mysql,
    A>::TcId_type_
    query_columns<
        ::oai::pcf::provisioning::model::TrafficControlDataODB, id_mysql,
        A>::TcId(A::table_name, "`TcId`", 0);

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::TrafficControlDataODB, id_mysql,
    A>::FlowStatus_type_
    query_columns<
        ::oai::pcf::provisioning::model::TrafficControlDataODB, id_mysql,
        A>::FlowStatus(A::table_name, "`FlowStatus`", 0);

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::TrafficControlDataODB, id_mysql,
    A>::FlowStatusIsSet_type_
    query_columns<
        ::oai::pcf::provisioning::model::TrafficControlDataODB, id_mysql,
        A>::FlowStatusIsSet(A::table_name, "`FlowStatusIsSet`", 0);

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::TrafficControlDataODB, id_mysql,
    A>::RedirectInfo_type_
    query_columns<
        ::oai::pcf::provisioning::model::TrafficControlDataODB, id_mysql,
        A>::RedirectInfo(A::table_name, "`RedirectInfo`", 0);

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::TrafficControlDataODB, id_mysql,
    A>::RedirectInfoIsSet_type_
    query_columns<
        ::oai::pcf::provisioning::model::TrafficControlDataODB, id_mysql,
        A>::RedirectInfoIsSet(A::table_name, "`RedirectInfoIsSet`", 0);

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::TrafficControlDataODB, id_mysql,
    A>::AddRedirectInfo_type_
    query_columns<
        ::oai::pcf::provisioning::model::TrafficControlDataODB, id_mysql,
        A>::AddRedirectInfo(A::table_name, "`AddRedirectInfo`", 0);

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::TrafficControlDataODB, id_mysql,
    A>::AddRedirectInfoIsSet_type_
    query_columns<
        ::oai::pcf::provisioning::model::TrafficControlDataODB, id_mysql,
        A>::AddRedirectInfoIsSet(A::table_name, "`AddRedirectInfoIsSet`", 0);

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::TrafficControlDataODB, id_mysql,
    A>::MuteNotif_type_
    query_columns<
        ::oai::pcf::provisioning::model::TrafficControlDataODB, id_mysql,
        A>::MuteNotif(A::table_name, "`MuteNotif`", 0);

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::TrafficControlDataODB, id_mysql,
    A>::MuteNotifIsSet_type_
    query_columns<
        ::oai::pcf::provisioning::model::TrafficControlDataODB, id_mysql,
        A>::MuteNotifIsSet(A::table_name, "`MuteNotifIsSet`", 0);

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::TrafficControlDataODB, id_mysql,
    A>::TrafficSteeringPolIdDl_type_
    query_columns<
        ::oai::pcf::provisioning::model::TrafficControlDataODB, id_mysql, A>::
        TrafficSteeringPolIdDl(A::table_name, "`TrafficSteeringPolIdDl`", 0);

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::TrafficControlDataODB, id_mysql,
    A>::TrafficSteeringPolIdDlIsSet_type_
    query_columns<
        ::oai::pcf::provisioning::model::TrafficControlDataODB, id_mysql, A>::
        TrafficSteeringPolIdDlIsSet(
            A::table_name, "`TrafficSteeringPolIdDlIsSet`", 0);

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::TrafficControlDataODB, id_mysql,
    A>::TrafficSteeringPolIdUl_type_
    query_columns<
        ::oai::pcf::provisioning::model::TrafficControlDataODB, id_mysql, A>::
        TrafficSteeringPolIdUl(A::table_name, "`TrafficSteeringPolIdUl`", 0);

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::TrafficControlDataODB, id_mysql,
    A>::TrafficSteeringPolIdUlIsSet_type_
    query_columns<
        ::oai::pcf::provisioning::model::TrafficControlDataODB, id_mysql, A>::
        TrafficSteeringPolIdUlIsSet(
            A::table_name, "`TrafficSteeringPolIdUlIsSet`", 0);

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::TrafficControlDataODB, id_mysql,
    A>::RouteToLocs_type_
    query_columns<
        ::oai::pcf::provisioning::model::TrafficControlDataODB, id_mysql,
        A>::RouteToLocs(A::table_name, "`RouteToLocs`", 0);

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::TrafficControlDataODB, id_mysql,
    A>::RouteToLocsIsSet_type_
    query_columns<
        ::oai::pcf::provisioning::model::TrafficControlDataODB, id_mysql,
        A>::RouteToLocsIsSet(A::table_name, "`RouteToLocsIsSet`", 0);

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::TrafficControlDataODB, id_mysql,
    A>::TraffCorreInd_type_
    query_columns<
        ::oai::pcf::provisioning::model::TrafficControlDataODB, id_mysql,
        A>::TraffCorreInd(A::table_name, "`TraffCorreInd`", 0);

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::TrafficControlDataODB, id_mysql,
    A>::TraffCorreIndIsSet_type_
    query_columns<
        ::oai::pcf::provisioning::model::TrafficControlDataODB, id_mysql,
        A>::TraffCorreIndIsSet(A::table_name, "`TraffCorreIndIsSet`", 0);

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::TrafficControlDataODB, id_mysql,
    A>::UpPathChgEvent_type_
    query_columns<
        ::oai::pcf::provisioning::model::TrafficControlDataODB, id_mysql,
        A>::UpPathChgEvent(A::table_name, "`UpPathChgEvent`", 0);

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::TrafficControlDataODB, id_mysql,
    A>::UpPathChgEventIsSet_type_
    query_columns<
        ::oai::pcf::provisioning::model::TrafficControlDataODB, id_mysql,
        A>::UpPathChgEventIsSet(A::table_name, "`UpPathChgEventIsSet`", 0);

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::TrafficControlDataODB, id_mysql,
    A>::SteerFun_type_
    query_columns<
        ::oai::pcf::provisioning::model::TrafficControlDataODB, id_mysql,
        A>::SteerFun(A::table_name, "`SteerFun`", 0);

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::TrafficControlDataODB, id_mysql,
    A>::SteerFunIsSet_type_
    query_columns<
        ::oai::pcf::provisioning::model::TrafficControlDataODB, id_mysql,
        A>::SteerFunIsSet(A::table_name, "`SteerFunIsSet`", 0);

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::TrafficControlDataODB, id_mysql,
    A>::SteerModeDl_type_
    query_columns<
        ::oai::pcf::provisioning::model::TrafficControlDataODB, id_mysql,
        A>::SteerModeDl(A::table_name, "`SteerModeDl`", 0);

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::TrafficControlDataODB, id_mysql,
    A>::SteerModeDlIsSet_type_
    query_columns<
        ::oai::pcf::provisioning::model::TrafficControlDataODB, id_mysql,
        A>::SteerModeDlIsSet(A::table_name, "`SteerModeDlIsSet`", 0);

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::TrafficControlDataODB, id_mysql,
    A>::SteerModeUl_type_
    query_columns<
        ::oai::pcf::provisioning::model::TrafficControlDataODB, id_mysql,
        A>::SteerModeUl(A::table_name, "`SteerModeUl`", 0);

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::TrafficControlDataODB, id_mysql,
    A>::SteerModeUlIsSet_type_
    query_columns<
        ::oai::pcf::provisioning::model::TrafficControlDataODB, id_mysql,
        A>::SteerModeUlIsSet(A::table_name, "`SteerModeUlIsSet`", 0);

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::TrafficControlDataODB, id_mysql,
    A>::MulAccCtrl_type_
    query_columns<
        ::oai::pcf::provisioning::model::TrafficControlDataODB, id_mysql,
        A>::MulAccCtrl(A::table_name, "`MulAccCtrl`", 0);

template<typename A>
const typename query_columns<
    ::oai::pcf::provisioning::model::TrafficControlDataODB, id_mysql,
    A>::MulAccCtrlIsSet_type_
    query_columns<
        ::oai::pcf::provisioning::model::TrafficControlDataODB, id_mysql,
        A>::MulAccCtrlIsSet(A::table_name, "`MulAccCtrlIsSet`", 0);

template<typename A>
struct pointer_query_columns<
    ::oai::pcf::provisioning::model::TrafficControlDataODB, id_mysql, A>
    : query_columns<
          ::oai::pcf::provisioning::model::TrafficControlDataODB, id_mysql, A> {
};

template<>
class access::object_traits_impl<
    ::oai::pcf::provisioning::model::TrafficControlDataODB, id_mysql>
    : public access::object_traits<
          ::oai::pcf::provisioning::model::TrafficControlDataODB> {
 public:
  struct id_image_type {
    details::buffer id_value;
    unsigned long id_size;
    my_bool id_null;

    std::size_t version;
  };

  struct image_type {
    // m_TcId
    //
    details::buffer m_TcId_value;
    unsigned long m_TcId_size;
    my_bool m_TcId_null;

    // m_FlowStatus
    //
    details::buffer m_FlowStatus_value;
    unsigned long m_FlowStatus_size;
    my_bool m_FlowStatus_null;

    // m_FlowStatusIsSet
    //
    signed char m_FlowStatusIsSet_value;
    my_bool m_FlowStatusIsSet_null;

    // m_RedirectInfo
    //
    details::buffer m_RedirectInfo_value;
    unsigned long m_RedirectInfo_size;
    my_bool m_RedirectInfo_null;

    // m_RedirectInfoIsSet
    //
    signed char m_RedirectInfoIsSet_value;
    my_bool m_RedirectInfoIsSet_null;

    // m_AddRedirectInfo
    //
    details::buffer m_AddRedirectInfo_value;
    unsigned long m_AddRedirectInfo_size;
    my_bool m_AddRedirectInfo_null;

    // m_AddRedirectInfoIsSet
    //
    signed char m_AddRedirectInfoIsSet_value;
    my_bool m_AddRedirectInfoIsSet_null;

    // m_MuteNotif
    //
    signed char m_MuteNotif_value;
    my_bool m_MuteNotif_null;

    // m_MuteNotifIsSet
    //
    signed char m_MuteNotifIsSet_value;
    my_bool m_MuteNotifIsSet_null;

    // m_TrafficSteeringPolIdDl
    //
    details::buffer m_TrafficSteeringPolIdDl_value;
    unsigned long m_TrafficSteeringPolIdDl_size;
    my_bool m_TrafficSteeringPolIdDl_null;

    // m_TrafficSteeringPolIdDlIsSet
    //
    signed char m_TrafficSteeringPolIdDlIsSet_value;
    my_bool m_TrafficSteeringPolIdDlIsSet_null;

    // m_TrafficSteeringPolIdUl
    //
    details::buffer m_TrafficSteeringPolIdUl_value;
    unsigned long m_TrafficSteeringPolIdUl_size;
    my_bool m_TrafficSteeringPolIdUl_null;

    // m_TrafficSteeringPolIdUlIsSet
    //
    signed char m_TrafficSteeringPolIdUlIsSet_value;
    my_bool m_TrafficSteeringPolIdUlIsSet_null;

    // m_RouteToLocs
    //
    details::buffer m_RouteToLocs_value;
    unsigned long m_RouteToLocs_size;
    my_bool m_RouteToLocs_null;

    // m_RouteToLocsIsSet
    //
    signed char m_RouteToLocsIsSet_value;
    my_bool m_RouteToLocsIsSet_null;

    // m_TraffCorreInd
    //
    signed char m_TraffCorreInd_value;
    my_bool m_TraffCorreInd_null;

    // m_TraffCorreIndIsSet
    //
    signed char m_TraffCorreIndIsSet_value;
    my_bool m_TraffCorreIndIsSet_null;

    // m_UpPathChgEvent
    //
    details::buffer m_UpPathChgEvent_value;
    unsigned long m_UpPathChgEvent_size;
    my_bool m_UpPathChgEvent_null;

    // m_UpPathChgEventIsSet
    //
    signed char m_UpPathChgEventIsSet_value;
    my_bool m_UpPathChgEventIsSet_null;

    // m_SteerFun
    //
    details::buffer m_SteerFun_value;
    unsigned long m_SteerFun_size;
    my_bool m_SteerFun_null;

    // m_SteerFunIsSet
    //
    signed char m_SteerFunIsSet_value;
    my_bool m_SteerFunIsSet_null;

    // m_SteerModeDl
    //
    details::buffer m_SteerModeDl_value;
    unsigned long m_SteerModeDl_size;
    my_bool m_SteerModeDl_null;

    // m_SteerModeDlIsSet
    //
    signed char m_SteerModeDlIsSet_value;
    my_bool m_SteerModeDlIsSet_null;

    // m_SteerModeUl
    //
    details::buffer m_SteerModeUl_value;
    unsigned long m_SteerModeUl_size;
    my_bool m_SteerModeUl_null;

    // m_SteerModeUlIsSet
    //
    signed char m_SteerModeUlIsSet_value;
    my_bool m_SteerModeUlIsSet_null;

    // m_MulAccCtrl
    //
    details::buffer m_MulAccCtrl_value;
    unsigned long m_MulAccCtrl_size;
    my_bool m_MulAccCtrl_null;

    // m_MulAccCtrlIsSet
    //
    signed char m_MulAccCtrlIsSet_value;
    my_bool m_MulAccCtrlIsSet_null;

    std::size_t version;
  };

  struct extra_statement_cache_type;

  using object_traits<object_type>::id;

  static id_type id(const image_type&);

  static bool grow(image_type&, my_bool*);

  static void bind(MYSQL_BIND*, image_type&, mysql::statement_kind);

  static void bind(MYSQL_BIND*, id_image_type&);

  static bool init(image_type&, const object_type&, mysql::statement_kind);

  static void init(object_type&, const image_type&, database*);

  static void init(id_image_type&, const id_type&);

  typedef mysql::object_statements<object_type> statements_type;

  typedef mysql::query_base query_base_type;

  static const std::size_t column_count                    = 27UL;
  static const std::size_t id_column_count                 = 1UL;
  static const std::size_t inverse_column_count            = 0UL;
  static const std::size_t readonly_column_count           = 0UL;
  static const std::size_t managed_optimistic_column_count = 0UL;

  static const std::size_t separate_load_column_count   = 0UL;
  static const std::size_t separate_update_column_count = 0UL;

  static const bool versioned = false;

  static const char persist_statement[];
  static const char find_statement[];
  static const char update_statement[];
  static const char erase_statement[];
  static const char query_statement[];
  static const char erase_query_statement[];

  static const char table_name[];

  static void persist(database&, const object_type&);

  static pointer_type find(database&, const id_type&);

  static bool find(database&, const id_type&, object_type&);

  static bool reload(database&, object_type&);

  static void update(database&, const object_type&);

  static void erase(database&, const id_type&);

  static void erase(database&, const object_type&);

  static result<object_type> query(database&, const query_base_type&);

  static unsigned long long erase_query(database&, const query_base_type&);

 public:
  static bool find_(statements_type&, const id_type*);

  static void load_(statements_type&, object_type&, bool reload);
};

template<>
class access::object_traits_impl<
    ::oai::pcf::provisioning::model::TrafficControlDataODB, id_common>
    : public access::object_traits_impl<
          ::oai::pcf::provisioning::model::TrafficControlDataODB, id_mysql> {};

// TrafficControlDataODB
//
}  // namespace odb

#include "TrafficControlDataODB-odb.ixx"

#include <odb/post.hxx>

#endif  // TRAFFIC_CONTROL_DATA_ODB_ODB_HXX
