# SPDX-License-Identifier: MIT
# ---------------------------------------------------------------------
#
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: "pcf-build-cfg"
  namespace: oaicicd-core
spec:
    runPolicy: "Serial"
    source:
        type: "Binary"
    strategy:
        dockerStrategy:
            dockerfilePath: "docker/Dockerfile.pcf.centos"
    output:
        to:
            kind: "ImageStreamTag"
            name: "oai-pcf:latest"
