/**
 * Npcf_PolicyAuthorization Service API
 * PCF Policy Authorization Service.   © 2024, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.3.0-alpha.6
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "ApplicationSessionsCollectionApiImpl.h"

namespace oai::pcf::api {

using namespace oai::model::pcf;
using namespace oai::pcf::app;
using namespace oai::model::common;

ApplicationSessionsCollectionApiImpl::ApplicationSessionsCollectionApiImpl(
    const std::shared_ptr<Pistache::Rest::Router>& rtr,
    const std::shared_ptr<pcf_policy_authorization>& pa_service,
    const std::string& address)
    : ApplicationSessionsCollectionApi(rtr) {
  m_api_handler = std::make_shared<application_sessions_collection_api_handler>(
      pa_service, address);
}

void ApplicationSessionsCollectionApiImpl::post_app_sessions(
    const AppSessionContext& appSessionContext,
    Pistache::Http::ResponseWriter& response) {
  api_response resp  = m_api_handler->post_app_sessions(appSessionContext);
  response.headers() = resp.headers;
  response.send(Pistache::Http::Code(resp.status_code), resp.body);
}

}  // namespace oai::pcf::api
