/**
 * Npcf_PolicyAuthorization Service API
 * PCF Policy Authorization Service.   © 2024, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.3.0-alpha.6
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * ApplicationSessionsCollectionApiImpl.h
 *
 *
 */

#ifndef APPLICATION_SESSIONS_COLLECTION_API_IMPL_H_
#define APPLICATION_SESSIONS_COLLECTION_API_IMPL_H_

#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>
#include <optional>

#include <ApplicationSessionsCollectionApi.h>

#include "AppSessionContext.h"
#include "ExtendedProblemDetails.h"
#include "ProblemDetails.h"
#include <string>

// #include "SmPolicyControl.h"
// #include "SmPolicyDecision.h"
// #include "SmPolicyDeleteData.h"
// #include "SmPolicyUpdateContextData.h"

#include "pcf_app.hpp"
#include "application_sessions_collection_api_handler.h"

namespace oai::pcf::api {

using namespace oai::model::pcf;
using namespace pcf;

class ApplicationSessionsCollectionApiImpl
    : public oai::pcf::api::ApplicationSessionsCollectionApi {
 public:
  explicit ApplicationSessionsCollectionApiImpl(
      const std::shared_ptr<Pistache::Rest::Router>& rtr,
      const std::shared_ptr<pcf_policy_authorization>& pa_service,
      const std::string& address);
  ~ApplicationSessionsCollectionApiImpl() override = default;

  void post_app_sessions(
      const AppSessionContext& appSessionContext,
      Pistache::Http::ResponseWriter& response);

 private:
  std::shared_ptr<application_sessions_collection_api_handler> m_api_handler;
};

}  // namespace oai::pcf::api

#endif
