/**
 * Npcf_PolicyAuthorization Service API
 * PCF Policy Authorization Service.   © 2024, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.3.0-alpha.6
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "EventsSubscriptionDocumentApiImpl.h"

namespace oai::pcf::api {

using namespace oai::model::pcf;

EventsSubscriptionDocumentApiImpl::EventsSubscriptionDocumentApiImpl(
    const std::shared_ptr<Pistache::Rest::Router>& rtr,
    const std::shared_ptr<pcf_policy_authorization>& pa_service,
    const std::string&)
    : EventsSubscriptionDocumentApi(rtr) {
  m_api_handler =
      std::make_shared<events_subscription_document_api_handler>(pa_service);
}

void EventsSubscriptionDocumentApiImpl::delete_events_subsc(
    const std::string& appSessionId, Pistache::Http::ResponseWriter& response) {
  api_response resp  = m_api_handler->delete_events_subsc(appSessionId);
  response.headers() = resp.headers;
  response.send(Pistache::Http::Code(resp.status_code), resp.body);
}
void EventsSubscriptionDocumentApiImpl::update_events_subsc(
    const std::string& appSessionId,
    const EventsSubscReqData& eventsSubscReqData,
    Pistache::Http::ResponseWriter& response) {
  api_response resp =
      m_api_handler->update_events_subsc(appSessionId, eventsSubscReqData);
  response.headers() = resp.headers;
  response.send(Pistache::Http::Code(resp.status_code), resp.body);
}

}  // namespace oai::pcf::api
