/**
 * Npcf_PolicyAuthorization Service API
 * PCF Policy Authorization Service.   © 2024, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.3.0-alpha.6
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * EventsSubscriptionDocumentApiImpl.h
 *
 *
 */

#ifndef EVENTS_SUBSCRIPTION_DOCUMENT_API_IMPL_H_
#define EVENTS_SUBSCRIPTION_DOCUMENT_API_IMPL_H_

#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>
#include <optional>

#include <EventsSubscriptionDocumentApi.h>

#include "EventsSubscPutData.h"
#include "EventsSubscReqData.h"
#include "ProblemDetails.h"
#include "RedirectResponse.h"
#include <string>

#include "pcf_app.hpp"
#include "events_subscription_document_api_handler.h"

namespace oai::pcf::api {

using namespace oai::model::pcf;

class EventsSubscriptionDocumentApiImpl
    : public oai::pcf::api::EventsSubscriptionDocumentApi {
 public:
  explicit EventsSubscriptionDocumentApiImpl(
      const std::shared_ptr<Pistache::Rest::Router>& rtr,
      const std::shared_ptr<pcf_policy_authorization>& pa_service,
      const std::string&);
  ~EventsSubscriptionDocumentApiImpl() override = default;

  void delete_events_subsc(
      const std::string& appSessionId,
      Pistache::Http::ResponseWriter& response);
  void update_events_subsc(
      const std::string& appSessionId,
      const EventsSubscReqData& eventsSubscReqData,
      Pistache::Http::ResponseWriter& response);

 private:
  std::shared_ptr<events_subscription_document_api_handler> m_api_handler;
};

}  // namespace oai::pcf::api

#endif
