/**
 * Npcf_PolicyAuthorization Service API
 * PCF Policy Authorization Service.   © 2024, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.3.0-alpha.6
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * PCSCFRestorationIndicationApiImpl.h
 *
 *
 */

#ifndef PCSCF_RESTORATION_INDICATION_API_IMPL_H_
#define PCSCF_RESTORATION_INDICATION_API_IMPL_H_

#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>
#include <optional>

#include <PCSCFRestorationIndicationApi.h>

#include "PcscfRestorationRequestData.h"
#include "ProblemDetails.h"
#include "RedirectResponse.h"
#include <string>

#include "pcf_app.hpp"
#include "pcscf_restoration_indication_api_handler.h"

namespace oai::pcf::api {

using namespace oai::model::pcf;

class PCSCFRestorationIndicationApiImpl
    : public oai::pcf::api::PCSCFRestorationIndicationApi {
 public:
  explicit PCSCFRestorationIndicationApiImpl(
      const std::shared_ptr<Pistache::Rest::Router>& rtr,
      const std::shared_ptr<pcf_policy_authorization>& pa_service,
      const std::string&);
  ~PCSCFRestorationIndicationApiImpl() override = default;

  void pcscf_restoration(
      const PcscfRestorationRequestData& pcscfRestorationRequestData,
      Pistache::Http::ResponseWriter& response);

 private:
  std::shared_ptr<pcscf_restoration_indication_api_handler> m_api_handler;
};

}  // namespace oai::pcf::api

#endif
