/**
 * Npcf_PolicyAuthorization Service API
 * PCF Policy Authorization Service.   © 2024, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * The version of the OpenAPI document: 1.3.0-alpha.6
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "PCSCFRestorationIndicationApiImpl.h"

namespace oai::pcf::api {

using namespace oai::model::pcf;

PCSCFRestorationIndicationApiImpl::PCSCFRestorationIndicationApiImpl(
    const std::shared_ptr<Pistache::Rest::Router>& rtr,
    const std::shared_ptr<pcf_policy_authorization>& pa_service,
    const std::string&)
    : PCSCFRestorationIndicationApi(rtr) {
  m_api_handler =
      std::make_shared<pcscf_restoration_indication_api_handler>(pa_service);
}

void PCSCFRestorationIndicationApiImpl::pcscf_restoration(
    const PcscfRestorationRequestData& pcscfRestorationRequestData,
    Pistache::Http::ResponseWriter& response) {
  api_response resp =
      m_api_handler->pcscf_restoration(pcscfRestorationRequestData);
  response.headers() = resp.headers;
  response.send(Pistache::Http::Code(resp.status_code), resp.body);
}

}  // namespace oai::pcf::api
